### ISSUE TITLE
API to parse NuGetVersions

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#1022]
We forked the NuGet version parsing code for Portable, but users are now creating project.json files that include Versions that our fork can't parse. (This is DevDiv 1204134). We need an API from NuGet to parse a string into a NuGetVersion so that we don't have to update the project system code every time Version changes.

**Comment by yishaigalatzer** [comment]
@joelverhagen this was fixed I believe, can you please close if so

**Comment by joelverhagen** [comment]
Not fixed (the only version IVS API we have is _comparing_ versions). I talked to @rchande and found this is not needed for Update 3, not Update 2.

**Comment by yishaigalatzer** [comment]
You mean needed for update 3

Sent from Outlook Mobilehttps://aka.ms/xp9y6l

On Wed, Mar 16, 2016 at 11:04 AM -0700, "Joel Verhagen" <notifications@github.com<mailto:notifications@github.com>> wrote:

Not fixed (the only version IVS API we have is comparing versions). I talked to @rchandehttps://github.com/rchande and found this is not needed for Update 3, not Update 2.

##

**Comment by joelverhagen** [comment]
:sweat: yes, precisely.

> Not fixed (the only version IVS API we have is comparing versions). I talked to @rchande and found this is ~~not~~ needed for Update 3, not Update 2.

**Comment by nkolev92** [comment]
Redundant now. 
NuGet.Version has a method to parse the version out of a string.
