### ISSUE TITLE
NuGet restore failing on .NET 5 for Archlinux

### ISSUE THREAD

**Issue by Mizux** [NuGet/Home#10695]
disclaimer: seems related to *NuGet restore failing on .NET 5 for Debian-based OSes (CA trust changed)* aka #10491 

## Details about Problem
Using the archlinux package: `community/dotnet-sdk 5.0.4.sdk104-1` (47.3 MiB 165.6 MiB)

## Repro steps and/or sample project
Here a simple exe to create snk key (since this tools is still not available on MacOS and Linux dotnet cli)
see: https://github.com/dotnet/docs/issues/7183

```sh
$ cd ortools/dotnet/CreateSigningKey
$ cat CreateSigningKey.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <!-- see https://github.com/dotnet/docs/issues/12237 -->
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>
</Project>
```
src: https://github.com/google/or-tools/blob/stable/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj

### Verbose Logs
When trying to restore
```sh
$ dotnet restore
  Determining projects to restore...
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3028: Package 'Microsoft.NETCore.App.Ref 3.1.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.10' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3037: Package 'Microsoft.NETCore.App.Ref 3.1.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3037: Package 'Microsoft.AspNetCore.App.Ref 3.1.10' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3028: Package 'Microsoft.NETCore.App.Ref 3.1.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/home/mizux/work/master/ortools/dotnet/CreateSigningKey/CreateSigningKey.csproj : error NU3028: Package 'Microsoft.AspNetCore.App.Ref 3.1.10' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
```

FYI 
```sh
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.104
 Commit:    ca6b6acadb

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.104/

Host (useful for support):
  Version: 5.0.4
  Commit:  269e323b5f

.NET SDKs installed:
  5.0.104 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Maybe should be added to https://github.com/NuGet/Announcements/issues/49 in "Other distros" ?
EDIT: This issue is added to https://github.com/NuGet/Announcements/issues/56

**Comment by Mizux** [comment]
Also spotted by our public CI -> https://github.com/google/or-tools/runs/2195354201?check_suite_focus=true#step:6:4489

**Comment by Mizux** [comment]
Current workaround: install `dotnet-sdk-3.1` **and** remove `dotnet-sdk`
```sh
pacman -Rcns dotnet-sdk
pacman -S dotnet-sdk-3.1
```

**Comment by heng-liu** [comment]
Hi @Mizux , could you try the commands in the following comments? Thanks!
https://github.com/NuGet/Home/issues/10684#issuecomment-806842279
https://github.com/NuGet/Home/issues/10684#issuecomment-806947048

**Comment by Mizux** [comment]
Seems it fail on archlinux...
```sh
openssl verify -verbose cert.pem
C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2008 VeriSign, Inc. - For authorized use only", CN = VeriSign Universal Root Certification Authority
error 18 at 0 depth lookup: self signed certificate
error cert.pem: verification failed
```

There is no `/etc/ca-certificates.conf` nor any "mozilla" certificate on Archlinux

```sh
$ find /etc/ca-certificates/ -type f -iname "*microsoft*"
/etc/ca-certificates/extracted/cadir/Microsoft_ECC_Root_Certificate_Authority_2017.pem
/etc/ca-certificates/extracted/cadir/Microsoft_RSA_Root_Certificate_Authority_2017.pem

grepc -rIin -A2 "microsoft" /etc/ca-certificates
/etc/ca-certificates/extracted/tls-ca-bundle.pem:2110:# Microsoft ECC Root Certificate Authority 2017
/etc/ca-certificates/extracted/tls-ca-bundle.pem-2111------BEGIN CERTIFICATE-----
/etc/ca-certificates/extracted/tls-ca-bundle.pem-2112-MIICWTCCAd+gAwIBAgIQZvI9r4fei7FK6gxXMQHC7DAKBggqhkjOPQQDAzBlMQsw
--
/etc/ca-certificates/extracted/tls-ca-bundle.pem:2127:# Microsoft RSA Root Certificate Authority 2017
/etc/ca-certificates/extracted/tls-ca-bundle.pem-2128------BEGIN CERTIFICATE-----
/etc/ca-certificates/extracted/tls-ca-bundle.pem-2129-MIIFqDCCA5CgAwIBAgIQHtOXCV/YtLNHcB6qvn9FszANBgkqhkiG9w0BAQwFADBl
--
/etc/ca-certificates/extracted/ca-bundle.trust.crt:2522:# Microsoft ECC Root Certificate Authority 2017
/etc/ca-certificates/extracted/ca-bundle.trust.crt-2523------BEGIN TRUSTED CERTIFICATE-----
/etc/ca-certificates/extracted/ca-bundle.trust.crt-2524-MIICWTCCAd+gAwIBAgIQZvI9r4fei7FK6gxXMQHC7DAKBggqhkjOPQQDAzBlMQsw
--
/etc/ca-certificates/extracted/ca-bundle.trust.crt:2540:# Microsoft RSA Root Certificate Authority 2017
/etc/ca-certificates/extracted/ca-bundle.trust.crt-2541------BEGIN TRUSTED CERTIFICATE-----
/etc/ca-certificates/extracted/ca-bundle.trust.crt-2542-MIIFqDCCA5CgAwIBAgIQHtOXCV/YtLNHcB6qvn9FszANBgkqhkiG9w0BAQwFADBl
```

**Comment by heng-liu** [comment]
Thanks @Mizux !
May I know  if you have run dotnet restore with version above 5.0 successfully before?
Is it happening recently just after you start to use dotnet version 5? Thanks!

**Comment by dbent** [comment]
This can be temporarily worked around by downgrading the [ca-certificates-mozilla](https://archlinux.org/packages/core/x86_64/ca-certificates-mozilla/) package to the previous version of 3.62-1.

The current version (3.63-1) was released on 2021-03-19. The upstream release notes for [NSS 3.63](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.63_release_notes) notes:

> [Bug 1686854](https://bugzilla.mozilla.org/show_bug.cgi?id=1686854) - Remove GeoTrust PCA-G2 and VeriSign Universal root certs from NSS.

[FS#70095](https://bugs.archlinux.org/task/70095) in the Arch Linux bug tracker is tracking the same issue and includes a probably better workaround of manually installing the VeriSign Universal root certificate from 3.62-1 and then upgrading back to 3.63-1.

**Comment by heng-liu** [comment]
Thanks a lot @dbent ! That's very helpful!

FYI @dtivel  @JonDouglas

**Comment by JonDouglas** [comment]
Please note that a .NET 5 release is now available that should resolve this issue. You can find a link to download it on the announcement below:

https://github.com/NuGet/Announcements/issues/56

**Comment by aortiz-msft** [comment]
Closing per last comment. Thank you for your feedback!

**Comment by fnzr** [comment]
Error persists even on 5.0.202:
```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     endeavouros
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  561d6ea60d

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

When trying to build F# (truncated):

```
[...] error NU3037: Package 'System.Net.Http 4.3.0' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json': The repository primary signature validity period has expired. [/home/master/repos/fsharp/src/buildtools/fslex/fslex.fsproj]
    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:02.13
Build failed with exit code 1. Check errors above.
Error building tools (exit code '1').
```

is there other steps I should be taking?

**Comment by Mizux** [comment]
@fnzr like previously reported this is still an open issue tracked in Archlinux...

> [FS#70095](https://bugs.archlinux.org/task/70095) in the Arch Linux bug tracker is tracking the same issue and includes a probably better workaround of manually installing the VeriSign Universal root certificate from 3.62-1 and then upgrading back to 3.63-1.

**Comment by JonDouglas** [comment]
@fnzr Do you have `signatureValidationMode` set to `require` somewhere in a config file? That would likely explain the failure as that .NET SDK should work given signature verification is disabled for it. Try turning the mode to `accept` or removing the node so it will default back to `accept` itself.
