### ISSUE TITLE
5.0.300 dotnet restore ignores proxy settings

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10932]
@jirikopecky commented on [Mon, 31 May 2021 14:34:05 GMT](https://github.com/dotnet/sdk/issues/17991)
Our build server is behind proxy and we use private NuGet feed. This feed have to be accessed directly, without the proxy. Feed DNS name is configured in `no_proxy` environment variable. `dotnet restore` fails with HTTP 504 Gateway Timeout.

Summaray:
- Environment: Docker (using `mcr.microsoft.com/dotnet/sdk:5.0` image)
- Custom NuGet feed configured in NuGet.config (nuget.mycorp.com)
- HTTP(S) proxy configured using `http_proxy` and `https_proxy` env variables
- Using `no_proxy` env variable to configure direct access to custom feed (`no_proxy=nuget.mycorp.com`)
- Restore works with SDK 5.0.203, same setup fails with SDK 5.0.300

**Comment by nkolev92** [comment]
@dotnet-issue-labeler[bot] commented on [Mon, 31 May 2021 14:34:08 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-851531179)
I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by nkolev92** [comment]
@tempel3 commented on [Tue, 01 Jun 2021 07:25:39 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-851892321)
Hello,

i have a similar issue.

While trying to setup a proxy WITH Authentication for the docker build using the nuget.config and environmental variables. The settings are ignored or not handled correctly.

For more information regarding the test setup, please ask.

Best regards
Paul

**Comment by nkolev92** [comment]
@protonyx commented on [Wed, 02 Jun 2021 21:07:22 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-853383219)
I noticed this same issue with SDK v5.0.300. If I clear my proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`), `dotnet restore` begins working (we also have a private feed on our intranet). It seems that the `NO_PROXY` environment variable is being ignored, even when I specify it in a solution-local nuget.config:

```
  <config>
    <add key="http_proxy" value="http://proxy.mycorp.com" />
    <add key="no_proxy" value=".mycorp.com" />
  </config>
```

**Comment by nkolev92** [comment]
@michal-ciechan commented on [Wed, 09 Jun 2021 09:16:59 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857531612)
Adding from https://github.com/NuGet/Home/issues/6981#issuecomment-856852714

_________

My issue is that we need to use proxy for a single source. and not for others. 

We have HTTP_PROXY set so that everything picks it up correctly. 

We also have NO_PROXY set for various domains/IP ranges that cannot go through the proxy.

Global `NuGet.config`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!-- This needs to go through Proxy -->
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

    <!-- This cannot go through Proxy. Has exclusion in NO_PRXY -->
    <add key="TeamCityInternal" value="http://nuget.internal/" />
  </packageSources>
</configuration>
```

And then we have 

```
HTTP_PROXY=http://somproxy
NO_PROXY=.internal
```

This works perfectly fine when running `nuget restore` using `nuget.exe` versions `v5.9.1` or  `v5.10.0-preview2`

It doesn't work when running `dotnet restore` using .NET SDK `5.0.300` or .NET SDK `6.0.100-preview.4`.

Using `dotnet restore` get a 403 forbidden error. (Proxy uses standard NTLM)

**Comment by nkolev92** [comment]
@michal-ciechan commented on [Wed, 09 Jun 2021 09:26:43 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857538659)
`5.0.301` still broken

**Comment by nkolev92** [comment]
@sfoslund commented on [Wed, 09 Jun 2021 15:56:29 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857827017)
FYI @nkolev92

**Comment by nkolev92** [comment]
@nkolev92 commented on [Wed, 09 Jun 2021 18:33:50 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857958916)
Dup in https://github.com/NuGet/Home/issues/10902. 

cc @erdembayar who fixed it. 

fyi @aortiz-msft, we might need to consider patching this.

**Comment by nkolev92** [comment]
@nkolev92 commented on [Wed, 09 Jun 2021 18:38:49 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857964837)
For reference, the fix *is available* in the 5.0.400 dailies, https://github.com/dotnet/sdk/pull/18041.

**Comment by erdembayar** [comment]
Here is link for daily build if someone wants to download 5.0.400 daily build
https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries

**Comment by erdembayar** [comment]
> @nkolev92 commented on [Wed, 09 Jun 2021 18:33:50 GMT](https://github.com/dotnet/sdk/issues/17991#issuecomment-857958916)
> Dup in #10902.
> 
> cc @erdembayar who fixed it.
> 
> fyi @aortiz-msft, we might need to consider patching this.

Do you mean patching latest 5.0.30x? Can I just manually create PR or I have to use darc tool? Please let me know.

**Comment by nkolev92** [comment]
Triage: Fix available in 5.0.400, at this point no plans to service down level.

**Comment by michal-ciechan** [comment]
This is still broken in VS both  `16.10` ~~and `16.11 preview 2`~~



**EDIT**: Seems to be fixed in 16.11.0 preview 2. See https://github.com/NuGet/Home/issues/10932#issuecomment-875514246

**Comment by darrylmelander** [comment]
Can anyone confirm whether the fix has made it into VS 16.10.3, which was released today?  We're holding all Visual Studio updates until this is fixed in Visual Studio itself. If this is still broken in the latest VS, is there a way to notify the VS team that this fix needs to make it into their release stream ASAP?

**Comment by daekblad** [comment]
> Can anyone confirm whether the fix has made it into VS 16.10.3, which was released today? We're holding all Visual Studio updates until this is fixed in Visual Studio itself. If this is still broken in the latest VS, is there a way to notify the VS team that this fix needs to make it into their release stream ASAP?

It's still broken in 16.10.3 as far as I can tell.

**Comment by erdembayar** [comment]
> This is still broken in VS both `16.10` and `16.11 preview 2`

Hi. I can see fix is already in [16.11.0 preview 2](https://visualstudio.microsoft.com/vs/preview/). But it takes time to go in GA version. Could you be able to verify again?
I just verified by installing into clean machine and checked `Preview\....IDE\CommonExtensions\Microsoft\NuGet\NuGet.Configuration.dll` file manually.

**Comment by michal-ciechan** [comment]
> > This is still broken in VS both `16.10` and `16.11 preview 2`
> 
> Hi. I can see fix is already in [16.11.0 preview 2](https://visualstudio.microsoft.com/vs/preview/). But it takes time to go in GA version. Could you be able to verify again?
> I just verified by installing into clean machine and checked `Preview\....IDE\CommonExtensions\Microsoft\NuGet\NuGet.Configuration.dll` file manually.

Can confirm latest preview 2 works for me. 

# 👍 

Not sure why it was broken when I tested last, maybe at the time I didn't have newer version of SDK installed. (been uninstalling/reinstalling them to test various fixes/workarounds/issues around this)

For completeness, I have the following SDKs installed:

```
>dotnet --list-sdks
2.1.509 [C:\Program Files\dotnet\sdk]
2.1.814 [C:\Program Files\dotnet\sdk]
5.0.300 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
5.0.400-preview.21323.10 [C:\Program Files\dotnet\sdk]
```

**Comment by michal-ciechan** [comment]
Not sure why it was broken when I tested last, maybe at the time I didn't have newer version of SDK installed. (been uninstalling/reinstalling them to test various fixes/workarounds/issues around this)
