### ISSUE TITLE
"Upgrade vailable" filter shows upgrades that violate the version constraint

### ISSUE THREAD

**Issue by MartinJohns** [NuGet/Home#1094]
Hello. I'm using Visual Studio 2015 Prof RTM. When I select "Manage NuGet Packages" on my project and select the "Upgrade available" filter I see updates to my packages that violate the version constraint.

Specifically I have this entry in my packages.config:

<package id="Microsoft.AspNet.Mvc" version="4.0.40804.0" targetFramework="net40" allowedVersions="(,5.0.0.0)" />

NuGet shows me an upgrade is available to version 5.2.3.

The expected behavior would be to only show upgrades to versions within my specified constraint.

**Comment by emgarten** [comment]
@MartinJohns what is the entry in packages.config? Are you using allowedVersions?

**Comment by MartinJohns** [comment]
@emgarten 
The entry in my packages.config is this:

<package id="Microsoft.AspNet.Mvc" version="4.0.40804.0" targetFramework="net4" allowedVersions="(, 5.0.0)" />

This clearly says I want all updates until version 5. The NuGet manager in Visual Studio shows that there is an update to version 5 available. This violates the specified allowedVersions constraint.

The PoweShell command "Update-Package" recognizes this constraint correctly. It updates to all packages less than version 5.

Here's an image of the issue:

![Imgur](http://i.imgur.com/bdUxAZz.png)


I just noticed another bug, but I gotta see if there's already an issue. If NuGet found an update and installed it, it will replace my entry in the packages.config with the new version. While doing this it removes the allowedVersions constraint. The expected behavior would be to take this over.

**Comment by yishaigalatzer** [comment]
Thanks for reporting it, this is a regression from Visual Studio 2013.

**Comment by RanjiniM** [comment]
After discussing with Fei, I am assigning this bug to him. Currently while in the dialog we don't read packages.config and apply the constraints in the values show in the dropdown. We always return all listed versions available.Only when we invoke an action version constraints are applied. As Fei is working on redesigning the dialog he is going to add code to read packages.config while populating the dropdown.

**Comment by regisbsb** [comment]
Cool will we need a visual studio update? @RanjiniM

**Comment by yishaigalatzer** [comment]
No visual studio update will be necessary, just a nuget extension update

**Comment by yishaigalatzer** [comment]
This is a duplicate of #333 or at least very closely related. We should fix both in one go

**Comment by yishaigalatzer** [comment]
Also note this comment from a duplicate issue by @Advarius:

Visual Studio 2015 is used. I update package with allowedVersions="[1.0,1.1)" attribute from NuGet Package Manager. Current version of package is 1.0.72, available versions are 1.0.73 and 1.1.1.

Firstly, I can see that version "1.1.1" is available for update, which is not satisfy condition. But moreover, if I use Dependency behavior: "Ignore dependencies", nuget will update package to this version despite of constraint without any message.

**Comment by alpaix** [comment]
Fixed in NuGet/NuGet.Client#501.

**Comment by JohnGalt1717** [comment]
This still isn't fixed. Fully patched VS.net 2015 Update 3 with latest Nuget and the following line:

<package id="jQuery" version="2.2.4" allowedVersions="(, 3.0.0)" targetFramework="net461" />

Still gets version 3 even though that clearly states get everything up to 3.0.0 and stop.

**Comment by yishaigalatzer** [comment]
Do you have 3.5 installed?

**Comment by NathanGloyn** [comment]
I have this problem as well. AFAIK I have latest Nuget installed (3.5.0.1484), but with the following packages entry I see upgrades offered both at a project and solution level:
`  <package id="IdentityModel" version="1.13.1" targetFramework="net452" allowedVersions="(,2.0)" />`

**Comment by jainaashish** [comment]
Can you try with latest NuGet from https://dist.nuget.org/index.html which is 3.5.0.1996 I see it working. If you still see issue, then pls share your sample solution.

**Comment by azachert** [comment]
Just tested - it is working fine with latest version (3.5.0.1996)

**Comment by NathanGloyn** [comment]
This is working if you manage the packages at the individual project level, but if you do it at the solution level it still shows offers upgrades even if all the projects using the package have a restriction on the version.
