### ISSUE TITLE
[Bug]: VS2022: Random NU1301 error on restore packages

### ISSUE THREAD

**Issue by ChristianHaefner** [NuGet/Home#12032]
### NuGet Product Used

MSBuild.exe

### Product Version

Version 17.2.1+52cd2da31

### Worked before?

Version 16.11.2+f32259642

### Impact

I'm unable to use this version

### Repro Steps & Context

Currently we move from VS2019 16.11.x to VS2022 17.2.x. When running a pipeline on a build agent (ADOS 2020 On-Prem and VS2022 17.2.x) we face a NU1301 **randomly, but frequent in always different solutions/projects**:

```
##[error]xxx\xxx.csproj(0,0): Error NU1301: Fehler beim Überprüfen des Stammverzeichnisses der lokalen Quelle "https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/". 
1167>c:\tb\1\s\xxx\xxx.csproj : error NU1301: Fehler beim Überprüfen des Stammverzeichnisses der lokalen Quelle "https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/". [c:\tb\1\s\xxx\subsystemxxx.sln]
```

Corresponding translation for the error message above should be `Failed to verify the root directory of local source`.  The error also occurs randomly with another package URI `https://packages.repo.xxx.de/artifactory/api/nuget/nuget-thirdparty-repo/`.

Unfortunately I haven't been able to get a verbose log with this error until now. Also we don't see this kind of error at all on our build agents with VS2019 16.11.x. 

Questions:  
- Is this a new behavior for 17.2 that this type of error will get raised, while in previous versions of msbuild they have been suppressed (like stated in #11862)?
- Since package URI `https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/` looks quite OK for me,  are there any tips of how to track down the real cause of the error?

We are also using Jfrog Artifactory 7.41.7 as proxy for some official NuGet package sources.

Any help is very appreciated, since the issue blocks us to move to VS2022, because of the frequent build breaks.

**Comment by nkolev92** [comment]
Thanks for filing this @ChristianHaefner 

NU1301 was added to allow NuGet to gracefully fail when a source cannot be accessed. 
Before NuGet would fail and not print an error code, so that'd make it difficult for us to provide instructions on how to deal with these issues and that was especially difficult in Visual Studio. 
So, basically NU1301 is a new error code that is now associated with an error that previous didn't have an error code.

I can't really confirm that NU1301 is like the one in the linked issue. if I had to guess, I'd say no, because we're getting an actual exception your scenario. 

Now onto figuring out the exact root cause,

Can you reproduce this locally on your machine or is it something that can only be reproduced on the CI?

**Comment by ChristianHaefner** [comment]
Thanks for pointing out, that NU1301 is a new error code and that the issue possibly already exists in our environment with VS2019/msbuild16, but doesn't get raised as an error there.

Unfortunately I'm not able to repro this on my local machine, although I did intensive tests so far. It currently only occurs in our CI randomly.

The CI consists of ADOS 2020 and VS2020 17.2.x installed. The pipeline is configured to use msbuild x64 17.2 (from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\). Maybe it is a issue with concurrent restore of multiple projects of one solution. The issue is not related to a special solution or project (we build hundreds and thousands) in our over 5h lasting CI build. But the error also arises in different, much smaller builds.

It seems to be thrown in LocalFolderUtility.GetAndVerifyRootDirectory(string root), but I can't find out why with the given package source URI.

**Comment by nkolev92** [comment]
> The pipeline is configured to use msbuild x64 17.2 (from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64). Maybe it is a issue with concurrent restore of multiple projects of one solution. The issue is not related to a special solution or project (we build hundreds and thousands) in our over 5h lasting CI build. But the error also arises in different, much smaller builds.

Interesting. Running multiple restores concurrently can work, as long as you are not trying to restore the same project in more than 1 restore, then you can hit some race conditions. 

> It seems to be thrown in LocalFolderUtility.GetAndVerifyRootDirectory(string root), but I can't find out why with the given package source URI.

Noticed that and it's definitely peculiar. How are your sources configured? Do you use a nuget.config, or do you specify them in msbuild properties?

**Comment by ChristianHaefner** [comment]
We use a nuget.config looks like the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget-xxx-repo" value="https://packages.repo.xxx.de/artifactory/api/nuget/nuget-xxx-repo/" />
    <add key="nuget-gallery-proxy" value="https://packages.repo.xxx.de/artifactory/api/nuget/v3/nuget-gallery-proxy/" protocolVersion="3"/>
    <add key="nuget-powershellgallery-proxy" value="https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/" />
    <add key="nuget-thirdparty-repo" value="https://packages.repo.xxx.de/artifactory/api/nuget/nuget-thirdparty-repo/" />
 </packageSources>
  <packageSourceCredentials>
    <nuget-xxx-repo>
      <add key="Username" value="xxx" />
      <add key="ClearTextPassword" value="xxx" />
    </nuget-datev-repo>
    <nuget-gallery-proxy>
      <add key="Username" value="xxx" />
      <add key="ClearTextPassword" value="xxx" />
    </nuget-gallery-proxy>
    <nuget-powershellgallery-proxy>
      <add key="Username" value="xxx" />
      <add key="ClearTextPassword" value="xxx" />
    </nuget-powershellgallery-proxy>
    <nuget-thirdparty-repo>
      <add key="Username" value="xxx" />
      <add key="ClearTextPassword" value="xxx" />
    </nuget-thirdparty-repo>
  </packageSourceCredentials>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
  <config>
    <add key="globalPackagesFolder" value=".\EXT\packages" />
  </config>
</configuration>
```

Until now, we see the errors only for the package sources `nuget-powershellgallery-proxy` and `nuget-thirdparty-repo`.

**Comment by nkolev92** [comment]
Thanks for sharing that. That eliminates the commandline parameter escaping issues that can sometimes be encountered with msbuild properties. 

I think the next step would be to try to collect detailed logs, potentially with a longer stack. 

Can you get detailed logs from your command?
It'd be great if you can set NUGET_SHOW_STACK to `true` as well.

**Comment by ChristianHaefner** [comment]
Do you need a log only from a failing build? Currently I hadn't the chance to capture one with detailed logging, but I'll do my best.

**Comment by ChristianHaefner** [comment]
I've captured a log with a `System.NullReferenceException` which we also see during restore, but much more rarely as the error descibed above. Maybe both errors are related. 

To provide the logs at a safe and private location, I opened the MS support ticket 2208220010001823 for this. Please let me know in case you have problems to access the logs.

**Comment by ChristianHaefner** [comment]
In addition I was also able to provide a log with the "verify root directory" error to the same location. It seems that there will be no exception, since I haven't found any stacktrace.

**Comment by zivkan** [comment]
warning: nuget internal implementation discussion ahead.

The error message:
> Error NU1301: Fehler beim Überprüfen des Stammverzeichnisses der lokalen Quelle "https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/". 

[The German message is for the resource string `Log_FailedToVerifyRootDirectory`](https://github.com/NuGet/NuGet.Build.Localization/blob/9087b8e61438260a1e52abf76f250e3e44dd703e/localize/DEU/15/NuGet.Protocol.dll.lcl#L313-L321), whose [English translation is "Failed to verify the root directory of local source '{0}'."](https://github.com/NuGet/NuGet.Client/blob/66de4c89f5bf56201f769d63a53881201fd94cec/src/NuGet.Core/NuGet.Protocol/Strings.resx#L307-L310). It's only used in one place: https://github.com/NuGet/NuGet.Client/blob/5c8c1960a12f8665b4dd02bade0d0aae010fb680/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L829

Given that the code got to this point, it's likely that [`!uriResult.IsFile` is true, causing the exception to be thrown](https://github.com/NuGet/NuGet.Client/blob/5c8c1960a12f8665b4dd02bade0d0aae010fb680/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L817-L821). The file/class, `LocalFolderUtility`, as the name suggests, isn't supposed to be used with HTTP sources.

It doesn't seem like NuGet should get into this scenario, so unless a custom build of NuGet is being used, I think there's a bug, but I haven't yet figured out how it's happening, or why other customers aren't reporting the same error 😕.

@ChristianHaefner how are you restoring?  If you use `dotnet restore`, can you add `dotnet --info` to your CI. If you're using `msbuild -t:restore`, can you add `vswhere` to your CI (maybe you need to use the full path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe").

It doesn't make sense to me why the same version of the .NET SDK or MSBuild (and therefore NuGet) would sometimes fail in this way, sometimes succeed. If different CI machines have different versions of NuGet, that would make more sense to me. I'm curious if we can figure out if your CI randomness is due to different CI agents having different versions, and one version always succeeds and a different version always fails.

**Comment by ChristianHaefner** [comment]
We run a explicit restore by calling the msbuild-Task in our target-File, which will be used as the "build project" for msbuild in our ADOS "Run Build Targets" task.

```xml
  <Target Name="_nugetRestore" Condition="'$(_nuGetRestoreTarget)' != ''">
    <Message Text="# _nugetRestore $(BuildStep) $(DOMAIN)/$(FullSubsystemName) $(NuGetRestoreParameters)" Importance="high" Condition="'$(BuildVerbosity)' != 'minimal'"/>
    <!-- MSBuild NuGet Restore only in separatem Step-->
    <MSBuild
      Targets="$(_nuGetRestoreTarget)"
      Projects="%(_slnItems.Identity)"
      Properties="Configuration=%(Configuration);Platform=%(Platform);UseCommonOutputDirectory=%(UseCommonOutputDirectory);$(NuGetRestoreParameters)"
      BuildInParallel="$(BuildInParallel)"
      ContinueOnError="$(BuildContinueOnError)"/>
  </Target>
```

where $(_nuGetRestoreTarget)=Restore.

Our CI build agents are VDI based and exactly the same, based on one golden image. After every CI build the agent will be destroyed, to ensure that build is repeatable. It's very unlikely that build agents differ.

This is the output of vswhere from one of our used agents:  
```
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere -all
Visual Studio Locator version 3.0.1+e2e4e03c65 [query version 3.2.2137.26324]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 24e857ed
installDate: 23.06.2022 07:45:46
installationName: VisualStudio/17.2.7+32802.462
installationPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
installationVersion: 17.2.32802.462
productId: Microsoft.VisualStudio.Product.Enterprise
productPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Enterprise 2022
description: Skalierbare End-to-End-Lösung für Teams jeder Größe
channelId: VisualStudio.17.Release.LTSC.17.2
channelUri: \\xxx.xxx.de\xxx\xxx\xxx\MS_VS_ENT\2022\release.ltsc.17.2\ChannelManifest.json
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
installChannelUri: \\xxx.xxx.de\xxx\xxx\xxx\MS_VS_ENT\2022\17.2.4\Packages\ChannelManifest.json
installedChannelUri: \\xxx.xxx.de\xxx\xxx\xxx\MS_VS_ENT\2022\release.ltsc.17.2\ChannelManifest.json
layoutPath: \\xxx.xxx.de\xxx\xxx\xxx\MS_VS_ENT\2022\17.2.7\Packages
releaseNotes: https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.7
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=661288
updateDate: 2022-08-15T13:12:14.2042179Z
catalog_buildBranch: d17.2
catalog_buildVersion: 17.2.32802.462
catalog_id: VisualStudio/17.2.7+32802.462
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 17.2.7
catalog_productLine: Dev17
catalog_productLineVersion: 2022
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 7
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 17.2.7+32802.462
catalog_requiredEngineVersion: 3.2.2163.42842
properties_campaignId:
properties_channelManifestId: VisualStudio.17.Release.LTSC.17.2/17.2.7+32802.462
properties_nickname: ENT
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe
```

**Comment by zivkan** [comment]
@ChristianHaefner are you able to reproduce the error locally, if you clean the repo and then restore a few times?  It will make getting more information easier, but it will also be possible on CI, just more work.

Using [SysInternals ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump), we can capture memory dumps when first chance exceptions are thrown. It will be a lot easier if you can separate restore into its own command, rather than doing a restore as part of a longer msbuild script. Also, NuGet unfortunately uses `FatalProtocolException` for many reasons, and in my local testing, it gets thrown thousands of times when the global packages folder doesn't exist. So it's also best to `mkdir $env:USERPROFILE\.nuget\packages` before running this command:

```text
procdump -accepteula -n 99 -e 1 -f System.NotSupportedException -f Stammverzeichnisses -x c:\path\for\dumps\ msbuild -t:restore c:\path\to\solution.sln
```

Since my machine is English, I'd use `"verify the root"` instead of `Stammverzeichnisses`. I wasn't able to capture any dumps with this command, since I can't reproduce the error you're seeing, but I'm reasonably confident that this is the correct procdump arguments to capture what I'd like to see.

If you successfully capture memory dumps of this error, please add them to the Microsoft support ticket you've already opened.

Note that this captures up to 99 dumps. If procdump reaches that limit, it exits, while letting msbuild keep running. But since procdump exits, if you do this on a CI machine, the next step of the CI build will start before msbuild finishes. So you might want to make the `-n 99` number unreasonably large to minimize risk of CI failing. Although all the dumps will eat up disk space, and since you'll need to save them as build artifacts so you can send them to us, it will take a lot of space, so maybe failing the build early if there are more than 10 dumps is good.

Unfortunately, I just can't understand why an HTTP source is being used in a method that should only be used for local sources, so I'd love to know the stack trace when [the NotSupportedException is thrown in GetAndVerifyRootDirectory](https://github.com/NuGet/NuGet.Client/blob/5c8c1960a12f8665b4dd02bade0d0aae010fb680/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L820).

**Comment by ChristianHaefner** [comment]
Unfortunately I haven't been able to reproduce the issue locally, even though I created a batch file where I was continuously build a solution and clean cache immediately after building in a loop. The script ran the whole day and no error occurred. 

First of all I will try to run a restore step in our CI before our build begins and look if see the error as well. If this will happen, I will be able to configure procdump to catch the requested dumps.

I'm currently not sure if we will see that error with that way as you described. Will it be a possible alternative, that you provide a modified version of the corresponding DLL (based on msbuild version 17.2) where you do a stack dump inside the method [GetAndVerifyRootDirectory](https://github.com/NuGet/NuGet.Client/blob/5c8c1960a12f8665b4dd02bade0d0aae010fb680/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L820)?

**Comment by ChristianHaefner** [comment]
Just to give a short feedback to my attempts: I was able to reproduce the issue with the **plain** msbuild call above in our CI.

When I try to run the same command with procdump.exe (as you suggested), the error does not come up until now. I'll keep trying, but not sure if we can produce dumps this way since the error seems to not arise with procdump.

Have you thought about to provide a modified DLL as mentioned above?

**Comment by ChristianHaefner** [comment]
Very funny. Just some minutes after writing above lines the error was there with procdump. Unfortunately no dump was written by procdump. I've uploaded the buildlog to the workspace of the MS support case.

**Comment by ChristianHaefner** [comment]
As I had a closer log to the log I see that there is an other error message in the log, although it's a NU1301, too. I suppose that the error is related to the message "E0434F4D.System.Net.Http.HttpRequestException ("Der Antwortstatuscode gibt keinen Erfolg an: 502 (Bad Gateway).")".

I'll keep going to catch the initial error.

**Comment by paulomorgado** [comment]
@ChristianHaefner you can add the `-f System.Net.Http.HttpRequestException` filter to procdump to catch that one.

**Comment by zivkan** [comment]
HTTP 502 bad gateway is commonly when a CDN endpoint doesn't have a locally cached copy of the requested file, and the CDN endpoint has an error trying to connect to its data source. That is to say, it's not a client-side problem, so collecting memory dumps of it won't be particularly interesting. HTTP, TCP and IP are all fundamentally unreliable (TCP tries to give an impression of reliability, but it has limited success), which is why all internet tools need to have retry loops.

I can provide a custom build of NuGet.Protocol.dll with additional outputs, probably as a vsix that needs to be "installed" (assembly versioning is hard). I'll try to build it later today and attach it here. Warning though it won't be Microsoft signed, so you'll additionally need to configure the machine to ignore strong name errors. I'll provide instructions when I create the build.

**Comment by zivkan** [comment]
Here's a vsix with some `Console.WriteLine` in `LocalFolderUtility.GetAndVerifyRootDirectory`, for VS 17.2.
[NuGet.Tools.vsix.zip](https://github.com/NuGet/Home/files/9465690/NuGet.Tools.vsix.zip)

1. Rename the file to `NuGet.Tools.vsix`.
2. In a Developer PowerShell, or Developer Command Prompt (or just find sn.exe yourself, I think it's in the .NET Framework directory, somewhere under c:\windows)

   ```text
   sn -Vr b03f5f7f11d50a3a
   sn -Vr 31bf3856ad364e35
   ```
   NuGet also has a script to disable strong name verification for these two public keys in our repo: https://github.com/NuGet/NuGet.Client/blob/dev/scripts/utils/DisableStrongNameVerification.ps1

3. If you're doing this locally, you can double-click the vsix to install it. Otherwise, you can use `vsixinstaller.exe NuGet.Tools.vsix`, where `vsixinstaller.exe` is in the VS install directory's `Common7\IDE` sub-directory. [vswhere can help you find vsixinstaller.exe](https://github.com/microsoft/vswhere/wiki/Find-VSIXInstaller).

4. If you ever want to revert this VSIX and go back to the built-in version of NuGet, run `VSIXInstaller.exe /d:NuGet.72c5d240-f742-48d4-a0f1-7016671e405b` (source: https://github.com/NuGet/NuGet.Client/blob/dev/docs/debugging.md#uninstalling-a-custom-version-of-the-nuget-extension-from-visual-studio).

   To re-enable strong name validation for the assemblies that were disabled in step 2, use `-Vu` instead of `-Vr`, but otherwise the same command line: https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool

**Comment by ChristianHaefner** [comment]
Hi Paulo,

I think the HttpRequestException was a short hiccup of our Artifactory proxy for NuGet. We think that it has nothing to do with the initial problem.

I will try to install Andy's modified DLL to our CI Agent and hopefully we will get some more informations with it.

**Comment by ChristianHaefner** [comment]
I'm OOF from 09/02-09/05. Hopefully I can provide some results next Tuesday or Wednesday.

**Comment by ChristianHaefner** [comment]
Fortunately, during my holidays we have that error again with the builds configured with `procdump.exe`.

Here is the extracted information from the dump you are likely interested in. I will upload some dumps to the known workspace of the MS support case.
```
0:017> !pe
Exception object: 000001eb98bb7040
Exception type:   NuGet.Protocol.Core.Types.FatalProtocolException
Message:          Fehler beim Überprüfen des Stammverzeichnisses der lokalen Quelle "https://packages.repo.xxx.de/artifactory/api/nuget/nuget-powershellgallery-proxy/".
InnerException:   System.NotSupportedException, Use !PrintException 000001eb98bb6c98 to see more.
StackTrace (generated):
    SP               IP               Function
    00000066A9CF8E70 00007FFB0477A76B NuGet_Protocol!NuGet.Protocol.LocalFolderUtility.GetAndVerifyRootDirectory(System.String)+0x1cb
    00000066A9CFB740 00007FFB0477A49B NuGet_Protocol!NuGet.Protocol.LocalV3FindPackageByIdResource..ctor(NuGet.Configuration.PackageSource)+0x6b
    00000066A9CFB790 00007FFB0477A311 NuGet_Protocol!NuGet.Protocol.LocalV3FindPackageByIdResourceProvider+<TryCreate>d__1.MoveNext()+0x121
    00000066A9CFB8F0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFB920 00007FFB04775674 NuGet_Protocol!NuGet.Protocol.Core.Types.SourceRepository+<GetResourceAsync>d__16`1[[System.__Canon, mscorlib]].MoveNext()+0x1e4
    00000066A9CFBA70 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFBAA0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFBAD0 00007FFB04774D9C NuGet_Protocol!NuGet.Protocol.Core.Types.SourceRepository+<GetResourceAsync>d__15`1[[System.__Canon, mscorlib]].MoveNext()+0x11c
    00000066A9CFBC20 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFBC50 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFBC80 00007FFB04774563 NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+<EnsureResource>d__26.MoveNext()+0x103
    00000066A9CFBDB0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFBDE0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFBE10 00007FFB04773E7D NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+<FindLibraryCoreAsync>d__20.MoveNext()+0xed
    00000066A9CFBF80 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFBFB0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFBFE0 00007FFB047734C7 NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+<>c__DisplayClass19_0+<<FindLibraryAsync>b__0>d.MoveNext()+0xd7
    00000066A9CFC1C0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC1F0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFC220 00007FFB04772DA8 NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+<FindLibraryAsync>d__19.MoveNext()+0x4b8
    00000066A9CFC1F0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC220 00007FFB04772CE5 NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+<FindLibraryAsync>d__19.MoveNext()+0x3f5
    00000066A9CFC3A0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC3D0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFC400 00007FFB04772636 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<<FindLibraryFromSourcesAsync>g__FindLibraryFromProviderAsync|9_0>d.MoveNext()+0x106
    00000066A9CFC570 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC5A0 00007FFB047720FC NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<FindLibraryFromSourcesAsync>d__9.MoveNext()+0x34c
    00000066A9CFC720 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC750 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFC780 00007FFB047718F6 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<FindLibraryByVersionAsync>d__8.MoveNext()+0x286
    00000066A9CFC8E0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFC910 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFC940 00007FFB04771267 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<FindPackageLibraryMatchAsync>d__6.MoveNext()+0x487
    00000066A9CFCAA0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFCAD0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFCB00 00007FFB0476D233 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<FindLibraryMatchAsync>d__3.MoveNext()+0x5b3
    00000066A9CFCCC0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFCCF0 00007FFB0476C41C NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+<FindLibraryEntryAsync>d__1.MoveNext()+0x21c
    00000066A9CFCF10 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFCF40 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFCF70 00007FFB0476A9B0 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+<CreateGraphNode>d__3.MoveNext()+0x470
    00000066A9CFD1B0 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFD1E0 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFD210 00007FFB0476AF05 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+<CreateGraphNode>d__3.MoveNext()+0x9c5
    00000066A9CFD450 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFD480 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFD4B0 00007FFB04769AC6 NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+<WalkAsync>d__2.MoveNext()+0x1c6
    00000066A9CFD650 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFD680 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFD6B0 00007FFB0476943E NuGet_Commands!NuGet.Commands.ProjectRestoreCommand+<WalkDependenciesAsync>d__13.MoveNext()+0x1ce
    00000066A9CFD860 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20
    00000066A9CFD890 00007FFB61F89AAE mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3e
    00000066A9CFD8C0 00007FFB04767F62 NuGet_Commands!NuGet.Commands.ProjectRestoreCommand+<TryRestoreAsync>d__9.MoveNext()+0x4b2
    00000066A9CFDB50 00007FFB628E8EE0 mscorlib_ni!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x20

StackTraceString: <none>
HResult: 80131500
```

**Comment by zivkan** [comment]
Thank you, that's very helpful.  Unfortunately I'm inexperienced with procdump, and the dumps only contain stack trace, not full memory information. This prevents me from inspecting internal state to try to investigate why the code is getting into a path that shouldn't be possible.  Can you please add `-ma`. Unfortunately it will probably make the dumps a lot larger, but it's what I need to investigate.

I'm reformatting the stack trace, to make it easier to read, plus adding links to relevant source code (note, links are for dev branch's source, but most of this code doesn't change often, so I think there's low risk of there being differences between the it and the VS17.2 code)

> [NuGet_Protocol!NuGet.Protocol.LocalFolderUtility.GetAndVerifyRootDirectory(System.String)](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs#L798-L835)
> [NuGet_Protocol!NuGet.Protocol.LocalV3FindPackageByIdResource..ctor(NuGet.Configuration.PackageSource)](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResource.cs#L78-L90)
> [NuGet_Protocol!NuGet.Protocol.LocalV3FindPackageByIdResourceProvider+\<TryCreate>d__1.MoveNext()](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResourceProvider.cs#L21-L35)
> [NuGet_Protocol!NuGet.Protocol.Core.Types.SourceRepository+\<GetResourceAsync>d__16~1[[System.__Canon, mscorlib]].MoveNext()](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/SourceRepository.cs#L148-L166)
> [NuGet_Protocol!NuGet.Protocol.Core.Types.SourceRepository+\<GetResourceAsync>d__15~1[[System.__Canon, mscorlib]].MoveNext()](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/SourceRepository.cs#L138-L141)
> [NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+\<EnsureResource>d__26.MoveNext()](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs#L549-L565)
> [NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+\<FindLibraryCoreAsync>d__20.MoveNext()](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs#L223-L264)
> NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+\<>c__DisplayClass19_0+\<<FindLibraryAsync>b__0>d.MoveNext()
> NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+\<FindLibraryAsync>d__19.MoveNext()
> NuGet_Commands!NuGet.Commands.SourceRepositoryDependencyProvider+\<FindLibraryAsync>d__19.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<<FindLibraryFromSourcesAsync>g__FindLibraryFromProviderAsync|9_0>d.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<FindLibraryFromSourcesAsync>d__9.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<FindLibraryByVersionAsync>d__8.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<FindPackageLibraryMatchAsync>d__6.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<FindLibraryMatchAsync>d__3.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.ResolverUtility+\<FindLibraryEntryAsync>d__1.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+\<CreateGraphNode>d__3.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+\<CreateGraphNode>d__3.MoveNext()
> NuGet_DependencyResolver_Core!NuGet.DependencyResolver.RemoteDependencyWalker+\<WalkAsync>d__2.MoveNext()
> NuGet_Commands!NuGet.Commands.ProjectRestoreCommand+\<WalkDependenciesAsync>d__13.MoveNext()
> NuGet_Commands!NuGet.Commands.ProjectRestoreCommand+\<TryRestoreAsync>d__9.MoveNext()

For HTTP sources [LocalV3FindPackageByIdResourceProvider.TryCreate's if statement](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResourceProvider.cs#L28-L29) should never be true, but clearly is given the stack trace.

I'd really like to see what all the fields are in the SourceRepository object is, try to try guess what `GetFeedType` is probably returning.

In addition, can you add `dotnet nuget list source` to your CI pipeline, just before the restore, to see if maybe the source name is the HTTP url, but somehow the source path is a local folder?

**Comment by ChristianHaefner** [comment]
Hi Andy, sure I will append the -ma minidump option and the `dotnet nuget list source` cmd. It probably might take another several days until I have a new dump. I get back when I have one!

**Comment by ChristianHaefner** [comment]
Short feedback. I was not able to catch new dumps until today. I'll keep trying...

**Comment by ChristianHaefner** [comment]
After another week of vacation there are still no new dumps. I guess that it is related to the VSIX install you provided above. After applying that, I haven't seen that error at all. Maybe it is already fixed in that version?

Nevertheless I will revert the build agents to the snapshot before applying the VSIX and try again to provide the minidump to you. With that you can hopefully see the root cause more detailed and you can tell me, if this issue is probably already been fixed.

Thanks for your patience!

**Comment by ChristianHaefner** [comment]
Hi Andy, I've uploaded a few minidumps (nugetrestore_fatalprotocolexc_minidump.zip) to the workspace of the MS support case. After uninstalling your provided VSIX the error arises quite fast again.

Let me know what you think. Thanks!

**Comment by ChristianHaefner** [comment]
Hi Andy, did you have the chance to look into the dumps?

**Comment by ChristianHaefner** [comment]
Hi Andy, since there seems to be a security issue with `NuGet.Protocol` (https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.9) it is no longer possible to use your provided VSIX as a temporary workaround for this issue.

Can you please tell us if the issue above is being fixed in VS 17.2.9 and (if not being so), provide us an updated version of the VSIX that contains the security fix?

Thanks! Christian

**Comment by zivkan** [comment]
Sorry for the delay. There's been a lot going on recently.

I just spent another 2 hours looking at it, and it still feels like it should be impossible. I'm still stuck at [what I wrote before](https://github.com/NuGet/Home/issues/12032#issuecomment-1241324338):

> For HTTP sources [LocalV3FindPackageByIdResourceProvider.TryCreate's if statement](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResourceProvider.cs#L28-L29) should never be true, but clearly is given the stack trace.

With the memory dump, I can see there are 10 instances of `NuGet.Protocol.Core.Types.SourceRepository`. There are two whose [FeedTypeOverride](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/SourceRepository.cs#L99) are `FileSystemV3`, but the source for both of those are `C:\..` paths. All 8 others have no (well, `Unknown`) `FeedTypeOverride`. Hence, it should get into [FeedTypeResourceProvider](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/Providers/FeedTypeResourceProvider.cs#L41) and therefore [FeedTypeUtility.GetFeedType](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/Utility/FeedTypeUtility.cs#L16). There are two `PackageSource` instances for the URL reported in the exception, but neither of them are of [type `FeedTypePackageSource`](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/Utility/FeedTypeUtility.cs#L19-L21), so it must be getting to [checking `source.IsHttp`](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/Utility/FeedTypeUtility.cs#L27), and again the managed memory debugging of the memory dump, shows that the value is `true`. 

So it just doesn't make sense that [TryCreate's check for `feedType == FileSystemUnknown || feedType == FileSystemV3` is returning true](https://github.com/NuGet/NuGet.Client/blob/4aa1cb43a161178ce12c7e74121b401ce188ff81/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalV3FindPackageByIdResourceProvider.cs#L28-L29). The memory dump shows it did get there, but I just can't wrap my brain around how it's possible.


I can't remember if I already asked in this thread.  Are you experiencing any other weird problems on your CI?  Is it at all possible that one (or more?) of your CI servers has a hardware fault. It's incredibly unlikely that a machine with a hardware fault would only have this flaky behavior, and not others. But I can't think of any other explanation at this time.


In theory, the following console app should reproduce the bug (add a PackageReference to NuGet.Protocol):

```cs
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;
using NuGet.Configuration;

try
{
    PackageSource packageSource = new PackageSource("https://api.nuget.org/v3/index.json", "my-source-name");
    SourceRepository source = Repository.Factory.GetCoreV3(packageSource);
    FindPackageByIdResource resource = await source.GetResourceAsync<FindPackageByIdResource>();

    Console.WriteLine("Exception did not happen");
    return 0;
}
catch (Exception e)
{
    Console.WriteLine(e);
    return -1;
}
```

I didn't use the URL from your memory dump, or error message, for privacy reasons. At the same time the 'real' URL shouldn't matter, because the code only checks if it's http(s), not the hostname or server path.

Running this on your CI to validate whether or not it happens won't really give me any more information, I still won't know how to fix the problem. But it should be an easier reproduction than restore, if we want to try for some reason. You could run the app in a loop a bunch of times until the process exit code != 0, to try to reproduce it more quickly than 1 execution per CI run.

I'm really sorry, but right now I just don't have any more ideas how to get more information or how to fix the bug. The code conditions look correct, and `LocalV3FindPackageByIdResourceProvider.TryCreate` should not be getting into this path.

**Comment by ChristianHaefner** [comment]
Hi Andy, since the issue never comes up again with your provided VSIX, we currently run our CI infrastructure with this VSIX as a temporary workaround. Most importantly, do we need an updated VSIX which contains the NuGet security update contained in 17.2.9?  

I'm pretty sure that the issue is not related to a hardware defect etc., since we're facing the issue on several Build Agent VMs, all running 17.2.x.

I'll try the test sample next week and get back to you.

**Comment by zivkan** [comment]
My build did nothing more than add `Console.WriteLine` (or maybe using the MSBuild logger, I can't remember) in two places, so there's no logical reason for it to work and not the shipping version. Coming soon will be an update to NuGet in VS16.11 (related to the NuGet Recommender feature), but due to the way that our builds work, it will ship a newly compiled build of all the NuGet DLLs. I can't imagine why the version of NuGet on your build agents would have a problem, but if it my custom build of NuGet really did resolve the problem, then hopefully the new compile will as well.

The October 2022 security advisory only affects Linux and Mac. We didn't even insert an update for NuGet into VS (for Windows). It was added to VS' release notes by error, and I believe we're in the process of getting it removed from VS's release notes.


Edit: and for what it's worth, I created a VM with the de-de locale, and ran my sample 1000 times. It never reproduced the exception.

**Comment by sangwook96** [comment]
Hi
I am glad to see it here.
Recently, I got the same issue and my partner got the same issue.
When we update it to 17.4 preview 2.1 , it happens and there is still it in 17.4 preview 3 version, too.
Now, we could not develop our task in the 2022 preview version.
We think that we need the MS team's help.
Thanks

**Comment by ChristianHaefner** [comment]
Bad news, we hoped that the issue will be solved with 17.4, but we didn't tried it out until now.  
Did you try the "workaround" with installing the VSIX provided here https://github.com/NuGet/Home/issues/12032#issuecomment-1233555901?

**Comment by ChristianHaefner** [comment]
Hi Andy, as you already stated, your provided VSIX contained much more changed files than only `Nuget.Protocol.dll`.

Will it be possible to provide me only that DLL in two versions?  
1. Your current version you're working on
2. Your current version you're working on with the WriteConsole calls you built in

With this I can try, if the issue still persists with your current version of only this special DLL (I guess this is quite the version from VS17.4 preview). If yes, hopefully the version with WriteConsoles might help tracking it down. What do you think?

**Comment by zivkan** [comment]
A vsix is just a zip file with a different extension, so you can open it with your favorite zip program.  However, the Console.WriteLines in that previous version turn out to be not helpful. Also, I'm not really sure it will work to copy just that 1 dll, because of assembly strong names and assembly binding.

Here's another vsix, with hopefully more useful logging, but also includes all the security fixes (despite not affecting Windows):
[NuGet.Tools.vsix.zip](https://github.com/NuGet/Home/files/9892510/NuGet.Tools.vsix.zip)

Same caveats and instructions as [my previous comment](https://github.com/NuGet/Home/issues/12032#issuecomment-1233555901).

Here are my changes, in case we want to refer back to it at some other point: https://github.com/NuGet/NuGet.Client/compare/release-6.2.x...zivkan-gh12032

**Comment by ChristianHaefner** [comment]
Hi Andy, I'm in vacation until 11/11 and get back to you after that. Thanks for your help!

**Comment by zivkan** [comment]
Another idea is to try setting `protocolVersion="2"`, because in theory that should force at least one or two places in the code to assume HTTP, rather than trying to detect http vs local: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources

Also, perhaps you could restoring with nuget.exe, to see if that makes a difference?  The problem with nuget.exe is that it doesn't ship with VS, so needs to be downloaded independently. I also hate nuget.exe for several other reasons and strongly encourage everyone to use msbuild restore instead, but maybe for testing this issue it might be worth a try 🤷‍♂️

Finally, if any of the packages your solution use contains their own msbuild files, there's a chance that restoring the way you do might not work correctly. It's not what you're doing, but `msbuild -t:restore,build` does not work correctly, as MSBuild will not reload files after restore. MSBuild has a nuget specific switch `-restore` which tells it to run restore first, then reload all files, then run other targets, but there's no way to do the same thing from an MSBuild script.  There's a chance that using `<MSBuild Targets="restore"`, like you're doing forces it to reload the files (at least for the restore, you might need to also run build via `<MSBuild Targets="build"`, but I don't know MSBuild well enough to know if it does a re-evaluation of the files already in memory, or if it reloads from disk.  It's not common for customers to run restore via the MSBuild task inside an MSBuild script, so perhaps you could consider running `msbuild -t:restore` as a command line step before your build, rather than as an msbuild task inside an msbuild script.


None of these suggestions will fix the problem where NuGet incorrectly gets into the "local source only" code for an HTTP source, but depending if you care more about getting the underlying bug fixed, or mitigating the issue for yourself, it might be an option.

**Comment by zivkan** [comment]
Thanks to Paulo, the MSBuild team confirmed that doing `<MSBuild Targets="Restore"` followed by `<MSBuild Targets="Build"` will **not** reload files. This means that if any project in your solution uses a package that has msbuild props/targets files (most popular are GitVersioning, SourceLink, but there are a surprising number of packages with `build/*` files) then your current build scripts are not working "correctly".

You should either run `msbuild -t:restore ; msbuild -t:build` as seprate commands, or run `msbuild -restore -t:build` (notice no `t:` for restore) which tells msbuild to run restore, reload files, then run build.

However, I don't see how this could affect the restore failure. It's just more of an FYI to improve correctness.

**Comment by ChristianHaefner** [comment]
Hi Andy, sorry for getting back late.

With your new provided version of the VSIX, the error does't arise either as in the version before. So, unfortunately this doesn't help.

We already do the Nuget restore in a dedicated seperate build step (1. msbuild /t:restore; 2. msbuild /t:rebuild). We did the right thing by chance ;-). But your information may be very helpful for other followers.

In parallel I try to get a Time Travel trace with Paulo. Hopefully I can catch an appropriate one.

I'll let you know, when we have one. Thanks for your help here!

**Comment by ChristianHaefner** [comment]
Andy, just letting you know that I was able to provide a time travel trace to Paulo. He's currently investigating.

**Comment by himanshudwd001** [comment]
@ChristianHaefner Did you get a solution? I'm also facing the exact same error on Visual Studio 2022 for Mac 17.4.2.
<img width="186" alt="Screenshot 2023-01-06 at 12 19 35 AM" src="https://user-images.githubusercontent.com/112612188/210857785-3647b406-265b-413d-b1bc-8639b9895580.png">

**Comment by ChristianHaefner** [comment]
No, until now we don't have a solution for it. The guys are still investigating.

**Comment by zivkan** [comment]
Sorry about the delay. Due to the holiday period, plus personal circumstances, progress has been slow.

I forgot to comment about this, but about two or three weeks ago, I had another look at the memory dumps, and noticed that one of the `PackageSource` instances had `_isHttps == true`, but `_isHttp == false`, which would explain all the other behaviour I described in previous comments. So, I'm reasonably confident that the problem is isolated to [these lines of code](https://github.com/NuGet/NuGet.Client/blob/9a6031899f3ee7682213ec1d1bd05aa6e3ccad12/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSource.cs#L68-L99), but it still looks like it should be impossible. The code looks idempotent to me, and I can't imagine any multi-threading order that would cause this theoretically impossible state. Additionally, the memory dump had a second `PackageSource` instance with the same source name and source URL, but both properties correctly had the `true` value. Therefore, there's something very strange given the same inputs result in different outputs. I just can't figure out how.

While looking at this class, I noticed that it had a problem where the `Is*` properties, and the `GetHashCode()` method, return the wrong values if the source value is changed. So, [I created a PR to fix that theoretical issue](https://github.com/NuGet/NuGet.Client/pull/4995). But `PackageSource.Source`'s setter is never used in NuGet's official tooling, so this doesn't explain the problem from this thread. However, since it changes how the `IsHttp` and `IsHttps` properties are calculated, perhaps it will have an impact on this bug.

If you'd like to test, here's a VSIX for VS17.2 (rebased onto the latest commit on the branch, just in case there have been other fixes since I created the branch) with just the first commit from my PR cherry-picked: [NuGet.Tools.vsix.zip](https://github.com/NuGet/Home/files/10373603/NuGet.Tools.vsix.zip)
You can see the code change in my branch: https://github.com/NuGet/NuGet.Client/compare/release-6.2.x...zivkan-gh12032

However, I think it's very unlikely we'll get permission to make this change on VS17.2 or 17.4 (anything other than the current preview release). Normally we need evidence that a bug fix actually works, either from automatic or manual tests, or a bug fix previously released in preview where telemetry shows an improvement. For this bug, we don't have any relevant telemetry (in fact, NuGet doesn't have any telemetry from command line tools), and we can't reproduce the bug.

**Comment by zivkan** [comment]
Here a VSIX for VS17.4: [NuGet.Tools.vsix.zip](https://github.com/NuGet/Home/files/10425893/NuGet.Tools.vsix.zip)

I updated my branch, rebasing the PR branch onto `release-6.4.x`: https://github.com/NuGet/NuGet.Client/compare/release-6.4.x...zivkan-gh12032

**Comment by ChristianHaefner** [comment]
Thanks Andy! Since the problem is still present in 17.4.x on our side (but very rarely, ~2% of our builds), we will give it a try. 

Currently we test Paulos suggestion with `msbuild.exe /p:RestoreUseStaticGraphEvaluation=True`. Maybe this already will help, too.

I'll let you know how it goes.

**Comment by ChristianHaefner** [comment]
Hi @zivkan, I’ve testing your VSIX (for 17.4.x) for several days now. I haven’t seen the NU1301 issue anymore after applying the VSIX. Do you already know the version where your changes will be applied?

**Comment by zivkan** [comment]
Unfortunately due to major testing infrastructure issues in the beginning of January, we weren't able to get the change in during VS' "easy approval process", and the change was rejected for VS17.5 by the time we were able to mitigate our pipeline issues. I think we even missed 17.6 preview 1, so it will be necessary to wait until 17.6 preview 2 😞 

I can't give dates, but if you look at the release history of older versions of VS, you can probably make a good guess.

**Comment by ChristianHaefner** [comment]
It would be great if we will find it finally in 17.6.x, since this will be the next LTSC we will use.

**Comment by wastegate711** [comment]
Hi
I use the console to create a project
`dotnet new console -n test`
I add package
`dotnet add package System.IO.Ports --version 7.0.0`
build project and `dotnet` can't restore the dependency.
the error started appearing this week.
I tried using JetBrains Rider and it had the same problem.

I have error NU1301: Failed to load the services index for the source https://api.nuget.org/v3/index.json .
OS OpenSuse 15.3 x64
.net6 .net7

**Comment by paulomorgado** [comment]
@wastegate711, what do you get with `curl https://api.nuget.org/v3/index.json`?

**Comment by wastegate711** [comment]
> @wastegate711, what do you get with `curl https://api.nuget.org/v3/index.json`?

returns nothing at all.

**Comment by paulomorgado** [comment]
@wastegate711, nothing means it's not getting there.

Until you get a response using `curl` or a web browser, you have a network access issue.

**Comment by wastegate711** [comment]
![image](https://user-images.githubusercontent.com/13132378/221185950-e6a08f57-3e51-4bda-968b-7d46ece13052.png)


> @wastegate711, nothing means it's not getting there.
> 
> Until you get a response using `curl` or a web browser, you have a network access issue.

`wget` and `curl` returns nothing at all.
but the browser returns.

**Comment by paulomorgado** [comment]
@wastegate711, do you have a proxy set or something?

What does nothing mean?

* HTTP 200 and no content?
* HTTP error status?
* Timeout?

**Comment by wastegate711** [comment]
@paulomorgado 

> do you have a proxy set or something?
i dot have proxy.

> HTTP 200 and no content?
browser return status code 200 and json content.

in console `curl` and `wget` returns nothing (no timeout or errors)

**Comment by paulomorgado** [comment]
Have you tried using [Fiddler](https://www.telerik.com/fiddler) or [Wireshark](https://www.wireshark.org/) to figure out why?

**Comment by SandersAlex** [comment]
![изображение](https://user-images.githubusercontent.com/7251181/223890736-11312f4f-c2e5-4e1f-abac-5683b2a2b2d4.png)

**Comment by paulomorgado** [comment]
![image](https://user-images.githubusercontent.com/470455/223986163-8c735879-441d-4d03-abae-0fd966115b24.png)

**Comment by SandersAlex** [comment]
VS 2019 Community

![изображение](https://user-images.githubusercontent.com/7251181/223990619-3bf03322-5325-4394-904d-47ce36acc116.png)

[nuget.org] Failed to load service index for source https://api.nuget.org/v3/index.json.
   An error occurred while sending the request.
   The underlying connection was closed: An unexpected error occurred while transmitting.
   Unable to read data from transport connection: A program on your host machine terminated the established connection.
   A program on your host machine terminated the established connection
Failed to load service index for source https://api.nuget.org/v3/index.json.

VS 2022 Community

![изображение](https://user-images.githubusercontent.com/7251181/223993008-2ee0c688-cdaa-4298-b4fa-c30a4199a0b6.png)

Some of the resources from the main list simply do not open when checking, some open normally

![изображение](https://user-images.githubusercontent.com/7251181/224019661-86f05152-f921-4625-97f7-91a1c54cfe2d.png)
or

<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:f72e8ce1-301e-0009-6f80-52f824000000 Time:2023-03-09T12:12:49.2198268Z
</Message>
</Error>

**Comment by zivkan** [comment]
@ChristianHaefner VS 17.6 preview 2 shipped overnight.  Are you able to test and validate if your issue is resolved?

**Comment by ChristianHaefner** [comment]
Thanks for notification! We will give it a try in our teambuild QA environment, but this will probably take some time/weeks, because our plan to upgrade to 17.6 will be only in a few weeks. Until then we still need 17.4 in our teambuild QA.

I’ll give feedback, when I know more, but – as mentioned – this will take some time.

@zivkan Thanks a lot for your engagement here!

**Comment by vchtelmakh** [comment]
Deleting a local nuget package reference that had NOTHING to do with my project or my project path caused this error for me. See here: https://www.mrlacey.com/2023/11/this-looks-like-nuget-bug-but-isnt.html

**Comment by Arlodotexe** [comment]
This straight-up prevents building with dotnet when offline. I have air-gapped machines that I do dev work on and this seems like questionable default behavior.
