### ISSUE TITLE
dotnet restore (from nuget) doesn't complete on M1 mac

### ISSUE THREAD

**Issue by tpitman** [NuGet/Home#12329]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet: 7.0.1, arm64 - msbuild: 16.10.1. nuget. Not sure, this gets executed inside of a docker-compose linux build.

### Worked before?

Worked in net6

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Create a asp.net project on M1 Mac
2. Add docker support that includes docker compose support
3. Go to command line in the solution folder where the docker compose file exists
4. Run the command: docker-compose build
5. Wait for any of the tasks that are: RUN dotnet restore "[project file].csproj
6. Notice that on an Intel mac this takes just a few seconds
7. Notice that on an M1 mac this continues and never finishes (I let it run for 15 minutes and it never completed)

**Comment by erdembayar** [comment]
Thank you for filing this issue.
Could you able to test if restore works with simple solution without docker?
Maybe you can create a simple solution with 
`dotnet new console`
`dotnet add package newtonsoft.json`

If above work, then try with simple bare minimum asp.net project.

**Comment by tpitman** [comment]
Restore seems to work fine in all cases when not building for docker. I believe it is when trying to build for x86 docker images that the issue occurs.

I created a new asp.net 7 web app.

I did right click on the project and added docker support.

I then went to a terminal and did docker-compose build. This works.

Then I add the following line to the docker-compose.yml file:

`platform: linux/amd64`

Then I do docker-compose build again and it has the issue.

I need that line because Azure requires x86 linux containers, so I have to force the output image to be amd64. If I don't then the resulting image is for arm and won't run on Azure.

Here is the full docker-compose file:

`version: '3.7'`
` `
`services:`
`  nugetdotnetrestoretest:`
`    platform: linux/amd64`
`    image: ${DOCKER_REGISTRY-}nugetdotnetrestoretest`
`    build:`
`      context: .`
`      dockerfile: NugetDotnetRestoreTest/Dockerfile`

**Comment by erdembayar** [comment]
Could we be able to share us `NugetDotnetRestoreTest` code after removing sensitive information?

**Comment by tpitman** [comment]
It is probably just as easy for you to create a new one. I didn't change anything in the project except adding that line in the docker-compose.yml file.

It might even validate that it happens for everyone.

If you are not able to then I will go through all the files and remove any personal information and upload it.

Thank you for helping out.

**Comment by erdembayar** [comment]
Docker is not our expertise, we might miss out something from repro. If you could provide us repro code, then it would be easier for us to diagnose.
By the way does this repro on non-M1 MAC? Don't have M1 MAC ready for test.

**Comment by tpitman** [comment]
Ok. I uploaded the example: https://github.com/tpitman/NugetDotnetRestoreTest

It will work fine on an Intel Mac.

You will need to do the docker-compose build on an M1 Mac.

The issue is completely related to trying to build on M1 mac to Linux container that targets Intel processors.

**Comment by erdembayar** [comment]
Sorry, currently many folks are OOF due to holiday. We need to wait another 1-2 weeks before we can do anything about it.
Thank you.

**Comment by tpitman** [comment]
I understand. I can get by by using my Intel mac. Means having to carry around 2, but hopefully you guys will get it figured out soon after the holidays.

**Comment by tobsai** [comment]
I am seeing the same issue on M1.

**Comment by zivkan** [comment]
Nobody has copied the error message in this issue. I don't have any Mac, let alone a M1 Mac.  Is it the same error as https://github.com/NuGet/Home/issues/12227?  Although it seems like that error might be due to qemu, rather than ARM more generally.

**Comment by tpitman** [comment]
There isn't an error that I have seen. The dotnet restore step just keeps going. I let it go for 10 minutes before giving up.

It is possible that if I let it go long enough maybe it would give an error.

I am also not sure whether they are related because I don't think I am using buildx. I am just running docker-compose build and don't see it reference buildx anywhere.

**Comment by zivkan** [comment]
Can you use [`dotnet-dump`](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) to get a (managed?) memory dump of the process, so we can try to see where it got stuck?  Although the direct downloads for `dotnet-dump` don't have an ARM64 version. This also assumes it's something in managed code causing problems, not the runtime itself.

If `dotnet-dump` doesn't work on ARM64 Macs, then I can ask some dotnet runtime people for advice on investigating, although there's a good chance nobody will be around until January.

**Comment by tpitman** [comment]
Can you give some details on how to use that so I get the right information to you? I installed the dotnet-dump tool. It appears that I have to give it a process Id to collect from.

The problem doesn't occur until I do a docker-compose command and part of that includes the dotnet restore that is getting stuck and only because one of the parameters inside the docker-compose.yml file is the platform = amd64.

So when do I run the dotnet-dump and what process do I do it on? I am doing the docker-compose build command in the source folder of my solution at a terminal session inside VS, but it also happens when I do it in any terminal session on the arm64 M1 mac.

**Comment by zivkan** [comment]
I have next to zero experience with docker. But my understanding is that you can run images in interactive mode `docker run -it`. Presumably if compose is having a problem, I imagine if you run the same image interactively, then manually running `dotnet restore` in the contain will also encounter the problem, and therefore you're able to run the process in the background, get the PID, and then run `dotnet-dump` within the container.

If this problem is only happening in docker, not on the physical machine directly, you might have better luck discussing at https://github.com/dotnet/dotnet-docker/discussions, where there are docker experts.

**Comment by zivkan** [comment]
Also, is QEMU involved in running your docker image?  It might be related to https://github.com/dotnet/sdk/issues/27190 (just in reverse, running a non-ARM64 image on an ARM64 host)

**Comment by tpitman** [comment]
Thank you for all the help and research. This is getting above my head quickly.

Since it is very easy for anyone with an M1 mac to reproduce, I think I might wait until someone with more knowledge and experience and an M1 mac can reproduce this issue and offer more than I can give.

**Comment by aortiz-msft** [comment]
@tpitman - Does this reproduce on M1 Mac without Docker? Our current understanding is that Docker is required to repro this issue. In that case, you may get a faster response by posting in https://github.com/dotnet/dotnet-docker/discussions as @zivkan  suggested.

**Comment by tpitman** [comment]
I will give that a try. Please leave this open as Erick said there might be some people there who can help once they are back from vacation.

I also posted this int he dotnet/sdk originally and they said this appears to be a nuget thing....

**Comment by tpitman** [comment]
Posted here in case anyone wants to join in there:

https://github.com/dotnet/dotnet-docker/discussions/4285

**Comment by joergjo** [comment]
The issue repros on ARM64 Docker hosts running Linux (Ubuntu 22 LTS) as well. `dotnet restore` just hangs forever.

**Comment by kartheekp-ms** [comment]
@tpitman - Can you please run the restore command with `--verbosity detailed` option and paste the log here?

https://learn.microsoft.com/dotnet/core/tools/dotnet-restore#options

**Comment by tpitman** [comment]
Since this is running in a container I can't figure out how to capture the output of that command. It only shows up on the console where I ran it while it is happening, then gets rolled up into a single line when it is done.

How can I capture the output for you?

**Comment by tpitman** [comment]
Turns out that you get no output at all.

In order to get the output I had to modify the files in the test project I have created, do docker-compose build and then start the container and exec into it.

Once you do that you can run comands like dotnet --version and even dotnet restore --version and get results, but if you run the command like this:

`dotnet restore --verbosity detailed "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"`

You get nothing at all. Ctrl-C doesn't do anything either. So it looks like the dotnet restore just won't run on an ARM computer like M1 when trying to create a linux/amd64 (intel) image.

Hopefully you guys can figure out a way to debug this, because I have no idea at this point.

You can get to the git repo here:

[https://github.com/tpitman/NugetDotnetRestoreTest](https://github.com/tpitman/NugetDotnetRestoreTest)

Make sure you use the terminal-test branch.

If you get that on an M1 mac and follow what I said above you can poke around in the container using this standard docker command:

`docker exec -it xxxxxx bash`

where xxxxx is the process id of the running container.

**Comment by tpitman** [comment]
By the way the versions that are output are:

`dotnet --version : 7.0.101`
`dotnet restore --version : 17.4.0.51802`

When I do `uname --all I get this:`

`Linux cea42bad34ea 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64 GNU/Linux`

Running on my M1 mac.

**Comment by thetechyghost** [comment]
I am running into the same issue.

**Comment by tpitman** [comment]
> @tpitman - Can you please run the restore command with `--verbosity detailed` option and paste the log here?
> 
> https://learn.microsoft.com/dotnet/core/tools/dotnet-restore#options

Did you see my reply of what is happening when trying to gather more information? There is no output.

**Comment by joergjo** [comment]
The problem seems fixed in .NET 7.0.2. It no longer hangs on my M2 Mac.

**Comment by tpitman** [comment]
> The problem seems fixed in .NET 7.0.2. It no longer hangs on my M2 Mac.

I am still seeing the issue.

Would you be willing to get the github sample project I created and try doing the docker-compose build and record it for me if it works?

Here is the link to the github project:

https://github.com/tpitman/NugetDotnetRestoreTest

Give details on how you got it to work.

I noticed that when I just ran it, the docker container still showed 7.0.101 version, so you will have to modify the docker file and change the image for FROM to be 7.0.102 instead of just 7.0.

Please let me know what you find.

**Comment by kartheekp-ms** [comment]
@tpitman - By any chance are you experiencing this issue because of https://github.com/NuGet/Home/issues/12365#issuecomment-1387319370?

**Comment by tpitman** [comment]
> @tpitman - By any chance are you experiencing this issue because of [#12365 (comment)](https://github.com/NuGet/Home/issues/12365#issuecomment-1387319370)?

I am not exactly sure how to test this. Currently here is the results of export in the container:

`declare -x ASPNET_VERSION="7.0.2"`
`declare -x DOTNET_GENERATE_ASPNET_CERTIFICATE="false"`
`declare -x DOTNET_NOLOGO="true"`
`declare -x DOTNET_RUNNING_IN_CONTAINER="true"`
`declare -x DOTNET_SDK_VERSION="7.0.102"`
`declare -x DOTNET_USE_POLLING_FILE_WATCHER="true"`
`declare -x DOTNET_VERSION="7.0.2"`
`declare -x HOME="/root"`
`declare -x HOSTNAME="[redacted]"`
`declare -x NUGET_XMLDOC_MODE="skip"`
`declare -x OLDPWD`
`declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`
`declare -x POWERSHELL_DISTRIBUTION_CHANNEL="PSDocker-DotnetSDK-Debian-11"`
`declare -x PWD="/src"`
`declare -x SHLVL="1"`
`declare -x TERM="xterm"`

I do not see anything in there where HOME has a slash or a ';' at the end

Please explain how this might be related and I will test it.

**Comment by kartheekp-ms** [comment]
Thanks for the details. I think this issue & https://github.com/NuGet/Home/issues/12365 are related because @ZeroSkill1 mentioned in the [comment](https://github.com/NuGet/Home/issues/12365#issuecomment-1387319370) that they are experiencing the same issue when executed as root user because HOME path is set to /root. In you case, I see `declare -x HOME="/root"` log.

Would it be possible to run the dotnet restore on a normal user account and let us know if you are experiencing the same issue?

**Comment by tpitman** [comment]
This is a docker container coming directly from mcr.microsoft.com/dotnet/sdk:7.0. There doesn't seem to be any other users.

This works fine when building for ARM on the M1 or when building for Intel on and Intel.

**Comment by tpitman** [comment]
I have done some more testing.

dotnet nuget --version works without making any changes to the HOME env variable.

dotnet nuget restore still hangs even after setting HOME to something other than /root

**Comment by ZeroSkill1** [comment]
Note that when I found this "fix", I was using SDK version 7.0.102.

**Comment by tpitman** [comment]
> Note that when I found this "fix", I was using SDK version 7.0.102.

I too saw a post about this being fixed in 7.0.102, but my testing has not confirmed that. I added code to the example project that output the version using dotnet --version, it showed 7.0.102, but still hung up on the dotnet restore command.

If someone else can take the example project mentioned above and have it work on an M1 mac and give details, I would love to see it.

**Comment by joergjo** [comment]
I retract my previous statement - both your sample project and mine hang as before. Not sure how I fooled myself, but anyway... back to square one.

**Comment by tpitman** [comment]
> I retract my previous statement - both your sample project and mine hang as before. Not sure how I fooled myself, but anyway... back to square one.

Sorry to hear that. I was really hoping it was just something I was doing different. Thank you for helping....

**Comment by kartheekp-ms** [comment]
@joergjo - Can you please capture dump of the running process (using dotnet-dump command) on docker environment? I am only interested in the call stack that is causing restore to wait indefinitely.

**Comment by kartheekp-ms** [comment]
> dotnet nuget --version works without making any changes to the HOME env variable.

@tpitman  - Good to know. In your sample repo, I see that `.csproj` file don't have any package reference. https://github.com/tpitman/NugetDotnetRestoreTest/blob/main/NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj

Would it be possible to add a package reference to a package (for example Newtonsoft.Json from nuget.org) and see if restore succeeds?

> dotnet add package Newtonsoft.Json --version 13.0.2

or update csproje file as shown below.

```
<ItemGroup>
   <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
</ItemGroup>
```

**Comment by tpitman** [comment]
That did not make any difference that I could tell. It still didn't proceed to do anything.

Good idea, though :-).

**Comment by jstedfast** [comment]
I just tried this (hopefully I did it correctly) and I think I also hit the hang:

```
[jestedfa@localhost NugetDotnetRestoreTest]$ docker-compose build                  
[+] Building 86.9s (11/17)                                                                                              
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 869B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0.102                                              0.2s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0                                               0.2s
 => [build 1/7] FROM mcr.microsoft.com/dotnet/sdk:7.0.102@sha256:028d360c0f409f13daf8689edfe680dba9d4b651eb8a6f12  0.0s
 => [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:debec27f5579ddee99c2fd5616ee18def873aa83ad68e7b563  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 848.98kB                                                                              0.0s
 => CACHED [base 2/2] WORKDIR /app                                                                                 0.0s
 => CACHED [final 1/2] WORKDIR /app                                                                                0.0s
 => CACHED [build 2/7] WORKDIR /src                                                                                0.0s
 => CACHED [build 3/7] COPY [NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj, NugetDotnetRestoreTest/]        0.0s
 => [build 4/7] RUN dotnet restore "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"
```

I am on a MacBook Pro M1 machine with the "Apple Chip" version of Docker installed (by default, when you go to the Download section of Docker's website, it offers you the x64 version - you have to specifically click the "Apple Chip" link below the big "Download" button).

I also modified the Docker file to use `dotnet restore -v diag` to see if anything got logged, but nothing:

```
 => [build 4/7] RUN dotnet restore -v diag "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"                 57.2s
```

What I can say is that if I use a bogus verbosity level, the `dotnet restore` command *does* error out:

```
 => ERROR [build 4/7] RUN dotnet restore -v bogus "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"           3.7s
------                                                                                                                  
 > [build 4/7] RUN dotnet restore -v bogus "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj":                      
#0 3.289 System.InvalidOperationException: Cannot parse argument 'bogus' for option '-v' as expected type 'Microsoft.DotNet.Cli.VerbosityOptions'.                                                                                              
#0 3.289    at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)       
#0 3.289    at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()                                           
#0 3.290    at System.CommandLine.Parsing.SymbolResult.GetValueForOption[T](Option`1 option)
#0 3.290    at Microsoft.DotNet.Cli.ParseResultExtensions.SafelyGetValueForOption[T](ParseResult parseResult, Option`1 optionToGet)
#0 3.290    at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName, Dictionary`2 measurements)
#0 3.290    at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
#0 3.290    at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
#0 3.290    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
#0 3.290    at Microsoft.DotNet.Cli.Program.Main(String[] args)
------
failed to solve: executor failed running [/bin/sh -c dotnet restore -v bogus "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"]: exit code: 1
```

Not sure if that information is helpful or not, but maybe it helps determine if the issue is the dotnet program itself hanging at startup vs the dotnet program hanging trying to restore a project.

**Comment by kartheekp-ms** [comment]
> I also modified the Docker file to use dotnet restore -v diag to see if anything got logged, but nothing:
 => [build 4/7] RUN dotnet restore -v diag "NugetDotnetRestoreTest/NugetDotnetRestoreTest.csproj"   

@jstedfast - Thank you for taking the time to reproduce this issue. Can you please follow the steps suggested in https://github.com/dotnet/dotnet-docker/discussions/4285#discussioncomment-4757664 and https://github.com/dotnet/dotnet-docker/discussions/4285#discussioncomment-4758844 and provide us with the call stack that is causing this issue?

**Comment by jstedfast** [comment]
I couldn't figure out how to get dotnet-dump working for this yesterday and have to get back to other tasks, but if someone can provide me with a clearer set of instructions, I can give it another try.

**Comment by erdembayar** [comment]
> I couldn't figure out how to get dotnet-dump working for this yesterday and have to get back to other tasks, but if someone can provide me with a clearer set of instructions, I can give it another try.

Sorry for getting back this issue late. I was busy with other stuff, also don't have MAC M1 machine, catching up today.
I just tested that `dotnet-dump` doesn't work on MAC M1 machine, it only works on intel base MAC. 
If look at [the doc](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) then it only supports intel x64.

<img src="https://user-images.githubusercontent.com/8766776/214731648-d4be9ff1-51e7-4d82-915e-3f92699e536a.png" width="400em" />

@tpitman 
I can repro it. This problem is regression with `sdk7.0` from `sdk6.0`, everything works as expected on sdk 6.0. So, if possible, you can temporarily unblock yourself by targeting `sdk6.0` image in your `Dockerfile` until actual solution is available. Sorry, if it's not an option for you. I'll post you more updates with my findings soon, looks like docker image issue considering restore/build works outside docker image on M1 machine.

**Comment by erdembayar** [comment]
@tpitman @jstedfast 

After playing for while with `dotnet restore` with docker I randomly hit memory violation error message in log, but still not able to get call stack. 
Finally got quite consistent repro with stack trace with following `Dockerfile`.  Here `dotnet new list` doesn't involve any `nuget` operation, **_so it's not NuGet problem_**.  This one is either `docker image` or `sdk/runtime` problem, you can see `memory violation/corruption error` in stack trace.

```
FROM mcr.microsoft.com/dotnet/sdk:7.0 as base
FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /src
RUN `dotnet new list`
```

1. Here is stack trace `dotnet new list`:
```
DEBU[0000] using default config store "/Users/tester/.docker/buildx" 
[+] Building 4.8s (7/10)                                                                                     
 => [internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 32B                                                                     0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                       0.0s
 => [build 1/6] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:028d360c0f409f13daf8689edfe680dba9d4b651e  0.0s
 => [internal] load build context                                                                       0.0s
 => => transferring context: 2.08kB                                                                     0.0s
 => CACHED [build 2/6] WORKDIR /src                                                                     0.0s
 => ERROR [build 3/6] RUN dotnet new list                                                               4.7s
------                                                                                                       
 > [build 3/6] RUN dotnet new list:                                                                          
#0 4.412 Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.                                                             
#0 4.418    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetStateMachineBox[[System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ReadAsyncInternal>d__159`1<System.Net.Security.AsyncReadWriteAdapter> ByRef, StateMachineBox<Int32> ByRef)
#0 4.418    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AwaitUnsafeOnCompleted[[System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ConfiguredValueTaskAwaiter<Int32> ByRef, <ReadAsyncInternal>d__159`1<System.Net.Security.AsyncReadWriteAdapter> ByRef, StateMachineBox<Int32> ByRef)
#0 4.420    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AwaitUnsafeOnCompleted[[System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ConfiguredValueTaskAwaiter<Int32> ByRef, <ReadAsyncInternal>d__159`1<System.Net.Security.AsyncReadWriteAdapter> ByRef)
#0 4.420    at System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
#0 4.420    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ReadAsyncInternal>d__159`1<System.Net.Security.AsyncReadWriteAdapter> ByRef)
#0 4.420    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Security.SslStream+<ReadAsyncInternal>d__159`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<ReadAsyncInternal>d__159`1<System.Net.Security.AsyncReadWriteAdapter> ByRef)
#0 4.420    at System.Net.Security.SslStream.ReadAsyncInternal[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](System.Memory`1<Byte>, System.Threading.CancellationToken)
#0 4.420    at System.Net.Http.HttpConnection.PrepareForReuse(Boolean)
#0 4.420    at System.Net.Http.HttpConnectionPool.TryGetPooledHttp11Connection(System.Net.Http.HttpRequestMessage, Boolean, System.Net.Http.HttpConnection ByRef, HttpConnectionWaiter`1<System.Net.Http.HttpConnection> ByRef)
#0 4.420    at System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__84.MoveNext()
#0 4.420    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__84, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendWithVersionDetectionAndRetryAsync>d__84 ByRef)
#0 4.420    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__84, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<SendWithVersionDetectionAndRetryAsync>d__84 ByRef)
#0 4.420    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(System.Net.Http.HttpRequestMessage, Boolean, Boolean, System.Threading.CancellationToken)
#0 4.420    at System.Net.Http.HttpConnectionPool.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, Boolean, System.Threading.CancellationToken)
#0 4.420    at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(System.Net.Http.HttpRequestMessage, System.Uri, Boolean, Boolean, Boolean, System.Threading.CancellationToken)
#0 4.420    at System.Net.Http.HttpConnectionPoolManager.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, Boolean, System.Threading.CancellationToken)
#0 4.420    at System.Net.Http.HttpMessageHandlerStage.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
#0 4.421    at System.Net.Http.DiagnosticsHandler.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)
#0 4.421    at System.Net.Http.HttpMessageHandlerStage.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
#0 4.421    at System.Net.Http.SocketsHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
#0 4.421    at Microsoft.ApplicationInsights.Channel.RedirectHttpHandler+<SendAsync>d__4.MoveNext()
#0 4.421    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.ApplicationInsights.Channel.RedirectHttpHandler+<SendAsync>d__4, Microsoft.ApplicationInsights, Version=2.20.0.103, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SendAsync>d__4 ByRef)
#0 4.421    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.ApplicationInsights.Channel.RedirectHttpHandler+<SendAsync>d__4, Microsoft.ApplicationInsights, Version=2.20.0.103, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SendAsync>d__4 ByRef)
#0 4.421    at Microsoft.ApplicationInsights.Channel.RedirectHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
#0 4.421    at System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()
#0 4.421    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<<SendAsync>g__Core|83_0>d ByRef)
#0 4.421    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<<SendAsync>g__Core|83_0>d ByRef)
#0 4.421    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationTokenSource, Boolean, System.Threading.CancellationTokenSource, System.Threading.CancellationToken)
#0 4.421    at System.Net.Http.HttpClient.SendAsync(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationToken)
#0 4.421    at Microsoft.ApplicationInsights.Channel.Transmission+<SendAsync>d__53.MoveNext()
#0 4.421    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.ApplicationInsights.Channel.Transmission+<SendAsync>d__53, Microsoft.ApplicationInsights, Version=2.20.0.103, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SendAsync>d__53 ByRef)
#0 4.421    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.ApplicationInsights.Channel.Transmission+<SendAsync>d__53, Microsoft.ApplicationInsights, Version=2.20.0.103, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SendAsync>d__53 ByRef)
#0 4.421    at Microsoft.ApplicationInsights.Channel.Transmission.SendAsync()
#0 4.421    at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
#0 4.421    at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
#0 4.421    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
#0 4.421    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
#0 4.425 qemu: uncaught target signal 6 (Aborted) - core dumped
#0 4.717 Aborted
------
DEBU[0000] serving grpc connection                      
DEBU[0000] stopping session                              span="load buildkit capabilities"
DEBU[0000] serving grpc connection                      
DEBU[0005] stopping session                             
failed to solve: executor failed running [/bin/sh -c dotnet new list]: exit code: 134
```

2. Different stacktrace for same `dotnet new list`, I got this from inside container. Below messages suggest it's `sdk image` problem, probably Docker is not pulling in correct platform image. I did try `linux/arm64/v8` platform with `docker-composer` but it found, not sure if it by design or not. There are many issues regarding `qemu: uncaught target signal 11 (Segmentation fault)`, they suggest it's either `qemu` or `docker image` problem: https://stackoverflow.com/a/68916382, https://github.com/docker/for-mac/issues/5123

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested.
 
>dotnet new list
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

3. Here is stack trace for `dotnet new console`,

<details><summary>Stack trace details</summary>

```cli
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Newtonsoft.Json.JsonWriter.AutoComplete(Newtonsoft.Json.JsonToken)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(Int64)
   at Newtonsoft.Json.Linq.JValue.WriteTo(Newtonsoft.Json.JsonWriter, Newtonsoft.Json.JsonConverter[])
   at Newtonsoft.Json.Linq.JToken.ToString(Newtonsoft.Json.Formatting, Newtonsoft.Json.JsonConverter[])
   at Microsoft.TemplateEngine.JExtensions.ToJTokenStringDictionary(Newtonsoft.Json.Linq.JToken, System.StringComparer, System.String)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.ConfigModel.GeneratedSymbol..ctor(System.String, Newtonsoft.Json.Linq.JObject)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.ConfigModel.SymbolModelConverter.GetModelForObject(System.String, Newtonsoft.Json.Linq.JObject, Microsoft.Extensions.Logging.ILogger, System.String)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.ConfigModel.TemplateConfigModel..ctor(Newtonsoft.Json.Linq.JObject, Microsoft.Extensions.Logging.ILogger, Microsoft.TemplateEngine.Orchestrator.RunnableProjects.ISimpleConfigModifiers, System.String)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectConfig..ctor(Microsoft.TemplateEngine.Abstractions.IEngineEnvironmentSettings, Microsoft.TemplateEngine.Abstractions.IGenerator, Microsoft.TemplateEngine.Abstractions.Mount.IFile, Microsoft.TemplateEngine.Abstractions.Mount.IFile, Microsoft.TemplateEngine.Abstractions.Mount.IFile, System.String)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.Microsoft.TemplateEngine.Abstractions.IGenerator.GetTemplatesAndLangpacksFromDir(Microsoft.TemplateEngine.Abstractions.Mount.IMountPoint, System.Collections.Generic.IList`1<Microsoft.TemplateEngine.Abstractions.ILocalizationLocator> ByRef)
   at Microsoft.TemplateEngine.Edge.Settings.Scanner.ScanMountPointForTemplatesAndLangpacks(MountPointScanSource)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<>c__DisplayClass22_0.<UpdateTemplateCacheAsync>b__2(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
   at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction`1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
   at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.For(Int32, Int32, System.Action`1<Int32>)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatePackagesAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatePackagesAsync>d__13, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatePackagesAsync>d__13, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatePackagesAsync>d__13, Microsoft.TemplateEngine.Edge, Version=7.0.102.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.UnwrapPromise`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)
   at System.Threading.Tasks.UnwrapPromise`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessInnerTask(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishSlow(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

</details>

4. For sake of completeness here is successful docker build log with `sdk6` on same M1 MAC machine, it's before regression experience.

<details><summary>Succesful run details</summary>

```cli
DEBU[0000] using default config store "/Users/tester/.docker/buildx" 
[+] Building 32.2s (17/18)                                                                                            
 => [internal] load build definition from Dockerfile                                                             0.0s
 => => transferring dockerfile: 838B                                                                             0.0s
 => [internal] load .dockerignore                                                                                0.0s
 => => transferring context: 2B                                                                                  0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0                                               32.1s
 => CACHED [build 1/9] FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:408f1593d25f04e5d1c97115da40760ca032505c97d  0.0s
 => [internal] load build context                                                                                0.0s
 => => transferring context: 5.38kB                                                                              0.0s
 => [build 2/9] RUN dotnet --info                                                                                1.1s
 => [build 3/9] RUN dotnet --version                                                                             1.1s
 => [build 4/9] WORKDIR /src                                                                                     0.0s 
 => [build 5/9] COPY [ericktest/ericktest.csproj, ericktest/]                                                    0.0s 
 => [build 6/9] COPY [ericktest/Program.cs, ericktest/]                                                          0.0s 
 => [build 7/9] COPY . .                                                                                         0.0s 
 => [build 8/9] WORKDIR /src/ericktest                                                                           0.0s
 => [build 9/9] RUN dotnet build "ericktest.csproj" -c Release -o /app/build                                    20.0s
 => [publish 1/1] RUN dotnet publish "ericktest.csproj" -c Release -o /app/publish /p:UseAppHost=false           9.8s
 => CACHED [base 2/2] WORKDIR /app                                                                               0.0s 
 => CACHED [final 1/2] WORKDIR /app                                                                              0.0s 
 => CACHED [final 2/2] COPY --from=publish /app/publish .                                                        0.0s 
 => exporting to image                                                                                           0.0s 
 => => exporting layers                                                                                          0.0s
 => => writing image sha256:aaab5afe6491bc002ca867aef6859a214e2fb83979399576e9b482ad5076a2cd                     0.0s
 => => naming to docker.io/library/ericktest                                                                     0.0s
DEBU[0000] serving grpc connection                      
DEBU[0000] stopping session                              span="load buildkit capabilities"
DEBU[0000] serving grpc connection                      
DEBU[0032] stopping session     
```

</details>

@aortiz-msft 
I believe this is not NuGet problem because same problem repro with `dotnet new list` command inside docker container.

@rainersigwald 
This one could be connected to https://github.com/NuGet/Home/issues/12227, please let me know if you need more details from me.

**Update** 1/26/2023:
Here is my docker repro [erickTest.zip](https://github.com/NuGet/Home/files/10511741/erickTest.zip)
It looks like an issue in the runtime: `System.Net.Security.AsyncReadWriteAdapter`

**Comment by rainersigwald** [comment]
@erdembayar I think this can be closed since it's pretty well tracked by  https://github.com/NuGet/Home/issues/12227, https://github.com/dotnet/runtime/issues/13648, and https://gitlab.com/qemu-project/qemu/-/issues/249.

**Comment by erdembayar** [comment]
Based on @rainersigwald comment we can close it, it's tracked by other issues.
