### ISSUE TITLE
Update-Package A installs missing dependency C for package B

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#1312]
I have a project with package A (my own) and another B (WebApiContrib). The later has a dumb dependency (C) on TaskHelpers.Sources which I don't need.

When I run `Update-Pacakge A -Source MyGet` not only A is updated but also C is installed. Every time.

Log:

```
Attempting to gather dependencies information for multiple packages with respect to project 'My.Api', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'A 0.1.9' from 'packages.config'
Successfully uninstalled 'A 0.1.9' from My.Api
Adding package 'TaskHelpers.Sources.0.1.0' to folder 'D:\Projects\My\packages'
Added package 'TaskHelpers.Sources.0.1.0' to folder 'D:\Projects\My\packages'
Added package 'TaskHelpers.Sources.0.1.0' to 'packages.config'
Successfully installed 'TaskHelpers.Sources 0.1.0' to My.Api
Package 'WebApiContrib.0.9.14' already exists in project 'My.Api'
Successfully installed 'WebApiContrib 0.9.14.0' to My.Api
Package 'A.0.1.11' already exists in folder 'D:\Projects\My\packages'
Added package 'A.0.1.11' to 'packages.config'
Successfully installed 'A 0.1.11' to My.Api
Removing package 'A 0.1.9' from folder 'D:\Projects\My\packages'
Removed package 'A 0.1.9' from folder 'D:\Projects\My\packages'
```

So after each update I have to run `Uninstall-Package TaskHelpers.Sources -Force`.

**Comment by emgarten** [comment]
Try _Update-Package Ab -Source MyGet -IgnoreDependencies_

**Comment by abatishchev** [comment]
But A has no dependencies. Or it has and I need to update it. Why C, a dependency of B, is installed as well?

**Comment by emgarten** [comment]
NuGet finds the full closure of dependencies and installs/updates the project to that state. Removing C puts the project in a bad state since B depends on it. Are you able to leave C installed and just remove the references to C from your csproj file to keep it out of the build?

**Comment by abatishchev** [comment]
I wish NuGet v3 (like v2 did, I believe) would update only what it was told to update and don't care about the reset of project.

The behavior you've described I would expect from `Update-Package`, that's true.

**Comment by abatishchev** [comment]
Interestingly, running `Update-Package A -IgnoreDependencies` produces the following log:

```
Attempting to gather dependencies information for multiple packages with respect to project 'My.Api', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Package 'WebApiContrib.0.9.14' already exists in project 'My.Api'
Successfully installed 'WebApiContrib 0.9.14.0' to My.Api
```

i.e. by some reason tries to re (?) install (?) WebApiContrib.

**Comment by emgarten** [comment]
I wouldn't expect WebApiContrib to get reinstalled there, that look could be a bug.

**Comment by johnataylor** [comment]
Looking at this more closely this is definitely an issue in package update.

Basically when you target a specific package only that package and its dependencies should be involved.

The resolver has to consider the overall project state in order to arrive at a solution. However the logic should be smart enough to realize what are unrelated aspects of the project - in other words if a package that does not have a dependency relationship with target package then we should not include that in the actions: essentially prune actions after resolution according to the dependency graph within the solution.

This is possibly a problem in other scenarios too - for example install may have similar behavior.

**Comment by johnataylor** [comment]
Just confirmed this is also a bug in install. The gather/resolve/action pipeline always attempts to "repair" the whole solution even when we really don't want it to be doing that.

**Comment by johnataylor** [comment]
Fixes checked in and functional test passing, and this should fix the issue in both Install and Update.
Thanks @abatishchev for opening the bug much appreciated.

**Comment by remids** [comment]
Fell across this bug March 30th 2016, while researching an issue with my new, patched just-updated VS 2015 install. I'm still seeing this behavior with Install-Package.

**Comment by abatishchev** [comment]
Can we have the issue reopened?
