### ISSUE TITLE
Restore packages in 9.0.200 takes a very long time

### ISSUE THREAD

**Issue by mnmr** [NuGet/Home#14147]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.200

### Worked before?

9.0.103

### Impact

Other

### Repro Steps & Context

I'm having issues with the new package restore logic, which is seemingly taking forever (aborted after 3 minutes).

I'm restoring packages using `dotnet restore -f -v d <sln>` but don't see anything useful in the console before the command is cancelled. It lists increasingly long restore times, with some projects completing in ms and others going on for minutes.

We're using centralized package version management and all versions are explicit (no wildcards). There's ballpark 150 projects in the solution.

Adding `<RestoreUseLegacyDependencyResolver>true</RestoreUseLegacyDependencyResolver>` to `Directory.Build.props` is a workaround. For reference, the old way of restoring packages completes in ~4s.

### Verbose Logs

```shell

```

**Comment by jeffkl** [comment]
@mnmr sorry you're experiencing this issue.  Fortunately, we've already fixed in and are in the process of releasing it.  Its currently fixed in Visual Studio 17.13.1 and NuGet 6.13.2 and we're working on getting .NET 9.0.2xx updated.  For now, as you've pointed out, setting `RestoreUseLegacyDependencyResolver` is a workaround.

**Comment by p10tyr** [comment]
Can confirm still an issue with VS 17.13.2 and SDK 9.0.200 
(for context a 10-second restore now takes 16minutes for us)

**Comment by jeffkl** [comment]
The fix for this will be in the next release of .NET SDK 9.0.200 which will be available on April 8th

**Comment by hiresm** [comment]
SDK 9.0.203 looks good

**Comment by martinsuchan** [comment]
Is there a Nuget.Commandline package with this fix? It's not listed in release notes yet:
https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.13

**Comment by nkolev92** [comment]
Closing as 9.0.203 is now out. 

@martinsuchan, yes 6.13.2 was published with VS so about ~2mo ago, the release notes are now updated.

**Comment by aaronsuydam** [comment]
Hey y'all, I'm using 9.0.203 on macOS and when I restore my project on osx-arm64 (the native arch so I don't specify) it takes < 1sec, but when I restore passing a "-r osx-x64" it takes into the multiple minutes. Just wanted to ask about that since this seems like the place to do that.
