### ISSUE TITLE
Fix NuGet.Config casing

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1427]
nuget.exe looks for NuGet.config instead of NuGet.Config. This breaks on linux when using mono and is a regression from 2.8.6.

**Comment by pranavkm** [comment]
Related: https://github.com/aspnet/dnx/issues/2747

On Linux, DNX looks for multiple casings of nuget.config and picks the first one that matches:
1. `nuget.config`
2. `NuGet.config` // v3 behavior
3. `NuGet.Config` // v2 behavior

**Comment by analogrelay** [comment]
DNX isn't going to be able to use NuGet's configuration code until we get something done to fix this. Is there an ETA on it? #1847 is blocked on it because we need to switch to NuGet.Configuration to fix it and we can't because Linux behavior is broken :(.

We're already punting the bug out to RC1, so we've got a few weeks, but I wanted to raise the profile of this bug a little so it can be fixed in time.

/cc @muratg @davidfowl @emgarten @yishaigalatzer

**Comment by muratg** [comment]
cc @Eilon

**Comment by emgarten** [comment]
I've updated the constant to the original NuGet.Config casing.
NuGet/NuGet3@39c7f5173f5acc5999fc7aaea436df449e72cce9

**Comment by pranavkm** [comment]
Why not use `nuget.config`? `NuGet.Config` is incredibly easy to mess up on a case sensitive platform.

**Comment by yishaigalatzer** [comment]
Because that was how it always worked. Changing it is a breaking change.

**Comment by pranavkm** [comment]
The current change will break DNX builds - https://github.com/aspnet/dnx/commit/8e31f4f61e8960544e0f9e63c152e00725e187e3 (NuGet.Config → NuGet.config)

If the intent is to not break, then just supporting multiple casings would be the appropriate fix.

**Comment by yishaigalatzer** [comment]
The ask came from your team, to revert back to what it always was.

CC @davidfowl

**Comment by zhili1208** [comment]
@pranavkm please verify this is fixed.

**Comment by akoeplinger** [comment]
@yishaigalatzer what's the verdict on this one? did you standardize on `nuget.config` as the default (with fallback for the other casings) like in DNX?

I still see other casings in the codebase: https://github.com/NuGet/NuGet3/blob/fdf204fa74ab3a336eb0ce11ac4eb0e87309bb0d/src/NuGet.Configuration/Settings/Settings.cs#L24

**Comment by yishaigalatzer** [comment]
That is the standard (with that casing), but we allow for all lowercase. Obviously it doesn’t matter on windows, and does a very small “performance damage” on case sensitive file systems.

The case is as such, because that is what it was in Nuget 2.8.X so minimal breaking changes.

**Comment by akoeplinger** [comment]
@yishaigalatzer DNX goes a different route though, they are looking for `nuget.config` by default on all platforms with the fallback for the other casings on !Windows and standardizing on nuget.config across their repos. That is the way to go IMHO, so would be great if NuGet proper could follow this (there are no breaking changes as well with this approach).

**Comment by yishaigalatzer** [comment]
Well, NuGet is RTM, DNU is not. So we need to be a bit careful with this.

We are going to merge the two eventually into one codebase, when that happens we can make more changes.

Right now there are no functional differences, so I don’t know that we need to spend more time on this.

**Comment by akoeplinger** [comment]
Sure, just wanted to make sure that we'll eventually move to a standardized `nuget.config` everywhere and support the other casings just as a fallback.

**Comment by yishaigalatzer** [comment]
Yup
