### ISSUE TITLE
Package restore intermittently fails with "Unable to find version 'x' of package 'y'"

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1448]
One example: 
https://ci.appveyor.com/project/AArnott/nerdbank-gitversioning/build/1.0.5

I see this perhaps 5-10% of the time when I do a nuget restore -- simply rerunning the command resolve the issue. But it is distressing to automation that will frequently fail because of this. Why is nuget failing to find the package on nuget.org?

**Comment by AArnott** [comment]
never mind. apparently this particular package version comes from myget.org. So I'll take it up with them.

**Comment by AArnott** [comment]
Nah, reopening because I see this for packages coming from nuget.org as well. For example a nuget restore on another computer just failed after installing several packages but failing for others:

> nuget restore src
> Restoring NuGet package MSBuildTasks.1.4.0.88.
> Restoring NuGet package LibGit2Sharp.0.21.0.176.
> Restoring NuGet package Nerdbank.GitVersioning.1.1.2-rc.
> Restoring NuGet package NuProj.0.10.4-beta-gf7fc34e7d8.
> Restoring NuGet package Validation.2.0.6.15003.
> WARNING: Unable to find version '0.21.0.176' of package 'LibGit2Sharp'.
> Restoring NuGet package xunit.2.0.0.
> WARNING: Unable to find version '2.0.6.15003' of package 'Validation'.
> Restoring NuGet package xunit.abstractions.2.0.0.
> WARNING: Unable to find version '1.4.0.88' of package 'MSBuildTasks'.
> Restoring NuGet package xunit.assert.2.0.0.
> WARNING: Unable to find version '0.10.4-beta-gf7fc34e7d8' of package 'NuProj'.
> Restoring NuGet package xunit.core.2.0.0.
> Adding package 'xunit.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'Nerdbank.GitVersioning.1.1.2-rc' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Restoring NuGet package xunit.extensibility.core.2.0.0.
> Restoring NuGet package xunit.runner.visualstudio.2.0.1.
> Added package 'Nerdbank.GitVersioning.1.1.2-rc' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'xunit.abstractions.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.abstractions.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'xunit.core.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.core.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'xunit.assert.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.assert.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'xunit.extensibility.core.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.extensibility.core.2.0.0' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Adding package 'xunit.runner.visualstudio.2.0.1' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Added package 'xunit.runner.visualstudio.2.0.1' to folder 'C:\git\Nerdbank.GitVersioning\packages'
> Unable to find version '0.21.0.176' of package 'LibGit2Sharp'.
> Unable to find version '2.0.6.15003' of package 'Validation'.
> Unable to find version '1.4.0.88' of package 'MSBuildTasks'.
> Unable to find version '0.10.4-beta-gf7fc34e7d8' of package 'NuProj'.
> Exception of type 'NuGet.CommandLineException' was thrown.

**Comment by emgarten** [comment]
When you see it fail with nuget.org are you using the api.nuget.org/v3/index.json or nuget.org/api/v2/ as your source?

**Comment by emgarten** [comment]
I am seeing this also now when restoring your repo using nuget.org v2. With v3 it works fine. The correct results are coming back from the OData feed, but then it seems to fail during the download.

**Comment by AArnott** [comment]
I'm glad it's repro'ing for you. I hope it's something that can be fixed.

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/NuGet3/commit/0669fceea385affb4d9f85721e3abeb9ea2f84ac

**Comment by deepakaravindr** [comment]
This was verified by Justin

**Comment by AArnott** [comment]
I'm still seeing failures. Was this a server-side fix or a client one?

> D:\Build.vnext\Agent2\agent\worker\tools\NuGet.exe restore "f:\vnext2\70d66e57\VSIDEProj.Validation\src\Microsoft.VisualStudio.Validation.sln" -NonInteractive
> Installing 'NuProj 0.10.0-beta-gd6d4e1ff23'.
> Successfully installed 'NuProj 0.10.0-beta-gd6d4e1ff23'.
> Installing 'xunit 2.0.0'.
> Successfully installed 'xunit 2.0.0'.
> Installing 'xunit.abstractions 2.0.0'.
> Successfully installed 'xunit.abstractions 2.0.0'.
> Installing 'xunit.assert 2.0.0'.
> Successfully installed 'xunit.assert 2.0.0'.
> Installing 'xunit.core 2.0.0'.
> Successfully installed 'xunit.core 2.0.0'.
> Installing 'xunit.extensibility.core 2.0.0'.
> Successfully installed 'xunit.extensibility.core 2.0.0'.
> Installing 'Moq 4.2.1507.0118'.
> Successfully installed 'Moq 4.2.1507.0118'.
> Installing 'xunit.runner.visualstudio 2.0.0'.
> Successfully installed 'xunit.runner.visualstudio 2.0.0'.
> Installing 'MicroBuild.VisualStudio 1.0.83-rc-g72bc07812b'.
> Successfully installed 'MicroBuild.VisualStudio 1.0.83-rc-g72bc07812b'.
> Installing 'MicroBuild.NonShipping 1.0.83-rc-g72bc07812b'.
> Successfully installed 'MicroBuild.NonShipping 1.0.83-rc-g72bc07812b'.
> Installing 'MicroBuild 1.0.83-rc-g72bc07812b'.
> Successfully installed 'MicroBuild 1.0.83-rc-g72bc07812b'.
> Unable to find version '1.1.52-rc' of package 'Nerdbank.GitVersioning'.
> Unable to find version '1.0.0-beta014' of package 'StyleCop.Analyzers'.
> Unexpected exit code 1 returned from tool NuGet.exe

**Comment by AArnott** [comment]
I'm also seeing this in package restore failures from network shares:

> 2015-10-21T01:24:55.2076575Z D:\Build.vnext\Agent1\agent\worker\tools\NuGet.exe restore "f:\vnext1\70d66e57\VSIDEProj.Validation\src\Microsoft.VisualStudio.Validation.sln" -NonInteractive
> 2015-10-21T01:24:55.6295375Z Installing 'NuProj 0.10.0-beta-gd6d4e1ff23'.
> 2015-10-21T01:24:55.7858489Z Successfully installed 'NuProj 0.10.0-beta-gd6d4e1ff23'.
> 2015-10-21T01:24:55.8170404Z Installing 'StyleCop.Analyzers 1.0.0-beta014'.
> 2015-10-21T01:24:55.8482908Z Installing 'xunit 2.0.0'.
> 2015-10-21T01:24:55.8482908Z Successfully installed 'xunit 2.0.0'.
> 2015-10-21T01:24:55.8639158Z Installing 'xunit.abstractions 2.0.0'.
> 2015-10-21T01:24:55.8795404Z Successfully installed 'xunit.abstractions 2.0.0'.
> 2015-10-21T01:24:55.8951669Z Installing 'xunit.assert 2.0.0'.
> 2015-10-21T01:24:55.9107920Z Successfully installed 'StyleCop.Analyzers 1.0.0-beta014'.
> 2015-10-21T01:24:55.9264174Z Successfully installed 'xunit.assert 2.0.0'.
> 2015-10-21T01:24:55.9264174Z Installing 'xunit.core 2.0.0'.
> 2015-10-21T01:24:55.9576675Z Installing 'xunit.extensibility.core 2.0.0'.
> 2015-10-21T01:24:55.9733273Z Successfully installed 'xunit.extensibility.core 2.0.0'.
> 2015-10-21T01:24:56.0045437Z Installing 'Moq 4.2.1507.0118'.
> 2015-10-21T01:24:56.0358610Z Successfully installed 'xunit.core 2.0.0'.
> 2015-10-21T01:24:56.0514177Z Installing 'xunit.runner.visualstudio 2.0.0'.
> 2015-10-21T01:24:56.0826675Z Successfully installed 'Moq 4.2.1507.0118'.
> 2015-10-21T01:24:56.0982947Z Successfully installed 'xunit.runner.visualstudio 2.0.0'.
> 2015-10-21T01:24:58.0202003Z Installing 'Nerdbank.GitVersioning 1.1.52-rc'.
> 2015-10-21T01:24:58.3015146Z Successfully installed 'Nerdbank.GitVersioning 1.1.52-rc'.
> 2015-10-21T01:25:08.4112897Z ##[error]Unable to find version '1.0.83-rc-g72bc07812b' of package 'MicroBuild'.
> 2015-10-21T01:25:08.4112897Z ##[error]Unable to find version '1.0.83-rc-g72bc07812b' of package 'MicroBuild.VisualStudio'.
> 2015-10-21T01:25:08.4265779Z ##[error]Unable to find version '1.0.83-rc-g72bc07812b' of package 'MicroBuild.NonShipping'.
> 2015-10-21T01:25:08.4890761Z ##[error]Unexpected exit code 1 returned from tool NuGet.exe

**Comment by emgarten** [comment]
It would be a different cause if you are seeing this happen for network shares, is it also intermittent?

**Comment by AArnott** [comment]
Actually the network share repro appeared intermittent but was actually attributable to a particular build agent (not always used) that had an older nuget.exe. The network share issue appears fixed now that I've updated that build agent. 

But the first comment I left today (regarding the Nerdbank.GitVersioning not being found) is of course from nuget.org. And it seemed to happen more frequently after I removed the v2 package source from nuget.config. Prior to that change, we had both v2 and v3 package sources for nuget.org listed. After the change only v3 was listed in nuget.config. This _may_ have also been correlated to that older build agent, I am not sure.

**Comment by emgarten** [comment]
The fix for this issue was made to the client for V2 online downloads. There were some v3 fixes, but I wouldn't expect them to cause the failures you are seeing here. 

I'm going to close this issue, if you are able to get a better repro for the v3 issue please open another bug. So far I haven't seen any issues there.

**Comment by luisrudge** [comment]
I'm still seeing this issue on appveyor when I add a private feed from myget. 

```
nuget restore %project_name% -verbosity detailed -verbosity detailed

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Restoring NuGet package Microsoft.Azure.KeyVault.Core.1.0.0.
Restoring NuGet package Microsoft.Data.Edm.5.6.4.
Restoring NuGet package Microsoft.Data.OData.5.6.4.
Restoring NuGet package Microsoft.Data.Services.Client.5.6.4.
Restoring NuGet package Microsoft.Orleans.Core.1.0.10.
Restoring NuGet package Microsoft.Orleans.CounterControl.1.0.10.
WARNING: Unable to find version '5.6.4' of package 'Microsoft.Data.Edm'.
Restoring NuGet package Microsoft.Orleans.OrleansAzureUtils.1.0.10.
WARNING: Unable to find version '5.6.4' of package 'Microsoft.Data.OData'.
Restoring NuGet package Microsoft.Orleans.OrleansHost.1.0.10.
WARNING: Unable to find version '1.0.10' of package 'Microsoft.Orleans.Core'.
Restoring NuGet package Microsoft.Orleans.OrleansProviders.1.0.10.
WARNING: Unable to find version '5.6.4' of package 'Microsoft.Data.Services.Client'.
Restoring NuGet package Microsoft.Orleans.OrleansRuntime.1.0.10.
Adding package 'Microsoft.Orleans.CounterControl.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Azure.KeyVault.Core.1.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.CounterControl.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.Orleans.Server.1.0.10.
Added package 'Microsoft.Azure.KeyVault.Core.1.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.WindowsAzure.ConfigurationManager.3.1.0.
Restoring NuGet package NEventStore.5.2.0.
Adding package 'Microsoft.Orleans.OrleansAzureUtils.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.OrleansAzureUtils.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Newtonsoft.Json.7.0.1.
Adding package 'Microsoft.Orleans.OrleansProviders.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.OrleansProviders.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Orleans.StorageProvider.Blob.1.0.4.
Adding package 'Microsoft.Orleans.Server.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.Server.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package System.Spatial.5.6.4.
Adding package 'Microsoft.Orleans.OrleansHost.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.OrleansHost.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Unofficial.Microsoft.WindowsAzure.ServiceRuntime.2.7.0.
Adding package 'Microsoft.WindowsAzure.ConfigurationManager.3.1.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.WindowsAzure.ConfigurationManager.3.1.0' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package WindowsAzure.ServiceBus.3.0.4.
Adding package 'Microsoft.Orleans.OrleansRuntime.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.OrleansRuntime.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package WindowsAzure.Storage.6.0.0.
Adding package 'Newtonsoft.Json.7.0.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Newtonsoft.Json.7.0.1' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.Orleans.Templates.Interfaces.1.0.10.
Adding package 'Orleans.StorageProvider.Blob.1.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Orleans.StorageProvider.Blob.1.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package AutoMapper.4.0.4.
Adding package 'NEventStore.5.2.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'System.Spatial.5.6.4' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'System.Spatial.5.6.4' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.Orleans.Templates.Grains.1.0.10.
Restoring NuGet package Newtonsoft.Json.6.0.8.
Restoring NuGet package BCrypt-Official.0.1.109.
Restoring NuGet package FakeItEasy.2.0.0-beta009.
Restoring NuGet package FluentValidation.5.6.2.
Restoring NuGet package Microsoft.AspNet.Cors.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Client.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Core.5.2.3.
Restoring NuGet package Microsoft.AspNet.WebApi.Cors.5.2.3.
Restoring NuGet package Microsoft.Azure.DocumentDB.1.5.0.
Added package 'NEventStore.5.2.0' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NBuilder.3.0.1.1.
Adding package 'WindowsAzure.ServiceBus.3.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'WindowsAzure.ServiceBus.3.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NLog.4.1.2.
Adding package 'WindowsAzure.Storage.6.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Unofficial.Microsoft.WindowsAzure.ServiceRuntime.2.7.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'AutoMapper.4.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Orleans.Templates.Interfaces.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.AspNet.WebApi.Cors.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'FakeItEasy.2.0.0-beta009' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Orleans.Templates.Grains.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Newtonsoft.Json.6.0.8' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'BCrypt-Official.0.1.109' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Azure.DocumentDB.1.5.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.AspNet.WebApi.Client.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'BCrypt-Official.0.1.109' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NLog.Config.4.1.2.
Adding package 'Microsoft.AspNet.Cors.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.AspNet.Cors.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NLog.Schema.4.0.1.
Adding package 'NLog.Config.4.1.2' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NLog.Config.4.1.2' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NUnit.2.6.4.
Adding package 'NLog.Schema.4.0.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NLog.Schema.4.0.1' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Rx-Core.2.2.5.
Added package 'Microsoft.Orleans.Templates.Interfaces.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.AspNet.WebApi.Core.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.AspNet.WebApi.Core.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Rx-Linq.2.2.5.
Restoring NuGet package Rx-Interfaces.2.2.5.
Adding package 'NUnit.2.6.4' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'NBuilder.3.0.1.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NBuilder.3.0.1.1' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Rx-Main.2.2.5.
Added package 'Microsoft.Orleans.Templates.Grains.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Rx-PlatformServices.2.2.5.
Added package 'Microsoft.Azure.DocumentDB.1.5.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'NLog.4.1.2' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package WindowsAzure.ServiceBus.3.0.6.
Added package 'Unofficial.Microsoft.WindowsAzure.ServiceRuntime.2.7.0' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.WindowsAzure.ConfigurationManager.3.0.0.
Added package 'Microsoft.AspNet.WebApi.Client.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.Azure.ServiceBus.EventProcessorHost.2.0.6.
Adding package 'FluentValidation.5.6.2' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Rx-Core.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Rx-Interfaces.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Rx-PlatformServices.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Rx-Main.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'WindowsAzure.ServiceBus.3.0.6' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'WindowsAzure.ServiceBus.3.0.6' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package Microsoft.Orleans.Client.1.0.10.
Added package 'Rx-PlatformServices.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NLog.Targets.Sentry.1.2.0.
Adding package 'Rx-Linq.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.AspNet.WebApi.Cors.5.2.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NLog.4.1.2' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package SharpRaven.1.4.3.
Added package 'Rx-Interfaces.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'FakeItEasy.2.0.0-beta009' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package NodaMoney.0.4.0.
Added package 'FluentValidation.5.6.2' to folder 'C:\projects\cis-v2\src\.\packages'
Restoring NuGet package EnterpriseLibrary.TransientFaultHandling.Data.6.0.1304.1.
Restoring NuGet package NodaTime.1.3.1.
Restoring NuGet package EnterpriseLibrary.TransientFaultHandling.6.0.1304.
Adding package 'Microsoft.WindowsAzure.ConfigurationManager.3.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Orleans.Client.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'NLog.Targets.Sentry.1.2.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NLog.Targets.Sentry.1.2.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'Microsoft.Azure.ServiceBus.EventProcessorHost.2.0.6' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Azure.ServiceBus.EventProcessorHost.2.0.6' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'AutoMapper.4.0.4' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Rx-Main.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'NodaMoney.0.4.0' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'SharpRaven.1.4.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'SharpRaven.1.4.3' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Rx-Core.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'EnterpriseLibrary.TransientFaultHandling.Data.6.0.1304.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'EnterpriseLibrary.TransientFaultHandling.Data.6.0.1304.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Newtonsoft.Json.6.0.8' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NodaMoney.0.4.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.WindowsAzure.ConfigurationManager.3.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'WindowsAzure.Storage.6.0.0' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Microsoft.Orleans.Client.1.0.10' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NUnit.2.6.4' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'Rx-Linq.2.2.5' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'EnterpriseLibrary.TransientFaultHandling.6.0.1304' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'EnterpriseLibrary.TransientFaultHandling.6.0.1304' to folder 'C:\projects\cis-v2\src\.\packages'
Adding package 'NodaTime.1.3.1' to folder 'C:\projects\cis-v2\src\.\packages'
Added package 'NodaTime.1.3.1' to folder 'C:\projects\cis-v2\src\.\packages'
Unable to find version '5.6.4' of package 'Microsoft.Data.Edm'.
Unable to find version '5.6.4' of package 'Microsoft.Data.OData'.
Unable to find version '1.0.10' of package 'Microsoft.Orleans.Core'.
Unable to find version '5.6.4' of package 'Microsoft.Data.Services.Client'.
NuGet.CommandLineException: Exception of type 'NuGet.CommandLineException' was thrown.
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__18.MoveNext()
Command exited with code 1
```

**Comment by emgarten** [comment]
@luisrudge what version of nuget.exe?

**Comment by luisrudge** [comment]
3.20. I had to point the feed to v3 to make it work:

```
init:
  - nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
  - nuget sources add -Name MyPrivateFeed -Source https://www.myget.org/F/mycompany/auth/{guid}/api/v2
```

**Comment by emgarten** [comment]
This is fixed in 3.2.1-rc 
https://dist.nuget.org/index.html

**Comment by luisrudge** [comment]
Ah, ok. Thanks!

**Comment by ghost** [comment]
Is there any chance for this fix to be retrofitted into version 2.8? It seems versions 3+ are not supported in Visual Studio 2013.

**Comment by alainbryden** [comment]
Still seeing this issue in 3.3.0:

```
13:16:48 Checking for updates from https://www.nuget.org/api/v2/.
13:16:49 Currently running NuGet.exe 3.3.0.
13:16:49 NuGet.exe is up to date.
13:16:49 MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
13:16:49 Feeds used:
13:16:49   C:\Users\jenkins\AppData\Local\NuGet\Cache
13:16:49   C:\Users\jenkins\.nuget\packages\
13:16:49   https://api.nuget.org/v3/index.json
13:16:49 
13:16:49 Restoring NuGet package Newtonsoft.Json.8.0.2.
13:16:49 Restoring NuGet package RestSharpSigned.105.2.3.
13:16:49 Adding package 'RestSharpSigned.105.2.3' to folder 'C:\jenkins-test\workspace\are_csharp_test_apiv0\packages'
13:16:49 Added package 'RestSharpSigned.105.2.3' to folder 'C:\jenkins-test\workspace\are_csharp_test_apiv0\packages'
13:18:29 WARNING: Unable to find version '8.0.2' of package 'Newtonsoft.Json'.
13:18:29 Unable to find version '8.0.2' of package 'Newtonsoft.Json'.
```

**Comment by rovinbhandari** [comment]
I hit this issue very recently with trying to install/restore nuget packages created internally in my company; the source was specified correctly and the package existed there but a similar error was thrown. Leaving this comment here for other people who might have similar issues.

#### With NuGet.exe version 2.8.60717.93

```
Source: file://\\server\packages
Unable to find version '2.6.4.0' of package 'Company.CustomPackage'
```

#### With NuGet.exe version 3.3.0.212

```
Feeds used:
    file://\\server\packages
Restoring NuGet package Company.CustomPackage.2.6.4.
WARNING: Unable to find version '2.6.4' of package 'Company.CustomPackage'.
```

The problem wasn't that the package didn't exist in the source provided as a command line argument, where I was looking based on the error/warning I got. In fact, there was a mismatch between the versions in the filename (Company.CustomPackage.2.6.4.0.nupkg) and the version specified in the nuspec inside the package (it was 2.6.3.0).

I'm not sure if this scenario qualifies as something which should be fixed (as in, properly reported) in the nuget client; please consider fixing it!

**Comment by RichardSilveira** [comment]
To solve this issue, use the command "dotnet restore" from CMD using DOTNet CLI.
download in http://dotnet.github.io/getting-started/
From visual studio does not work =\

**Comment by heatmonkey** [comment]
I don't think this is fixed and I am not using vNext. I am on VS2015 with a private nuget feed hosted on a teamcity server behind a corporate firewall. All things nuget worked fine until I added the TeamCity feed. . 

https://api.nuget.org/v3/index.json
Install-Package : Exception 'System.AggregateException' thrown when trying to add source 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are 
available.
At line:1 char:1
- Install-Package <<packagename>>
- ~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by kentcb** [comment]
Also don't think this is fixed. I'm using a 3.3.0 client. Running a build script on my machine works perfectly, even after purging all packages. But on the CI server (which is in an entirely different physical state to me) I get:

```
[14:52:24][Step 1/1] Feeds used:
[14:52:24][Step 1/1]   /Users/ci/.local/share/NuGet/Cache
[14:52:24][Step 1/1]   /Users/ci/.nuget/packages/
[14:52:24][Step 1/1]   https://api.nuget.org/v3/index.json
...
[14:52:28][Step 1/1] Restoring NuGet package Rx-PlatformServices.2.2.5.
[14:52:28][Step 1/1] Adding package 'Rx-PlatformServices.2.2.5' to folder '/Users/ci/buildAgent/work/d4dc54896edebb64/Src/packages'
[14:52:28][Step 1/1] Added package 'Rx-PlatformServices.2.2.5' to folder '/Users/ci/buildAgent/work/d4dc54896edebb64/Src/packages'
[14:52:28][Step 1/1] Restoring NuGet package Splat.1.6.2.
[14:52:28][Step 1/1] Adding package 'Splat.1.6.2' to folder '/Users/ci/buildAgent/work/d4dc54896edebb64/Src/packages'
[14:52:28][Step 1/1] Added package 'Splat.1.6.2' to folder '/Users/ci/buildAgent/work/d4dc54896edebb64/Src/packages'
[14:52:28][Step 1/1] Restoring NuGet package SQLitePCL.raw_basic.0.8.6.
[14:52:29][Step 1/1] WARNING: Unable to find version '0.8.6' of package 'SQLitePCL.raw_basic'.
[14:52:29][Step 1/1] Restoring NuGet package System.Collections.Immutable.1.1.37.
[14:52:30][Step 1/1] WARNING: Unable to find version '1.1.37' of package 'System.Collections.Immutable'.
```

**Comment by xavierdecoster** [comment]
Could you please try the 3.4.2 client from http://dist.nuget.org/index.html and see if it fixes it?

**Comment by kentcb** [comment]
@xavierdecoster It seems like it probably does fix it:

```
[17:35:49][Step 1/1] Error downloading 'SQLitePCL.raw_basic.0.8.6' from 'https://api.nuget.org/v3-flatcontainer/sqlitepcl.raw_basic/0.8.6/sqlitepcl.raw_basic.0.8.6.nupkg'.
[17:35:49][Step 1/1] Access to the path "/Users/ci/.nuget/packages/SQLitePCL.raw_basic" is denied.
[17:35:49][Step 1/1] WARNING: Unable to find version '0.8.6' of package 'SQLitePCL.raw_basic'.
[17:35:49][Step 1/1]   /Users/ci/.local/share/NuGet/Cache: Package 'SQLitePCL.raw_basic.0.8.6' is not found on source '/Users/ci/.local/share/NuGet/Cache'.
[17:35:49][Step 1/1]   /Users/ci/.nuget/packages/: Package 'SQLitePCL.raw_basic.0.8.6' is not found on source '/Users/ci/.nuget/packages/'.
[17:35:49][Step 1/1]   https://api.nuget.org/v3/index.json: Error downloading 'SQLitePCL.raw_basic.0.8.6' from 'https://api.nuget.org/v3-flatcontainer/sqlitepcl.raw_basic/0.8.6/sqlitepcl.raw_basic.0.8.6.nupkg'.
[17:35:49][Step 1/1]   Access to the path "/Users/ci/.nuget/packages/SQLitePCL.raw_basic" is denied.
```

The error at the end is probably an ownership problem on the directory. However, I won't be able to validate this until Monday because remote access to the CI server isn't working and no one is in the office. I will get back to you.

Thanks!

**Comment by kentcb** [comment]
Yes, it worked once I fixed the ownership of the `.nuget` directory.

**Comment by mahara** [comment]
Any reason why https://www.nuget.org/nuget.exe or https://api.nuget.org/downloads/nuget.exe still pointing to version 2.8.6 instead of the latest 3.4.x as published in http://dist.nuget.org/index.html?
In my case 2.8.6 causing this issue because it's what available from https://www.nuget.org/nuget.exe.

**Comment by harikmenon** [comment]
The majority of our customers are on 2.8.6 at this time and depend on a stable download. We will update this in the near future. In the meantime if you want to stay on the latest for nuget.exe I would recommend that you look at https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

**Comment by OsirisTerje** [comment]
I don't think this is fixed, we're running 3.4.3.855 and we still see it, on packages coming from nuget org., on some build servers, and it is intermittent. 

![image](https://cloud.githubusercontent.com/assets/203432/16492098/d5a4d06c-3ee0-11e6-8bea-cd931595db84.png)

Even if this is caused by something else than nuget, nuget should report properly what is causing it to fail.  Also, it says it is restoring, but it dont find the files, and what we see is that the packages folder is empty.

**Comment by timotei** [comment]
@OsirisTerje NuGet 3.4+ has a nicer Verbose output. You should enable it as it will tell you each feed it tries to search the package into.

**Comment by OsirisTerje** [comment]
@timotei Sounds good, but this is TFS XAML builds, I am not sure if I can easily modify what the nuget verbosity is set to there without murking arund with the xaml.  Thanks for the tip though.  I assume you mean  "-verbosity detailed" ?

**Comment by timotei** [comment]
Not sure I see the link between the NuGet params and XAML, they should be separate.

Yes, verbosity detailed is what you want.

**Comment by dilare** [comment]
# dsdfghj,# [ryfhghmn](hm

hm

@harshgMSFT ertuyg

)

>

**Comment by GrimaceOfDespair** [comment]
I totally agree on the remark about making nuget output more debug friendly. I suffered from a permission issue that manifested itself with the dreaded `Unable to find version`.

In hindsight, all symptoms should have pointed me in the right direction, but the actual message leaves the regular user baffled. If NuGet arrives at the stage where it actually queries a file share, I guess it would encounter an actual file permission issue, rather that a "not found", and even if it doesn't, it could tell the user that "the user might not have enough permissions"

**Comment by dotnetnate** [comment]
This happens quite regularly on the VSTS instance for one of our customers. The packages are sporadic - no rhyme or reason other than it chews up build minutes like nobody's business when we have to requeue builds due to this issue.

**Comment by txdv** [comment]
```bash
bentkus@dainty:~/Projects/csharp/monodevelop/main$ mono .nuget/NuGet.exe restore -verbosity detailed
Restoring NuGet packages for solution /home/bentkus/Projects/csharp/monodevelop/main/Main.sln.
Restoring NuGet packages listed in file /home/bentkus/Projects/csharp/monodevelop/main/.nuget/packages.config.
GET https://api.nuget.org/v3/index.json/Packages(Id='NuGet.CommandLine',Version='2.8.2')
GET https://api.nuget.org/v3/index.json/Packages(Id='NuGet.CommandLine',Version='2.8.2.0')
System.InvalidOperationException: Unable to find version '2.8.2' of package 'NuGet.CommandLine'.
  at NuGet.PackageHelper.ResolvePackage (NuGet.IPackageRepository repository, System.String packageId, NuGet.SemanticVersion version) [0x00071] in <3c93a88a29d041668b07b864a37db626>:0 
  at NuGet.Commands.RestoreCommand.RestorePackage (NuGet.IFileSystem packagesFolderFileSystem, System.String packageId, NuGet.SemanticVersion version, System.Boolean packageRestoreConsent, System.Collections.Concurrent.ConcurrentQueue`1[T] satellitePackages) [0x000ea] in <3c93a88a29d041668b07b864a37db626>:0 
  at NuGet.Commands.RestoreCommand+<>c__DisplayClass5+<>c__DisplayClass7.<ExecuteInParallel>b__2 () [0x0002c] in <3c93a88a29d041668b07b864a37db626>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Execute () [0x00016] in <8f2c484307284b51944a1a13a14c0266>:0
```

The contents of my file:
```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NuGet.CommandLine" version="2.8.2" />
  <package id="NUnit.Runners" version="2.6.4" />
</packages>
```

The response is:

```
{
  "version": "3.0.0-beta.1",
  "resources": [
    {
      "@id": "https://api-v2v3search-0.nuget.org/query",
      "@type": "SearchQueryService",
      "comment": "Query endpoint of NuGet Search service (primary)"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/query",
      "@type": "SearchQueryService",
      "comment": "Query endpoint of NuGet Search service (secondary)"
    },
    {
      "@id": "https://api-v2v3search-0.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService",
      "comment": "Autocomplete endpoint of NuGet Search service (primary)"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService",
      "comment": "Autocomplete endpoint of NuGet Search service (secondary)"
    },
    {
      "@id": "https://api-v2v3search-0.nuget.org/",
      "@type": "SearchGalleryQueryService/3.0.0-rc",
      "comment": "Azure Website based Search Service used by Gallery (primary)"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/",
      "@type": "SearchGalleryQueryService/3.0.0-rc",
      "comment": "Azure Website based Search Service used by Gallery (secondary)"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1/",
      "@type": "RegistrationsBaseUrl",
      "comment": "Base URL of Azure storage where NuGet package registration info is stored"
    },
    {
      "@id": "https://api.nuget.org/v3-flatcontainer/",
      "@type": "PackageBaseAddress/3.0.0",
      "comment": "Base URL of Azure storage where NuGet package registration info for NET Core is stored, in the format https://api.nuget.org/v3-flatcontainer/{id-lower}/{version-lower}.{version-lower}.nupkg"
    },
    {
      "@id": "https://www.nuget.org/api/v2",
      "@type": "LegacyGallery"
    },
    {
      "@id": "https://www.nuget.org/api/v2",
      "@type": "LegacyGallery/2.0.0"
    },
    {
      "@id": "https://www.nuget.org/api/v2/package",
      "@type": "PackagePublish/2.0.0"
    },	
    {
      "@id": "https://api-v2v3search-0.nuget.org/query",
      "@type": "SearchQueryService/3.0.0-rc",
      "comment": "Query endpoint of NuGet Search service (primary) used by RC clients"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/query",
      "@type": "SearchQueryService/3.0.0-rc",
      "comment": "Query endpoint of NuGet Search service (secondary) used by RC clients"
    },
    {
      "@id": "https://api-v2v3search-0.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService/3.0.0-rc",
      "comment": "Autocomplete endpoint of NuGet Search service (primary) used by RC clients"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService/3.0.0-rc",
      "comment": "Autocomplete endpoint of NuGet Search service (secondary) used by RC clients"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1/",
      "@type": "RegistrationsBaseUrl/3.0.0-rc",
      "comment": "Base URL of Azure storage where NuGet package registration info is stored used by RC clients"
    },
    {
      "@id": "https://www.nuget.org/packages/{id}/{version}/ReportAbuse",
      "@type": "ReportAbuseUriTemplate/3.0.0-rc",
      "comment": "URI template used by NuGet Client to construct Report Abuse URL for packages used by RC clients"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1/{id-lower}/index.json",
      "@type": "PackageDisplayMetadataUriTemplate/3.0.0-rc",
      "comment": "URI template used by NuGet Client to construct display metadata for Packages using ID"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1/{id-lower}/{version-lower}.json",
      "@type": "PackageVersionDisplayMetadataUriTemplate/3.0.0-rc",
      "comment": "URI template used by NuGet Client to construct display metadata for Packages using ID, Version"
    },
    {
      "@id": "https://api-v2v3search-0.nuget.org/query",
      "@type": "SearchQueryService/3.0.0-beta",
      "comment": "Query endpoint of NuGet Search service (primary) used by beta clients"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/query",
      "@type": "SearchQueryService/3.0.0-beta",
      "comment": "Query endpoint of NuGet Search service (secondary) used by beta clients"
    },
    {
      "@id": "https://api-v2v3search-0.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService/3.0.0-beta",
      "comment": "Autocomplete endpoint of NuGet Search service (primary) used by beta clients"
    },
    {
      "@id": "https://api-v2v3search-1.nuget.org/autocomplete",
      "@type": "SearchAutocompleteService/3.0.0-beta",
      "comment": "Autocomplete endpoint of NuGet Search service (secondary) used by beta clients"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1/",
      "@type": "RegistrationsBaseUrl/3.0.0-beta",
      "comment": "Base URL of Azure storage where NuGet package registration info is stored used by Beta clients"
    },
    {
      "@id": "https://www.nuget.org/packages/{id}/{version}/ReportAbuse",
      "@type": "ReportAbuseUriTemplate/3.0.0-beta",
      "comment": "URI template used by NuGet Client to construct Report Abuse URL for packages"
    },
    {
      "@id": "https://api.nuget.org/v3/stats0/totals.json",
      "@type": "TotalStats/3.0.0-rc",
      "comment": "Endpoint to get stats totals to display in nuget.org home page"
    },
    {
      "@id": "https://api.nuget.org/v3/registration1-gz/",
      "@type": "RegistrationsBaseUrl/3.4.0",
      "comment": "Base URL of Azure storage where NuGet package registration info is stored in GZIP format."
    },
	{
	  "@id": "https://api.nuget.org/v3/catalog0/index.json",
	  "@type": "Catalog/3.0.0",
      "comment": "Index of the NuGet package catalog."
	}
  ],
  "@context": {
    "@vocab": "http://schema.nuget.org/services#",
    "comment": "http://www.w3.org/2000/01/rdf-schema#comment"
  }
}
```

Does anyone have an idea why the response is so strange?

**Comment by Mpdreamz** [comment]
I just hit this error because my `sln` file was missing a `postSolution` section.
```
GlobalSection(ProjectConfigurationPlatforms) = postSolution
     ...
GlobalSection
```

**Comment by TimMurphy** [comment]
@Mpdreamz could you please expand on how to find and fix the problem you describe?

**Comment by emgarten** [comment]
The error here is a generic message that happens when a package cannot be found. There could be many different reasons for this, if anyone is still hitting this and have they have verified that the package does exist on the feed then please open a new issue with repro details since this needs to be looked at on a case by case basis.

@Mpdreamz it seems unlikely that the solution file is causing this issue. NuGet reads packages.config directly to find the list of packages to restore. If you are able to repro this consistently by adding and removing the postSolution section I would love to see the full repro steps, please open a new issue tracking that. Thanks!

**Comment by Mpdreamz** [comment]
@emgarten checkout https://github.com/elastic/elasticsearch-net alter `src/Elasticsearch.DotNetCoreOnly.sln` and remove its postSolution

```
$ dotnet restore src\Elasticsearch.DotNetCoreOnly.sln
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): warning : Unable to find a project to restore! [c:\Projects\elastic\net-master\src\Elasticsearch.DotNetCoreOnly.sln]
```

restore that postSolution section:

```
Mpdreamz@DESKTOP-C1TF44K c:\Projects\elastic\net-master
$ dotnet restore src\Elasticsearch.DotNetCoreOnly.sln
  Restoring packages for c:\Projects\elastic\net-master\src\Tests\Tests.csproj...
  Restoring packages for c:\Projects\elastic\net-master\src\Elasticsearch.Net\Elasticsearch.Net.csproj...
  Restoring packages for c:\Projects\elastic\net-master\src\Nest\Nest.csproj...

...
...
```

**Comment by willdaviesdevelops** [comment]
Using Jenkins on Windows.
Fixed with more elevated perms for the Jenkins service account.

**Comment by boudinekirrou** [comment]
Hi,
i have an issue to restore NuGet Package, when i click retore it give me the following error:  AN ERROR occured while trying to restore packages: Unable to find version 2.0.20525 of package 'expression-interactivity'
see attached screen 
i'm using the source: https://api.nuget.org/v3/index.json

thanks 

![error nuget](https://user-images.githubusercontent.com/15870461/50448962-7c46d400-0924-11e9-8929-e9e8b04b71dd.PNG)

**Comment by sparkcatalyst96** [comment]
Might help others: https://jfrog.com/knowledge-base/why-and-how-to-resolve-the-problem-of-install-search-of-nuget-packages-with-semver2-after-upgrade-to-6-0/
