### ISSUE TITLE
Old portable profiles have been opted into dnxcore50.

### ISSUE THREAD

**Issue by Pilchie** [NuGet/Home#1562]
As part of Win10Tools1.1/VS2015 Update 1, the portable tooling now opts existing profiles that support it into ASP.NET Core 5.0/dnxcore50.

NuGet will need to be able to reason about this.

**Comment by yishaigalatzer** [comment]
This needs a discussion, after spending some time with @emgarten we think this change should be reverted, or a new profile added.

I can be convinced otherwise, but this needs an immediate discussion, and we need to know about any such desired changes going forward.

**Comment by Pilchie** [comment]
It's not "a new profile".  It is the 8 or however many profiles that already have surface area that matches.

**Comment by yishaigalatzer** [comment]
@Pilchie I think that your statement above is the core of the issue here.

Creating portable-Random1+Random2+(wellKnownProfile1)  doesn't behave the same as portable-(wellKnownProfile2) when wellKnownProfile2 == Random1+Random2+(wellKnownProfile1)

**Comment by csharpfritz** [comment]
Questions that need to be answered:

Does this break existing clients?
Does this break existing packages?
Will existing packages not work with this new mechanism?

If the answer is yes to any of these questions then we need to find a better strategy.

**Comment by Pilchie** [comment]
Tagging @ericstj and @rchande in this issue too.

**Comment by yishaigalatzer** [comment]
@Pilchie ping, we think this needs to be reverted. It already broke users using visual studio 2013.

**Comment by derekmacdonald** [comment]
This breaks Xamarin Forms with VS2013, even if VS2015 has been uninstalled.

Details: https://bugzilla.xamarin.com/show_bug.cgi?id=34520

**Comment by yishaigalatzer** [comment]
This was fixed by @ericstj and friends :)

**Comment by ericstj** [comment]
FYI: I didn't fix this, @Pilchie & @rchande  did by hiding the registration from NuGet but still putting it in a place that the PCL project system could use it.
