### ISSUE TITLE
If package source list is empty, cannot add package source via UI (NuGet 3.4.x)

### ISSUE THREAD

**Issue by vortexau** [NuGet/Home#2617]
When trying to add Package Sources, access the config via Options -> Package Sources. Enter a 'Name' and 'Source' (valid details to try and install Moq), but then when I select 'Add' the item is added as 'Package source' with a URL of 'http://packagesource' and the fields updated to be those same values.

Apologies, I'm not sure of the version (unsure how to find that) - however I'm running VS 2015 Enterprise 14.0.25123.

![moq_pre_add](https://cloud.githubusercontent.com/assets/859420/14663002/f4bc4656-06fa-11e6-8110-356e9b638ea5.png)

![moq_not_added](https://cloud.githubusercontent.com/assets/859420/14661873/65e9a8f6-06f0-11e6-8974-e8d8f02bb6dc.png)

**Comment by rrelyea** [comment]
Workaround: manually add a source in the nuget.config located:  %appdata%\Roaming\NuGet\NuGet.Config

**Comment by yishaigalatzer** [comment]
Thanks for the report. This issue is fixed in 3.5 Beta, keeping it without a milestone because we might port it and release it earlier, still debating

**Comment by rrelyea** [comment]
@zhili1208 - can you please port this change to 3.4.5 today?

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/a9372618cda2c0a6c9e01fec8990fecce4246300 ported this change to 3.4.5

**Comment by duaneking** [comment]
Just got hit by this in the newest version, fix this please!

**Comment by rrelyea** [comment]
"newest version"?
think we fixed this problem in 3.5.0 for vs2015, which is posted at http://nuget.org/downloads

**Comment by duaneking** [comment]
I'm using Visual Studio 2015 Enterprise Edition, using the newest version of the app plugin based on the output from the extension and update manager, and this issue still exists as of the version 3.4.4.1321 that the manager says is installed.

**Comment by rrelyea** [comment]
Yes, 3.5.0 is not an auto-update. Please update to 3.5.0 via the URL I gave you above. It should fix your issue.

**Comment by duaneking** [comment]
Given that some corporate IT environments do not allow anything short of an auto update, may I ask when this will be made one?

**Comment by rrelyea** [comment]
We are being conservative and making sure we give this some time in the market place before turning on auto-update...just to make sure we get some extra validation time.
This is primarily because updates to NuGet without corresponding test runs on VS 2015 as part of major updates have extra risk.
We'd love your feedback on the policy.

We do believe this is a very good update and would love to hear your feedback.

**Comment by duaneking** [comment]
My friendly advice:  Just add more unit testing and TDD based code coverage for the UI, possibly use BDD for NuGet since its so critical to so many developers and companies.

**Comment by yishaigalatzer** [comment]
You would think we know that already :).

This is not a nuget team call, but an all up visual studio platform decision. Nothing else is allowed to auto update at this point.

You can opt in to auto updates by using our beta channel (see the blog).

**Comment by kennedyjosh** [comment]
This issue just occurred for me in VS2017. Workaround is to copy paste the below into the aforementioned nuget.config file:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
   <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

**Comment by hikaen2** [comment]
I have a same problem:
![Capture](https://user-images.githubusercontent.com/4222502/89554411-c8b8fc00-d849-11ea-904f-eb87c234d4d7.PNG)
How can I reset package sources?

**Comment by zivkan** [comment]
@hikaen2 the most likely reason I can think of is that one of the `nuget.config` files that NuGet tried to open is invalid XML. You can try going to `%appdata%\nuget` and rename `nuget.config` to something else. The next time NuGet tries to access it, it will re-create the file with defaults.

If a different `nuget.config` file is the problem, you can use our docs on [config file locations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) to check other paths.

In general, the most common location for config file problems is either `%appdata%\nuget\nuget.config` or any nuget.config file in your source code repo.

Also, closed issues are not watched very well. In the future you might get a better response by opening a new issue, rather than an issue that was closed 4 years ago.

**Comment by OleksiiFonin** [comment]
> I have a same problem: ![Capture](https://user-images.githubusercontent.com/4222502/89554411-c8b8fc00-d849-11ea-904f-eb87c234d4d7.PNG) How can I reset package sources?

I have same problem for VS 2022. After going to General tab and than back to Package Sources it shows everything.
