### ISSUE TITLE
Multiple instances of nuget.exe trying to install the same package in parallel causes a double write

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2628]
Scenario
ProjectA and ProjectB each have a packages.config that contain the same package.  They each build in parallel.  Each checks that the nuget package needs to be installed at the same time and then both try to install it.  (they both appear to install it fine.)  However the files are written out by both instances of nuget.exe.

(the plus side is this has revealed some bad practices where teams were hard linking from nuget package folders then overwriting the hardlinked file corrupting their nuget package install.)

(The down side is build tracers like buildcop need to now have nuget.exe exclusions for double-writes and doublewriting in practice is problematic especially if projectC thinks the package is installed because it is a large package that projectA installed and projectB is still doing a doublewrite and then projectC ends up doing a read lock on a file that projectB is trying to doublewrite causing an access violation.)

perhaps a mutex or something on the package folder should be created before nuget attempts to install a package.

**Comment by rrelyea** [comment]
What version of nuget.exe are you using?
Likely fixed in 3.3 or 3.4, we believe.

**Comment by yishaigalatzer** [comment]
Looks like we still have a hole with the static methods:

See these calls:
https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.ProjectManagement/Projects/FolderNuGetProject.cs#L94

https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.ProjectManagement/Projects/FolderNuGetProject.cs#L104

**Comment by zhili1208** [comment]
@kingerja I add a lock in folderNuGetProject, Can you help to validate the fix with my private build? Please ping me on skype, I can give you the build, thanks

**Comment by kingerja** [comment]
Sorry for delay my DRI rotation was very eventful.
I have been unable to get a standalone repro.  However I do have a consistent repro in one of the build systems I use.  So I can try any private I need and set any flags you desire for additional tracing.
I have pinged you on skype let me know what bits you want me to try.

**Comment by kingerja** [comment]
Hi I have been unable to produce a repro with this private.  I have run many builds and have not hit it.  Since it was a consistent repro it appears you have fixed this issue.

You may close this issue. Thanks.

**Comment by yishaigalatzer** [comment]
That's great news! @zhili1208 please include the commit on the issue before closing
