### ISSUE TITLE
Visual Studio 2015 CTP 6: Show from all sources. 

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#335]
@zoltu

As a user, I want an easy way to identify what packages are installed from the GUI.

There does not appear to be a way to tell the new NuGet package manager GUI to show a list of all packages from all sources. I have 4 package sources and in order to see what packages I have installed or search for a package I have to look through each collection separately.

**Comment by deepakaravindr** [comment]
Comment from @ggrnd0

+1
I vote for multiselect combobox and priority of package specified in settings.
If it possible for profiles in which specified list of sources and their priorities.
And specifiing sources directly in project.json file.

**Comment by feiling** [comment]
@zoltu Looks like you are talking about two issues:
- Can't list all installed packages from all sources. You can see that this has been fixed in VS 2015 CTP 6. 
- Can't search packages from all sources. There has been a feature request created for this.

**Comment by Zoltu** [comment]
Ah, I think the issue with listing all packages is just a very confusing UI then.  When I change the Filter to `Installed`, it still shows me the `Package source` dropdown which I can change.  However, upon closer examination it appears that changing that drop-down while I have `Installed` filter chosen does not do anything.

So I guess rather than a bug this is an improvement request to make the UX better for showing installed packages.  Two upgrades come to mind, the first being to make it more clear that the `Package source` doesn't mean anything while `Filter` is set to `Installed` and the second is to provide the user a way of identifying which package source a given installed package was pulled in from.
