### ISSUE TITLE
nuget.exe fails with mono (4.4.2.11) on rhel7 linux

### ISSUE THREAD

**Issue by schiebel** [NuGet/Home#3445]
Hi,
I'm trying to use NuGet to get GitVersion working on my linux system, but it seems like nuget.exe fails to even run with mono on rhel7...below is the output I get; sorry if this is a configuration issue, I am relatively new to using mono...

-bash-4.2$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.2 (Maipo)
-bash-4.2$ rpm -qi mono-core
Name        : mono-core
Version     : 4.4.2.11
Release     : 0.xamarin.1
Architecture: x86_64
Install Date: Wed 14 Sep 2016 11:04:59 AM EDT
Group       : Development/Languages/Mono
Size        : 76806936
License     : LGPL-2.1 and MIT and MS-PL
Signature   : RSA/SHA256, Fri 29 Jul 2016 06:19:39 AM EDT, Key ID a6a19b38d3d831ef
Source RPM  : mono-core-4.4.2.11-0.xamarin.1.src.rpm
Build Date  : Fri 29 Jul 2016 05:56:34 AM EDT
Build Host  : Azure0718022710.xamjenkins-builder.b8.internal.cloudapp.net
Relocations : (not relocatable)
URL         : http://www.mono-project.com
Summary     : Cross-platform, Open Source, .NET development framework
Description :
The Mono Project is an open development initiative that is working to
develop an open source, Unix version of the .NET development platform.
Its objective is to enable Unix developers to build and deploy
cross-platform .NET applications. The project will implement various
technologies that have been submitted to the ECMA for standardization.
-bash-4.2$ curl -Lsfo nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
-bash-4.2$ type mono
mono is hashed (/usr/bin/mono)
-bash-4.2$ rpm -q --whatprovides /usr/bin/mono
mono-core-4.4.2.11-0.xamarin.1.x86_64
-bash-4.2$ mono ./nuget.exe 
Could not load file or assembly or one of its dependencies.
-bash-4.2$ mono -v ./nuget.exe 

[nuget-mono-rhel7-log.txt](https://github.com/NuGet/Home/files/473196/nuget-mono-rhel7-log.txt)

**Comment by yishaigalatzer** [comment]
1. Please tell us what version of nuget.exe are you using?
2. This would probably be a mono issue rather than a nuget.exe issue. I would report it on the mono site. @kzu

**Comment by schiebel** [comment]
It looks like:
- curl -Lsfo nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

retrieves version 3.4.4...

**Comment by yishaigalatzer** [comment]
Thanks, I missed that.

**Comment by schiebel** [comment]
No problem, thanks for the quick reply!

I also (just) tried the v3.5.0-rc1 version, but with the same results...

**Comment by mrward** [comment]
Ubuntu 16.04 and NuGet 3.4.4 works OK for me with Mono 4.4.2. Not tried Red Hat. /cc @directhex

**Comment by directhex** [comment]
Mono 4.4+ has a persistent problem with distributions using Solaris-style directory names, like Red Hat. The relevant bug is https://bugzilla.xamarin.com/show_bug.cgi?id=41953

There are changes to the runtime needed to resolve the issue - I'll try and steal an engineer's time to hotfix the issue before 4.6 for Linux hits the stable channel.

**Comment by rrelyea** [comment]
@zhili1208 - please help

**Comment by zhili1208** [comment]
looks like this is fixed in mono 4.6

**Comment by rrelyea** [comment]
@schiebel - the linked mono bug has been fixed in Mono 4.6. Closing this issue. Please confirm that this addresses the issue for you. Thanks.

**Comment by schiebel** [comment]
Thank you for your persistence on this issue. Unfortunately, I get the same result as before. It could well be my error. The version that is installed is 4.6.2.16 and this is on RHEL7. Below is the basic output, and the verbose output is attached. Sorry...

-bash-4.2$ type mono
mono is hashed (/usr/bin/mono)
-bash-4.2$ rpm -q --whatprovides /usr/bin/mono
mono-core-4.6.2.16-0.xamarin.1.x86_64
-bash-4.2$ curl -Lsfo nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
-bash-4.2$ mono ./nuget.exe
Could not load file or assembly or one of its dependencies.
-bash-4.2$ mono -v ./nuget.exe > nuget-mono-rhel7-log-02.txt
Could not load file or assembly or one of its dependencies.
-bash-4.2$ tail nuget-mono-rhel7-log-02.txt 
converting method (wrapper runtime-invoke) object object:runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr)
Method (wrapper runtime-invoke) object object:runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr) emitted at 0x401de930 to 0x401dea28 (code length 248) [nuget.exe] with opts peephole,branch,inline,cfold,consprop,copyprop,deadce,linears,cmov,intrins,loop,fcmov,aot,exception,gshared,simd,alias-analysis
converting method (wrapper managed-to-native) void System.Runtime.InteropServices.GCHandle:FreeHandle (int)
Method (wrapper managed-to-native) void System.Runtime.InteropServices.GCHandle:FreeHandle (int) emitted at 0x401dea40 to 0x401deaee (code length 174) [nuget.exe] with opts peephole,branch,inline,cfold,consprop,copyprop,deadce,linears,cmov,intrins,loop,fcmov,aot,exception,gshared,simd,alias-analysis
converting method (wrapper managed-to-native) void System.Runtime.Remoting.Contexts.Context:ReleaseContext (System.Runtime.Remoting.Contexts.Context)
Method (wrapper managed-to-native) void System.Runtime.Remoting.Contexts.Context:ReleaseContext (System.Runtime.Remoting.Contexts.Context) emitted at 0x401deb40 to 0x401debee (code length 174) [nuget.exe] with opts peephole,branch,inline,cfold,consprop,copyprop,deadce,linears,cmov,intrins,loop,fcmov,aot,exception,gshared,simd,alias-analysis
converting method (wrapper managed-to-native) void System.Security.Cryptography.RNGCryptoServiceProvider:RngClose (intptr)
Method (wrapper managed-to-native) void System.Security.Cryptography.RNGCryptoServiceProvider:RngClose (intptr) emitted at 0x401dec00 to 0x401decae (code length 174) [nuget.exe] with opts peephole,branch,inline,cfold,consprop,copyprop,deadce,linears,cmov,intrins,loop,fcmov,aot,exception,gshared,simd,alias-analysis
converting method (wrapper managed-to-native) void System.Threading.InternalThread:Thread_free_internal (System.Threading.InternalThread,intptr)
Method (wrapper managed-to-native) void System.Threading.InternalThread:Thread_free_internal (System.Threading.InternalThread,intptr) emitted at 0x401decc0 to 0x401ded98 (code length 216) [nuget.exe] with opts peephole,branch,inline,cfold,consprop,copyprop,deadce,linears,cmov,intrins,loop,fcmov,aot,exception,gshared,simd,alias-analysis
-bash-4.2$ 
[nuget-mono-rhel7-log-02.txt](https://github.com/NuGet/Home/files/685938/nuget-mono-rhel7-log-02.txt)

**Comment by zhili1208** [comment]
@mrward is this fixed in 4.6.2?

**Comment by mrward** [comment]
Based on the comment from schiebel who is using Mono 4.6.2 it looks like it is not fixed. /cc @directhex

**Comment by directhex** [comment]
@mrward fixed in 5.0.0.36+ from tarballs, patched in mono-project.com packages for 4.6+ (but not in the tarballs)
