### ISSUE TITLE
Visual Studio 2015 CTP6: "nugetvs" installation failure 

### ISSUE THREAD

**Issue by jlouros** [NuGet/Home#354]
Hi there,

I was trying to install VS 2015 CTP6 yesterday, but for some reason it failed while applying package "nugetvs". On the installation log I have found this error messages:

**[04E8:06C4][2015-04-02T23:50:38]i000**: MUX:  ExecutePackageBegin PackageId: nugetvs
**[0E30:0BE8][2015-04-02T23:50:38]i301**: Applying execute package: nugetvs, action: Install, path: C:\ProgramData\Package Cache\{EE5B049A-CA9C-3DE6-BD6B-324D1E2DBFB8}v3.0.51210.242\packages\WPT\NuGetVisualStudio14.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7"'
**[04E8:06C4][2015-04-02T23:50:47]i000**: MUX:  ExecuteError: Package (nugetvs) failed: Error Message Id: 1722 ErrorMessage: There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
**[0E30:0BE8][2015-04-02T23:50:48]e000**: Error 0x80070643: Failed to install MSI package.
**[0E30:0BE8][2015-04-02T23:50:48]e000**: Error 0x80070643: Failed to execute MSI package.
**[04E8:06C4][2015-04-02T23:50:48]e000**: Error 0x80070643: Failed to configure per-machine MSI package.
**[04E8:06C4][2015-04-02T23:50:48]i000**: MUX:  Installation size in bytes for package: nugetvs MaxAppDrive: 0  MaxSysDrive: 5541888  AppDrive: 0  SysDrive: 192512
**[04E8:06C4][2015-04-02T23:50:48]i000**: MUX:  Return Code:0x80070643 Msi Messages:There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.   Result Detail:0 Restart:None
**[04E8:06C4][2015-04-02T23:50:48]i000**: MUX:  Set Result: Return Code=-2147023293 (0x80070643), Error Message=There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  , Result Detail=, Vital=False, Package Action=Install, Package Id=nugetvs
**[04E8:06C4][2015-04-02T23:50:48]i000**: Setting string variable 'BundleResult' to value '0'
**[04E8:06C4][2015-04-02T23:50:48]w350**: Applied non-vital package: nugetvs, encountered error: 0x80070643. Continuing...

**Comment by ChrisSfanos** [comment]
This is fixed in an update - please go and update via the Visual Studio Extension Gallery

**Comment by thorn0** [comment]
No, it isn't fixed.
Please go and see the "reviews" and "Q and A" on the Extension Gallery: https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d

**Comment by jlouros** [comment]
@thorn0 I wrote about it in my blog. What I describe in my post works perfectly. http://www.johnlouros.com/blog/how-to-fix-VS2015-CTP6-NuGet-installation-failure

**Comment by csharpfritz** [comment]
This has been fixed in our recent builds of Visual Studio and will be available with the next public release. 


-----Original Message-----

**Comment by Galan2X** [comment]
So for me, I get this error because when I updated Windows 10 10049 to 10061, it broke VS2015 CTP 6 (wouldn't launch), so I tried Repairing it and it finally fails with this error. Would John's trick work for me? Or should I uninstall and reinstall CTP 6, or wait for this new release you're talking about, Jeffrey?
