### ISSUE TITLE
PackageReference with a star in version is displayed under the updates tab/incorrectly represented in the installed tab

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3788]
### Steps
1. File > New Project > NETCore console app
2. Add a package reference with a star
3. Open the NuGet UI and go to the installed tab
### Expected

No updates displayed, and the correct package info is shown
### Actual

An update is displayed and no package info

``` xml
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.*</Version>
    </PackageReference>
```

![capture](https://cloud.githubusercontent.com/assets/6381138/19752314/3b52d558-9bb1-11e6-9326-19bc09ffa8ee.PNG)

Another customer report: 
https://developercommunity.visualstudio.com/content/problem/277887/nuget-package-manager-doesnt-respect-package-refer.html

Another scenario: https://github.com/NuGet/Home/issues/3101

[SPEC]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Build-Integrated-Project-handling-of-floating-versions-and-ranges-in-Visual-Studio-Client

**Comment by hkoelewijn** [comment]
It would be nice if VS allowed you to specify wildcards in the package manager in stead of us having to open the proj file directly

**Comment by pmiossec** [comment]
I think that's linked but when, in the "Package Manager Console", when you list the packages installed (with `Get-Package` command), you get the last number at "0".

Example: 
For: `<PackageReference Include="Newtonsoft.Json" Version="9.0.*" />`
you will always get (even if `9.0.3` is really installed) : `Newtonsoft.Json                     {9.0.0}` 

That's surely why "Nuget Package Manager` see it as "Should be updated"...

Is there some update on this issue? Seems to be postponed since v4.0... :cry:

**Comment by Neme12** [comment]
I found this after searching and trying out different things for 20 minutes thinking I must be doing something wrong with the wildcard :confused:

**Comment by tobiasschulz** [comment]
Yeah I really don't get why this has not been fixed yet.

**Comment by rfcdejong** [comment]
Any ETA?

**Comment by pmiossec** [comment]
That's the type of issue, that completely prevent the use of wildcard (I had to fallback to hardcoded version 😢 ) and so to put in place an update strategy that let me think that the paket ( https://github.com/fsprojects/Paket ) community driven project is a lot better solution to manage dependencies in a .net project....

That's a shame that the nuget team don't borrow most of the excellent ideas brought by this solution to spread them to the all the .net developers and make nuget a correct dependency manager 😢

**Comment by SaebAmini** [comment]
Wow, 3 years and no movement on such a basic package management feature?

**Comment by wickedmachinator** [comment]
really, we still can't use the floating version number along with visual studio?

**Comment by pmiossec** [comment]
I'm pretty sure that will be fixed soon, they put the 'priority:1' label...  😀😭

**Comment by Zastai** [comment]
Note: JetBrains' Rider IDE had the same issue (https://youtrack.jetbrains.com/issue/RIDER-37878). It was fixed the day after I reported it (the actual rollout won't be until the upcoming 2020.1 release though).

**Comment by PandeleFlorin** [comment]
2020 and STILL this is not fixed. Is it a major issue YES. Imagine a project that has multiple .sln files and you upgrade just some of the references in some of the slns but not all. Now I have to hunt for where the damn thing was used, in hundreds if not more slns.

**Comment by Duranom** [comment]
Can this be resolved soon? When is this getting planned? Any time at least before .NET 5 comes out?
It is causing for some battles between CI reporting packages out of date every now and then because someone keeps incidentally updating through the UI and forgetting to update the proper projects. Someone even raised the topic to reintroduce the nightmare Paket thing to tackle it.

**Comment by harigutta** [comment]
Any updates on this issue?

**Comment by aschuhardt** [comment]
This is still very relevant and a major pain point for many of us, I'm sure.

**Comment by Sl1ckR1ck** [comment]
Any update on this? Basically we can't use floating version at all?

Why is it still listed as a feature in the documentations?

**Comment by nkolev92** [comment]
@Sl1ckR1ck 

You can use floating versions, it's just the package manager UI that doesn't show you the floating versions are being used.

**Comment by tobiasschulz** [comment]
Yeah, but whyyy not?

Also the UI breaks / removes the floating versions if you use it.
It should at least leave those alone when updating packages. That would be the least they could do.

**Comment by websitewill** [comment]
> Yeah, but whyyy not?
> 
> Also the UI breaks / removes the floating versions if you use it. It should at least leave those alone when updating packages. That would be the least they could do.

100% agree. Just ran into this and spent time trying to figure out what I was doing wrong...

**Comment by Sl1ckR1ck** [comment]
Yes, as soon as you update using the package manager, it replaces the floating version with the fixed version.

I would understand this logic if the package was replaced with a version that doesn't match the floating version pattern...

I am using the floating version to provide our CI pipeline with some automation that ensure that all the latest components of our software package are building well together and run some automated tests.

**Comment by nkolev92** [comment]
Hey all, 
This will be available in 17.3.

You will be able to install custom versions, and packages that resolve to latest via a floating version won't be shown in the updates tab. 

Note that you can still `clobber` the user specified version if you install an exact version of a package. You can track that in https://github.com/NuGet/Home/issues/6566. 

![installing-floating-versions](https://user-images.githubusercontent.com/2878341/181661438-b4546313-74ab-49b2-9c25-6e88337c1c55.gif)
![floating-versions](https://user-images.githubusercontent.com/2878341/181661443-e76fc2fe-8295-4be5-83b9-0521541b9a2a.png)

cc @martinrrm

**Comment by PandeleFlorin** [comment]
Great. After How many YEARS was this solved? I don't even use VS/nugget any more...

**Comment by uhfath** [comment]
Is this really works?
This is what I get on VS 17.4:
![image](https://user-images.githubusercontent.com/14792749/200799554-f9b49026-dec1-4525-8e69-e9982a9483b7.png)
![image](https://user-images.githubusercontent.com/14792749/200799716-3e31b4e4-b112-46da-a2a7-98e1156f3ae0.png)
Tried numerous combinations defined [in docs](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges)
In the end I either get that my version installed is 1.x.x or even 0.0.0.
And when the UI always shows there is an update available. And after updating it replaces my wildcards with a specific version updated.

**Comment by nkolev92** [comment]
> And when the UI always shows there is an update available. And after updating it replaces my wildcards with a specific version updated.

You can type a version to update to manually. When you click installing 7.0.0, it thinks you want to install 7.0.0. 

The free form version entering is only available in the project level UI.

**Comment by uhfath** [comment]
> > And when the UI always shows there is an update available. And after updating it replaces my wildcards with a specific version updated.
> 
> You can type a version to update to manually. When you click installing 7.0.0, it thinks you want to install 7.0.0.
> 
> The free form version entering is only available in the project level UI.

The problem is that I don't click "install". I click "update" which implicitly works like an install. But there is no other way through UI except picking the version manually for each project.
Work the same way per-project or per-solution.

**Comment by martinrrm** [comment]
@uhfath Hi! Using floating versions in the PM UI is only available for project level at the moment. Updating/Installing to a version using the versions combobox will override what you have in your project file. In your screenshot your version is `6.*` which will not cover the version `7.0.0` which is the latest and is why is suggesting you an update. If you always want the latest version, I suggest using `*` instead.

**Comment by uhfath** [comment]
@martinrrm Thanks for the info.
Actually in our case we want to keep 6.* versions and not transition to major 7.x until we ready.
I tried to use version range notation like (,7.0) or [6.0,7.0) or event [6.0] but the results were always the same. There are always 'updates' available to 7.0 and after pressing 'update' they all overwrite.
Is using version ranges supported for solution or project level?
Is there any working method to keep major version without changes and use solution or project level updating?

**Comment by Zastai** [comment]
It's a bit of a hack, but you can add `IsImplicitlyDefined="true"` to a `PackageReference`. That tells the package manager that it comes from an SDK, which I think stops it from offering upgrades for it. However, it may also hide it entirely; not sure now (and can't currently check).

**Comment by uhfath** [comment]
@Zastai yep. It becomes hidden entirely even though there is an update to the minor version.
Just checked like this:
`<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" IsImplicitlyDefined="true" Version="6.0.10" />`
There is an update to `6.0.11` which I wanted to apply but using this attribute the entire package is hidden.

**Comment by davide-bergamini-sevenit** [comment]
This problem is still present

**Comment by fedordavid** [comment]
I'm facing this problem still and very unconvenient
