### ISSUE TITLE
Restore logs are lost and not persisted in the output window

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#3884]
build: d15rel/25904.2
cli: 1.0.0-preview3-004056

Create any Console application (.Net Core ) , this will kick in Auto restore which will display the restore information at the information bar , which disappears once completed.

![image](https://cloud.githubusercontent.com/assets/12449387/20070143/2a6a3ee4-a4d4-11e6-9453-dfb329e3cff4.png)

I don't see any log in the VS output window.

**Comment by alpaix** [comment]
Resolved with NuGet/NuGet.Client#1052.

**Comment by KristinXie1** [comment]
This issue is still repro on build [d15prerel.26105.05](\\cpvsbuild\drops\VS\d15prerel\products\26105.05\bootstrappers\Enterprise\vs_enterprise.exe).

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
