### ISSUE TITLE
Restoring Nuget packages hangs when building a solution with both aspnet 5 and mvc 5 project

### ISSUE THREAD

**Issue by Praburaj** [NuGet/Home#419]
Moving bug from aspnet/tooling:

https://github.com/aspnet/Tooling-Internal/issues/287

Get code from release branch: https://github.com/aspnet/musicstore/tree/release

Open the solution in VS and try to build. I see it gets stuck in Nuget package restore on MVC5 project for a long time.

![image](https://cloud.githubusercontent.com/assets/2294732/7033123/c3cc6cf4-dd2c-11e4-8e52-d9474f3fd20d.png)

**Comment by Praburaj** [comment]
I tried to do package restore on an individual MVC5 project and I notice error "Central directory corrupt". 

![image](https://cloud.githubusercontent.com/assets/2294732/7121284/5ef57b68-e1c8-11e4-8ff9-3bfda0e4bf27.png)

**Comment by yishaigalatzer** [comment]
@Praburaj this I believe was resolved already. Let's discuss in person tomorrow how to verify and report these kind of issues

**Comment by Praburaj** [comment]
@yishaigalatzer is the fix in latest WTE? I have a pretty recent build (build that was available on 4/13) and I still see the issue.

**Comment by Praburaj** [comment]
@yishaigalatzer @deepakaravindr we tried this with the latest nuget package manager and this issue seems not to reproduce. However there are 2 different issues we noticed:

1. The progress dialog does not show the name of the packages being restored. Previously it used to show. Not sure if this a regression or by design. 
2. On one of the retries we noticed the restore failed for EF6 packages with this error resulting in a bunch of build errors. But this disappeared on doing a restore missing packages.

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet package restore failed.
1>------ Build started: Project: MusicStore, Configuration: Debug Any CPU ------
2>------ Build started: Project: MusicStore.Spa, Configuration: Debug Any CPU ------
3>------ Build started: Project: DeploymentHelpers, Configuration: Debug Any CPU ------
4>------ Build started: Project: MvcMusicStore, Configuration: Debug Any CPU ------
5>------ Build started: Project: MvcMusicStore.Spa, Configuration: Debug Any CPU ------
NuGet Package restore failed for project src\MvcMusicStore.Spa: The context is not currently tracking the entity..
NuGet Package restore failed for project src\MvcMusicStore: The context is not currently tracking the entity..

```

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/059265bcf710ec01e62da072c2d78358fe52c529 and NuGet/NuGet.PackageManagement@80e6e5a
