### ISSUE TITLE
Init scripts are not being executed when package installed through dotnet add command

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#5456]
Steps:
1. Create .net core console app
2. Open PMC
3. Go to dev command prompt and use dotnet.exe to add EntityFramework package into this project.
4. Come back into VS, you'll see it already restored after you added EntityFramework.
5. Run "Add-Migration" command in PMC, it won't recongnize it.
6. Close/open solution, and again run "Add-Migration" cmd, it will still won't recognize it.

Root cause of this command not recognized is, it hasn't executed the init script associated with EntityFramework package. It should have executed this init script at step4 (when it restored the project) and step 6 (when solution was reloaded).

**Comment by mishra14** [comment]
`dotnet add package` cannot execute the script as it runs outside VS. But maybe we need to add code to listen to added packages and execute scripts.

**Comment by jonkerr** [comment]
I believe this issue started with VS 2017 Update 2.  Since the update, I can't add any migrations due to this "init.ps1' is not recognized as the name of a cmdlet..." issue.
Visual Studio 15.2 (26430.16) 
Package Manager Console Host 4.2.0.2457

I copied the project to a different computer without the update and was able to add migrations again.
Visual Studio 15.0.0+26228.9
Package Manager Console Host 4.0.0.2323

**Comment by zhili1208** [comment]
looks like this is fixed by @alpaix https://github.com/NuGet/NuGet.Client/commit/e5d632d5ed22380626ea8579b9c49ee1f3379b53

**Comment by zhili1208** [comment]
@jonkerr could you try Visual Studio 2017 15.3 Preview 7 from https://www.visualstudio.com/vs/preview/? this is fixed in that version.

**Comment by jonkerr** [comment]
I got 15.3 Preview 7 yesterday.  This is still an issue in that version.

**Comment by zhili1208** [comment]
@jonkerr Could you provide repro steps for your scenario and nuget version in your VS? thanks

**Comment by jonkerr** [comment]
Visual Studio 15.2 (26430.16)
Package Manager Console Host 4.2.0.2457

1) Close Visual Studio
2) Open Visual Studio
3) Load Project (auto package restore turned on)
4) Open PMC window
5) See error "The term 'C:\Users\[username]\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:45"
6) Type:  Add-Migration test
7) Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
```
 + Add-Migration test
 + ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by alpaix** [comment]
Can you confirm the `init.ps1` file presents on disk and packages cache is not corrupted?

**Comment by jonkerr** [comment]
Confirmed on disk in location noted above.  I'm able to open with powershell (so I assume not corrupted).  Where is the package cache?

**Comment by alpaix** [comment]
Package cache is at `%USERDIR%\.nuget\packages`.

Also, based on your comment you were not running 15.3 version
> Visual Studio 15.2 (26430.16)
> Package Manager Console Host 4.2.0.2457

**Comment by jonkerr** [comment]
Update: Disabled every Visual Studio extension (and there were a lot I wasn't expecting) 
No PMC errors and Adding a migration works.  Must be a conflict with something

**Comment by jonkerr** [comment]
I didn't want to do production work on a preview version but yes, I did try 15.3 Preview 7 with PMC 4.3.0.4339 yesterday and failed as well.  

However, since I disabled extensions in my 15.2 version, PMC works fine in 15.3... even though I didn't disable those extensions... weird

**Comment by jonkerr** [comment]
I'm going to re-enable one by one and see if I can find the conflicting extension

**Comment by zhili1208** [comment]
package caches is  'C:\Users[username]\.nuget\packages\', I suspect one case: when restore is still running and open PMC, at that time, init.ps1 is not on the disk, PMC get package init.ps1 path from lock file. then it might get this error.

Could you try following steps?
 Close VS-> Open VS-> Load Project -> wait until restore is done -> confirm the file is at 'C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1'-> Open PMC

Do you still hit this issue?

**Comment by jonkerr** [comment]
Re-enabled all extensions... and PMC works fine in 15.2 now.

**Comment by zhili1208** [comment]
does pmc works in 15.3 preview 7 now?

**Comment by jonkerr** [comment]
Oddly enough, yes.  Even though I wasn't doing anything with those extensions

**Comment by zhili1208** [comment]
Please try this, remove the package cache folder and do the repro steps again to see if you can repro the issue

**Comment by jonkerr** [comment]
Great, now it's hosed again.  
1) Deleted the packages folder
2) Did a dotnet restore
3) Broken again

4) Deleted packages again and restored from backup
5) Still broken

If the only fix is disabling all my extensions and re-enabling, that can wait till Monday.

**Comment by zhili1208** [comment]
I suspect the issue here is you open PMC before restore done. when you open PMC, PMC will try to execute init.ps1, if the restore is still in process, PMC might can't find the init.ps1 file on disk.

Could you confirm this theory? 

1. Deleted Packages folder.
2. restore
3. wait until restore is done, check the init.ps1 on disk.
4. Open PMC.

Does those steps work?

**Comment by jonkerr** [comment]
I have packages on auto restore and wait till complete before opening PMC
so I don't think that's the case.

Also, I backed up packages when it all still worked. After restoring with
VS, the project would compile. Then, I'd open PMC and get the error. I then
deleted packages and restored from my backup that I know had everthing:
after restarting VS, PMC still complained.

Why would disabling then re-enabling my extensions fix the issue?

--

**Comment by jonkerr** [comment]
And it's still broken.  Disabling my extensions didn't fix it this time.  Help!!

**Comment by jonkerr** [comment]
@zhili1208 no, those steps don't work

**Comment by zhili1208** [comment]
Could you try to uninstall microsoft.entityframeworkcore.tools and remove the package from cache, then install it again?

it will execute init.ps1 during install. 

And please always try it on VS 15.3 preview 7.

**Comment by jonkerr** [comment]
That worked.  Thanks @zhili1208

**Comment by zhili1208** [comment]
Please update to 15.3-RTM which is released this morning, close this, feel free to reopen it, if you still hit this issue.

**Comment by jonkerr** [comment]
Still an issue if I close VS and reopen.  PMC only works if I uninstall and reinstall Tools first, which is pretty tedious

**Comment by jonkerr** [comment]
PMC does not work in 15.3.  Please reopen

**Comment by zhili1208** [comment]
do you hit the following error in 15.3?
See error "The term 'C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:45"

**Comment by zhili1208** [comment]
also this issue is related to your machine or project? does pmc work with same project on other machine? If not, please share an repro project for investigation. Thx

**Comment by jonkerr** [comment]
Yes I still see that issue.  And yes, PMC works fine for the same project on a different machine that wasn't updated to 15.2  (It's 15.0 and I will not update it until this is fixed)

**Comment by jonkerr** [comment]
The issue began after the update to 15.2 and did not get better with 15.3

**Comment by zhili1208** [comment]
I see, looks like your project + 15.3 can repro this on any machine, so is that possible to share an repro project for investigation?

**Comment by zhili1208** [comment]
also please run "C:\Users[username]\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1" in PMC, do you hit same issue?

**Comment by jonkerr** [comment]
Unfortunately, I can't share the project with you due to IP restrictions.  I tried to create another project but for some reason that one worked fine.

If I run "C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1" it completes without error.  However, a subsequent call to Update-Database causes an error

"The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file..."

**Comment by zhili1208** [comment]
what's your Powershell version? you can check it from $PSVersionTable.PSVersion.

if you run "import-module C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\EntityFrameworkCore.psd1", does update-Database work?

**Comment by jonkerr** [comment]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10240  17488   

After running the above command, Update-Database does not work.  Also, I get this error message upon running it: 

The names of some imported commands from the module 'EntityFrameworkCore' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb

**Comment by zhili1208** [comment]
@balachir looks like importing the module "EntityFrameworkCore" doesn't import all functions. Any ideas?

**Comment by zhili1208** [comment]
Please run "import-module C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\EntityFrameworkCore.psd1 -verbose"

Could you get following?:
```
Importing function 'Add-Migration'.
The names of some imported commands from the module 'EntityFrameworkCore' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
The 'Drop-Database' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Drop-Database'.
Importing function 'Enable-Migrations'.
Importing function 'Get-DbContext'.
Importing function 'Remove-Migration'.
The 'Scaffold-DbContext' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Scaffold-DbContext'.
The 'Script-Migration' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Script-Migration'.
Importing function 'Update-Database'.
```

**Comment by jonkerr** [comment]
Loading module from path 'C:\Users\[user]\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\EntityFrameworkCore.psd1'.
Loading module from path 'C:\Users\[user]\.nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\EntityFrameworkCore.psm1'.
Exporting function 'Add-Migration'.
Exporting function 'Drop-Database'.
Exporting function 'Enable-Migrations'.
Exporting function 'Remove-Migration'.
Exporting function 'Scaffold-DbContext'.
Exporting function 'Script-Migration'.
Exporting function 'Update-Database'.
Exporting function 'GetProjects'.
Exporting function 'GetProviders'.
Exporting function 'GetContextTypes'.
Exporting function 'GetMigrations'.
Exporting function 'WarnIfEF6'.
Exporting function 'GetProject'.
Exporting function 'GetStartupProject'.
Exporting function 'GetSolutionProjects'.
Exporting function 'GetParams'.
Exporting function 'ShowConsole'.
Exporting function 'EF'.
Exporting function 'IsXproj'.
Exporting function 'IsCsproj2'.
Exporting function 'IsWeb'.
Exporting function 'IsUWP'.
Exporting function 'GetIntermediatePath'.
Exporting function 'GetPlatformTarget'.
Exporting function 'GetOutputFileName'.
Exporting function 'GetProjectTypes'.
Exporting function 'GetProperty'.
Exporting function 'GetCsproj2Property'.
Exporting function 'GetProjectItem'.
Exporting function 'ToArguments'.
Importing function 'Add-Migration'.
The names of some imported commands from the module 'EntityFrameworkCore' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
The 'Drop-Database' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Drop-Database'.
Importing function 'Enable-Migrations'.
Importing function 'Remove-Migration'.
The 'Scaffold-DbContext' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Scaffold-DbContext'.
The 'Script-Migration' command in the EntityFrameworkCore' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
Importing function 'Script-Migration'.
Importing function 'Update-Database'.

```
PM> Update-Database
Update-Database : The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Update-Database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Update-Database:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jonkerr** [comment]
Any update on this?  I've been advising my colleagues against updating from 15.0 since adding migrations still works for anyone who hasn't upgraded to 15.2 or 15.3

**Comment by zhili1208** [comment]
@mlorbetske Could you take a look? Since importing the module manually doesn't work, looks like it's not a nuget issue

**Comment by mlorbetske** [comment]
@livarcocc @nguerrera any ideas who'd be the right person to look in to this?

**Comment by nguerrera** [comment]
Happy to help if I can, but I am having a really hard time following how this would be a CLI issue.

**Comment by mlorbetske** [comment]
@nguerrera the original issue mentioned was that NuGet in the CLI wasn't allowing the init scripts to run. +@bricelam for the specific init.ps1 in question

**Comment by bricelam** [comment]
*@jonkerr said:*

> If I run "C:\Users[username].nuget\packages\microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1" it completes without error. However, a subsequent call to Update-Database causes an error "The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file..."

Does executing the following help?

``` ps1
Set-ExecutionPolicy RemoteSigned
```

**Comment by jonkerr** [comment]
Applied to all.  Didn't help.

**Comment by mishra14** [comment]
@jonkerr are you still facing this issue with latest VS 2017 15.5?

**Comment by jonkerr** [comment]
I stopped using visual studio but thanks for checking.

Jon

--
Sent from my phone. Spelling (in)corrections courtesy of Android.


On Dec 19, 2017 3:03 PM, "Ankit Mishra" <notifications@github.com> wrote:

@jonkerr <https://github.com/jonkerr> are you still facing this issue with
latest VS 2017 15.5?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NuGet/Home/issues/5456#issuecomment-352913677>, or mute
the thread

**Comment by mishra14** [comment]
closing this issue. Can be reopened if we have more repros, in the future.

**Comment by EDToft** [comment]
I know that this is ancient history and it is marked closed...BUT...4 years later, here we are. There does not seem to be any true documentation or any resolution to the issue. Here in this forum, the issue was closed because jonkerr quit using Visual Studio, and no one took it up. 

Sooo...why the heck am I digging it back up?

a) It is 2021 and we ARE seeing this problem. 
b) My team is using Microsoft Visual Studio Enterprise 2019 Version 16.11.7. 
c) I think I have some ideas about why.
d) I definitely have a work-around for it. 

If you want my suspicions on why and how I worked through it, continue reading. If you just want to give it a go, then go to the "WORK AROUND")

WHY I think it is happening...at least for us...
I work in a secure environment, and cannot share direct details...however my suspicion is that the security is what is messing things up for us.

First stab at it...
Our group policy for PowerShell is set to lockdown the -executionpolicy to Restricted. We have some freedom when we elevate our security, and therefore, at a PS command prompt, we can take advantage of setting -executionpolicy bypass while using those elevated credentials.

So, I began thinking that the problem could stem from these same security policies. We cannot run VS with our elevated security due to conflicting policies...admin account can't access our source repo; Ergo, we cannot use Visual Studio as admin. At the same time VS cannot be set up (that I know of) to run the PMC with the execution policy bypass without the elevated security.

Total Catch 22.

Possible solution 1...
I tried variations on setting the execution policyfrom an elevated (admin) Powershell command window...
           Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
           Set-ExecutionPolicy AllSigned -Scope LocalMachine -Force
           Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
           Set-ExecutionPolicy AllSigned -Scope CurrentUser -Force

...but when I try to run the init.ps1 script I get the following...

            Test-ModuleManifest : The name of the current Windows PowerShell host is: 'ConsoleHost'. 
            The module C:\Users\[ME]\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.0\tools\EntityFrameworkCore.psd1'
            requires the following Windows PowerShell host: 'Package Manager Host'........

Possible solution 2...
Each time I also started Visual Studio (un-elevated), to try loading my EF Core project. I still get the error...

          ......init.ps1' is not recognized as the name of a cmdlet, function.....

Another catch 22.

Possible solution 3...BINGO!
Our wonderful group policy also dictates that we can only access/execute code and scripts from certain directories...so I thought "Hey...this may be part of the issue too."

WORK AROUND
I went to C:\Users\[ME]\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.0\tools\ and copied all of the files shown here...

net461                   (dir)
netcoreapp2.0       (dir)
about_EntityFrameworkCore.help.txt
EntityFrameworkCore.PS2.psd1
EntityFrameworkCore.PS2.psm1
EntityFrameworkCore.psd1
EntityFrameworkCore.psm1
init.ps1

...to a location that I know will have execution permissions...c:\executeallowed\

In Visual Studio, at the PMC command line I entered...

            c:\executeallowed\init.ps1

...and VIOLA it worked.

It's so simple that I felt stupid...but maybe admitting my stupid will help someone else out.

**Comment by 1RJB** [comment]
Also got a similar error when opening the package manager console. resulting in being unable to run `Update-Database` or `Add-Migration Initial`:

```
& : The term 'C:\Users\[Username]\.nuget\packages\microsoft.entityframeworkcore.tool
s\9.0.0\tools\init.ps1' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:45
+ ... rgs+=$_}; & 'C:\Users\[Username]\.nuget\packages\microsoft.entityframework ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\[Username]\...\tools\init.p 
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
```
Note: Using Version 17.12.1 of Visual Studio Community 2022 (Released Novemeber 19th, 2024)


This might help someone (as it worked for me):

One possible solution could be manually importing the tools module with this,

`Import-Module "C:\Users\[Username]\.nuget\packages\microsoft.entityframeworkcore.tools\[Version No.]\tools\EntityFrameworkCore.psd1"
`
Note: Replace [Username] with your Windows username. Replace [Version No.] with the version of microsoft.entityframeworkcore.tools you have installed.

But this solution requires to do this everytime you open the Project or create a new Project, so kind of tedious
