### ISSUE TITLE
Projects having netcoreapp1.1;net46 targets don't restore at all

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5645]
_From @abpiskunov on July 24, 2017 23:50_

1. Create a Web App netcoreapp1.1 
2. wait for restore
3. edit csproj and add net46 target (don't forget to change element name to TargetFrameworks)
4. Save and reload project 

Actual result:

No auto restore happening, right click on Solution node and clicking "Restore Nuget Packages" dpes nothing

![image](https://user-images.githubusercontent.com/1592091/28549620-26ac93aa-7090-11e7-9dc0-35e207d5cad3.png)

_Copied from original issue: dotnet/project-system#2656_

**Comment by davkean** [comment]
_From @abpiskunov on July 24, 2017 23:50_

Also notice that no resolved references sent for anything under .NetFramework 4.6...

**Comment by davkean** [comment]
It thought this might be different: https://github.com/dotnet/project-system/issues/2658 but it's probably the same thing. I'm guessing the code that joins the configured projects subscriptions together is causing this and preventing us from notifying NuGet of the changes.

**Comment by davkean** [comment]
This looks to be NuGet bug, this is throwing InvalidOperationException:

```

	System.Core.dll!System.Linq.Enumerable.SingleOrDefault<string>(System.Collections.Generic.IEnumerable<string> source)	Unknown	No symbols loaded.
 	NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetNonEvaluatedPropertyOrNull<string>(NuGet.SolutionRestoreManager.IVsTargetFrameworks tfms, string propertyName, System.Func<string, string> valueFactory)	Unknown	No symbols loaded.
 	NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetRestoreSources(NuGet.SolutionRestoreManager.IVsTargetFrameworks tfms)	Unknown	No symbols loaded.
 	NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToPackageSpec(NuGet.VisualStudio.ProjectNames projectNames, NuGet.SolutionRestoreManager.IVsProjectRestoreInfo projectRestoreInfo)	Unknown	No symbols loaded.
 	NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToDependencyGraphSpec(NuGet.VisualStudio.ProjectNames projectNames, NuGet.SolutionRestoreManager.IVsProjectRestoreInfo projectRestoreInfo)	Unknown	No symbols loaded.
 	NuGet.SolutionRestoreManager.dll!NuGet.SolutionRestoreManager.VsSolutionRestoreService.NominateProjectAsync(string projectUniqueName, NuGet.SolutionRestoreManager.IVsProjectRestoreInfo projectRestoreInfo, System.Threading.CancellationToken token)	Unknown	No symbols loaded.

```

**Comment by emgarten** [comment]
This has been fixed as part of https://github.com/NuGet/Home/issues/5529

Here netcoreapp1.1 adds a source but net46 does not, the result is a mismatch between TFMs.

**Comment by davkean** [comment]
Which build was this fixed in? I'm not seeing it fixed in Version 15.3.0 Preview 5.0 [26721.2.d15rel]

**Comment by emgarten** [comment]
This change hasn't gone into d15rel yet, there is a PR out for the insertion and it will hopefully be in soon.

It was fixed in NuGet as part of: https://github.com/NuGet/NuGet.Client/pull/1568

**Comment by dozer75** [comment]
Any status for this in Visual Studio, it still an issue in 15.3.4...

**Comment by emgarten** [comment]
@dozer75 file a new issue with repro steps, thanks!

**Comment by dozer75** [comment]
@emgarten Done! As linked above.
