### ISSUE TITLE
Upgrade to Visual Studio 15.3 regressed package.json build behaviour for C++ UWP projects

### ISSUE THREAD

**Issue by DHowett-MSFT** [NuGet/Home#5815]
Please read the following information before posting the issue.
[Dll1.zip](https://github.com/NuGet/Home/files/1258498/Dll1.zip)

## Details about Problem

*NuGet product used:*
VS UI

*NuGet version (x.x.x.xxx):*
That which was shipped in VS 2017 Update 3

*VS version (if appropriate):*
26815.3 [and prior]

*OS version (i.e. win10 v1607 (14393.321)):*
win10 v1703 and insider builds

*Worked before?*
_Yes, with VS 2017 Update 2._

## Detailed repro steps so we can see the same problem

1. Create a project of type `DLL (Universal Windows)`

2. Add a project.json with no dependencies (or, any number of _native_ dependencies)

```json
{
  "dependencies": { },
  "frameworks": {
    "uap10.0": {
      "imports": [
        "native",
        "uap"
      ]
    }
  }
}
```

3. Restore Packages for Solution

4. Build All

5. The build fails:

```
1>------ Rebuild All started: Project: Dll1, Configuration: Debug Win32 ------
...
1>Target ResolveNuGetPackageAssets:
1>    C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5):
   error : Your project is not referencing the "UAP,Version=v10.0" framework.
   Add a reference to "UAP,Version=v10.0" in the "frameworks" section of your
   project.json, and then re-run NuGet restore.
1>Done building target "ResolveNuGetPackageAssets" in project "Dll1.vcxproj" -- FAILED.
1>
1>Done building project "Dll1.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

...

### Investigation

Restoring a native project with a project.json in Visual Studio¬, even if it doesn’t consume NuGet.Build.Packaging, results in the following:

Project.lock.json is populated with framework references:

```
{
  "version": 3,
  "targets": {
    "UAP,Version=v10.0.10586": {
      ...
    "UAP,Version=v10.0.10586/win10-arm": {
      ...
    "UAP,Version=v10.0.10586/win10-arm-aot": {
      ...
    "UAP,Version=v10.0.10586/win10-x86": {
      ...
    "UAP,Version=v10.0.10586/win10-x86-aot": {
      ...
```

However, the Preferred Target Moniker here is UAP,Version=v10.0.

Microsoft.NuGet.Build.Tasks' [ResolveNuGetPackageAssets.cs:660](https://github.com/NuGet/NuGet.BuildTasks/blob/dev/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L660) uses that preferred target moniker to look up the target in project.lock.json. Clearly, that doesn’t exist.

It looks like either package restore is putting too much version information in project.lock.json or ResolveNuGetPackageAssets doesn’t support any manner of version fallback. It doesn’t strain belief that v10.0.10586 should provide v10.0.

This reproduces in 15.3’s public release and 15.4 preview.

### Sample Project

[Dll1.zip](https://github.com/NuGet/Home/files/1258499/Dll1.zip)

### Real-world example

We have a large set of projects consuming native dependencies via project.json at [WinObjC](http://github.com/Microsoft/WinObjC). As of VS15.3 the in-tree build for these projects fails with the above error.

**Comment by rrelyea** [comment]
Duplicate of #5806 
@jainaashish, @rohit21agrawal  - we may need to fix in 15.4.0 p2 as well?

**Comment by jainaashish** [comment]
@rrelyea This is not the dupe of #5806 So re-opening this again!

**Comment by rrelyea** [comment]
from @rohit21agrawal:

>  So turns out the following lines of code are the culprit here: https://github.com/NuGet/NuGet.BuildTasks/blob/dev/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.targets#L82-L84
> 
```
<UseTargetPlatformAsNuGetTargetMoniker Condition="'$(UseTargetPlatformAsNuGetTargetMoniker)' == '' AND '$(TargetFrameworkMoniker)' == '.NETCore,Version=v5.0'">true</UseTargetPlatformAsNuGetTargetMoniker>     
<NuGetTargetMoniker Condition="'$(NuGetTargetMoniker)' == '' AND '$(UseTargetPlatformAsNuGetTargetMoniker)' == 'true'">$(TargetPlatformIdentifier),Version=v$([System.Version]::Parse('$(TargetPlatformMinVersion)').ToString(3))</NuGetTargetMoniker>
     
<NuGetTargetMoniker Condition="'$(NuGetTargetMoniker)' == '' AND '$(UseTargetPlatformAsNuGetTargetMoniker)' != 'true'">$(TargetFrameworkMoniker)</NuGetTargetMoniker>
```

> Because the BuildTasks only set UseTargetPlatformAsNuGetTargetMoniker to true for projects which have TargetFrameworkMoniker == .NETCore,Version=v5.0, this doesn’t work for C++ UAP projects.
> 
> You can work around this by setting that property to true. I have already verified locally by using your repro project for the above workaround.

Given that info, we still need to determine the right fix, and what changed (if anything) since 15.2.

**Comment by rrelyea** [comment]
This was a fallout of the work we did to make UAP TFMs have "real versions".
This included work in VS to get TPMV from the project file, and add it to the framework in project.json.

We are investigating these possible fixes:
1. In VS for C++ projects, turn off the updating of the UAP version in project.json
1. Change the target logic that @rohit21agrawal  mentioned so that it supports native code better.
1. Other?

Investigating pros/cons of those options.

Workarounds:

- Restore from command line (msbuild /t:restore) and turn off restore in VS.
- Set msbuild property "UseTargetPlatformAsNuGetTargetMoniker" to true. (unsure of other side effects)

**Comment by rrelyea** [comment]
Fixed in VS 2017 version 15.3.3 (released on 8/29/2017).

**Comment by rrelyea** [comment]
my mistake...reopening..(confused the other issue with this one).

We are preparing a fix for this. After that, we'll work with VS Shiproom to deliver asap.
Workaround: restore from command line (msbuild /t:restore) instead of inside VS.

**Comment by KirillOsenkov** [comment]
Hello, I'm still seeing this (or very similar) problem in VS 15.5.2. 

Here's a .binlog file:
https://www.dropbox.com/s/c8ubkbyuslbpobs/NugetPackageExplorer.binlog?dl=0

@rohit21agrawal would you be able to take a look at the binlog and see why the project fails to build/restore? The error I'm getting:

```
"C:\NuGetPackageExplorer\NuGetPackageExplorer.sln" (default target) (1) ->
"C:\NuGetPackageExplorer\PackageExplorer.Package\PackageExplorer.Package.jsproj
.metaproj" (default target) (8) ->
"C:\NuGetPackageExplorer\PackageExplorer.Package\PackageExplorer.Package.jsproj
" (default target) (9) ->
(ResolveNuGetPackageAssets target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Micros
oft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project is not refe
rencing the "UAP,Version=v10.0" framework. Add a reference to "UAP,Version=v10.
0" in the "frameworks" section of your project.json, and then re-run NuGet rest
ore. [C:\NuGetPackageExplorer\PackageExplorer.Package\PackageExplorer.Package.j
sproj]
```
