### ISSUE TITLE
NuGet UI should write stack traces to the activity log instead of displaying them on screen

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#596]
The NuGet UI displays stack traces for expected exceptions. Users will consider this a crash and miss the actual error message that helps them fix the issue. The stack traces do not help the user, for debugging purposes the user should get this from the activity log instead.

Stack traces from searching bad package sources (also expected) should be logged to the activity log instead.

Steps:
1. create a new universal ios project
2. install microsoft.aspnet.mvc from the UI

Expected:
Just the error message

Actual:
An unhelpful and distracting stack trace fills the output window:

Attempting to gather dependencies information for package 'Microsoft.AspNet.Mvc.6.0.0-beta4' with respect to project 'App1', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'Microsoft.AspNet.Mvc.6.0.0-beta4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.AspNet.Mvc.6.0.0-beta4'
Resolved actions to install package 'Microsoft.AspNet.Mvc.6.0.0-beta4'
For adding package 'Microsoft.AspNet.Mvc 6.0.0-beta4' to project 'App1' that targets 'xamarinios1'.
Install failed. Rolling back...
Package 'Microsoft.AspNet.Mvc 6.0.0-beta4' does not exist in project 'App1'
Package 'Microsoft.AspNet.Mvc 6.0.0-beta4' does not exist in folder 'C:\Users\juste\Documents\Visual Studio 2015\Projects\App1\packages'
System.InvalidOperationException: Could not install package 'Microsoft.AspNet.Mvc 6.0.0-beta4'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()

**Comment by zhili1208** [comment]
fixed

**Comment by emgarten** [comment]
Reopening based on bug bash feedback, stack traces are still shown from UI exceptions.

**Comment by emgarten** [comment]
It may help to find all locations where logging to INuGetProjectContext occurs, and make sure the stack is not being logged.
