### ISSUE TITLE
project.assets.json doesn't have a target for .NETCoreApp,Version=v2.0

### ISSUE THREAD

**Issue by fabich** [NuGet/Home#6710]
## Details about Problem

NuGet version (x.x.x.xxx): 4.6.1.5019

dotnet.exe --version (if appropriate): 2.1.102

VS version (if appropriate):  15.6.3

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Build 10.0.16299.309

Worked before? If so, with which NuGet version: Issue after upgrading to VS 15.6.3

## Detailed repro steps so we can see the same problem

1. Debug application -> all good

2. Stop application --> all good

3. Make changes

4. Debug application --> error:
```
1>------ Build started: Project: <ProjectName>, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file 'C:\Users\<UserName>\Documents\GitHub\<Project>\<ProjectName>\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.
1>Done building project "<ProjectName>" -- FAILED.
```

5. Rebuild Solution -> all good

6. Debug application -> all good

## .csproj example:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BaseClasses\**" />
    <Compile Remove="Helpers\Controller\**" />
    <EmbeddedResource Remove="BaseClasses\**" />
    <EmbeddedResource Remove="Helpers\Controller\**" />
    <None Remove="BaseClasses\**" />
    <None Remove="Helpers\Controller\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="AgileObjects.ReadableExpressions" Version="1.11.0" />
    <PackageReference Include="Autofac" Version="4.6.2" />
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="FluentValidation" Version="7.5.2" />
    <PackageReference Include="IdentityModel" Version="3.3.0" />
    <PackageReference Include="Sendgrid" Version="9.9.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
  </ItemGroup>

</Project>
```

**Comment by Zorzin** [comment]
I have the same problem when publishing to Azure. Building works perfectly fine. Everything was working fine, one deploy went ok until I made small changes (only in .cs files) and now get this error. New project with same files not working, previous version of app from git also don't work, but previously do. Removing bin, obj folders, clean, restore - I tried everything and still nothing.

My csproj:

``` <Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>usersecretid</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.AutoScaling" Version="3.3.4.2" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.21.16" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.4" />
    <PackageReference Include="AWSSDK.Polly" Version="3.3.4.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.17.2" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

**Comment by livarcocc** [comment]
@fabich does this fail for you if you run `dotnet build` or `dotnet publish` on your project from the command line?

@nguerrera

**Comment by livarcocc** [comment]
@fabich how were you debugging the project you shared above? It is not an application. It does not have the OutputType property set to exe on it.

**Comment by fabich** [comment]
> @fabich does this fail for you if you run dotnet build or dotnet publish on your project from the command line?

No, I only receive an error when pressing F5 in VS or when running unit tests.
After running `dotnet build` I can run the application or unit tests again without any issues.
Until I do any changes (like deleting an empty folder) and the app won't debug again ...

> @fabich how were you debugging the project you shared above? It is not an application. It does not have the OutputType property set to exe on it.

This project is part of a Console Application.
But I most of the time test it with a unit test / integration test project in the same solution.

**Comment by jainaashish** [comment]
@fabich can you please set this `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1` in developer command prompt and start devenv from there? Then repro your issue, it will print out all the nomination details passed from Project system to NuGet in output window which will help narrow it down.

**Comment by jainaashish** [comment]
we are specifically looking for `TargetFramework` property value being passed

**Comment by fabich** [comment]
@jainaashish is this what you are looking for?
https://gist.github.com/fabich/ef49fb11e90b18b2e1e3492df9e07379

**Comment by jainaashish** [comment]
Thanks for sharing that! This looks right.

Can you share a sample repro solution to further analyze this issue?

**Comment by jainaashish** [comment]
And btw what is the failing project name in that log file you shared? and do you see `BEGIN Nominate Restore for <project name>` in that log?

**Comment by Zorzin** [comment]
I fixed my problem with publishing to Azure by removing "C:\Program Files\dotnet\sdk\2.1.102" folder and having only "2.1.101". Solution provided from [StackOverflow](https://stackoverflow.com/questions/49397793/error-publishing-net-core-2-0-web-applicaiton-to-azure-app-service)

**Comment by fabich** [comment]
@Zorzin it looks like this solved my problem as well, thanks!

> And btw what is the failing project name in that log file you shared? and do you see BEGIN Nominate Restore for <project name> in that log?

It's not always the same. Sometimes it's BI, sometimes CMN, sometimes others.
Yes, they are all in that log.

**Comment by dasMulli** [comment]
@fabich do you have ReSharper installed? A lot of ppl seem to be hitting an issue with conflicting NuGet assemblies in VS and ReSharper.

**Comment by fabich** [comment]
@dasMulli yes I have

**Comment by dasMulli** [comment]
See https://github.com/dotnet/sdk/issues/2068#issuecomment-374868287

> We've figured out the issue internally; an assembly resolver in the R# extension is incorrectly resolving one of our assemblies to one of their assemblies. This only occurs when .NET Core SDK 2.1.102 is installed, which comes with 15.6.3.
>
> We're working on a patch will be released in the next couple of days that will avoid R#'s assembly resolver to be called, and we're going to be working with R# to resolve the underlying issue.

**Comment by AndreyAkinshin** [comment]
The problem is fixed in ReSharper 2017.3.5, everything works with all combinations of Visual Studio and .NET Core SDK.
You can find more technical details in the official blog post: https://blog.jetbrains.com/dotnet/2018/03/23/build-failures-visual-studio-15-6-3-resharper-ultimate-2017-3-5-rescue/

**Comment by nguerrera** [comment]
Thanks! We also released VS 15.6.4 with a different version of nuget in sdk that manages to get around the issue.

**Comment by AndreyAkinshin** [comment]
@nguerrera, it's great that VS 15.6.4 is released, but it doesn't solve the problem in general case. E.g., if you use a specific version of .NET Core SDK (e.g., via global.json), you still have this problem.

**Comment by nguerrera** [comment]
Yes. Absolutely right. I just wanted to add a related note.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nkolev92** [comment]
Just closing the loop here. 
This has been resolved.

**Comment by MMN3003** [comment]
I had the same problem. I install dotnet sdk and runtime again. and use this code in cmd "dotnet F:\nikosa_both\nikosaBoth\nikosaBoth\bin\Debug\netcoreapp2.1\nikosaBoth.dll" and then I found my problem. I deleted package that have problem from csproj .  and now it work again

**Comment by olivierr91** [comment]
@nguerrera I'm not sure this has been resolved, I just encountered this problem with VS 15.7.5 after changing the .NET Core target from 2.0 to 2.1. I had to delete and reinstall the .NET Core SDK to get around the issue.

**Comment by nguerrera** [comment]
This error can trigger in different cases and could be unrelated to the root cause of the incident this issue tracked. Please open a new bug with repro steps if you encounter the message.
