### ISSUE TITLE
[NuGet.VisualStudioExtension] Installation of packages does not respect customized packages folder

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#755]
When installing a package, it will always enforce "%SolutionDir%\packages". When I build, it does restore packages and respects my path "..\lib".

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik can you specify exactly where you specify it (we just want to make sure we fix your scenario)

I assume it is in nuget.config (which level?)

and in this form:

```xml
config>
     <add key="repositorypath" value="C:\Temp" />
    </config>
```

Is this for Visual Studio 2015 RC? NuGet 3.0 RC or NuGet 3.0 RC-2 (https://nuget.codeplex.com/releases/view/615507)

**Comment by GeertvanHorrik** [comment]
1. VS 2015 RC / NuGet RC 2
2. See https://github.com/GitTools/GitTools.Core/blob/develop/src/nuget.config (actual repository it went wrong)

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik thanks for the feedback, you make our lives easy :)

**Comment by harshgMSFT** [comment]
Hi @GeertvanHorrik, I tried to repro the bug with 
1. VS 2015 RC  / Nuget RC 2 (https://nuget.codeplex.com/releases/view/615507).
2. VS 2015 RC / Nuget 3.0 RTM

Unfortunately it did not reproduce. Can you please list out the steps you followed ( I am assuming you restarted your vs after updating the Nuget.Config). 

Can you double check the version ?

**Comment by martinsuchan** [comment]
Same error here. I just updated to NuGet 3.0 RC2. My nuget.config located in the same folder as the solution file and contains this:

<settings>
	 <repositoryPath>../../../packages</repositoryPath>
</settings>

With VS2013 everything worked, but VS2015 with NuGet 3.0 RC2 tries to install packages into the default packages path.

**Comment by yishaigalatzer** [comment]
Can you list out the exact steps you are taking? And share the whole tree of nuget config, as well as your packages.config?

**Comment by harshgMSFT** [comment]
seems like this was fixed just 2 days after RC https://github.com/NuGet/Home/issues/626

**Comment by yishaigalatzer** [comment]
@zhili1208 looking at the suggested code for the fix (of respecting config changes outside of visual studio), I'm saying we take is slower, get a smaller more targeted fix.

Moving out of RTM milestone

**Comment by martinsuchan** [comment]
Regarding your question - this is my whole nuget.config file. How to reproduce it?

Open Solution with blank .NET project in VS2013 with this nuget.config in the same folder as the sln, click Manage NuGet packages, add Json.NET for instance as the only package, save it, close VS.

Now open the solution in VS2015, it builds fine, but if I open the Manage NuGet packages window it's telling me that some packages are missing and if I click Restore, they are restored in wrong directory.

This is in my opinion must fix for the RTM version, if it's not fixed already, it's also one of reasons I'm still using VS2013 instead of VS2015 RC.

**Comment by zhili1208** [comment]
@martinsuchan this is fixed in https://github.com/NuGet/Home/issues/626, but this fix is not in RC2 yet, will be in RTM, for your case, it will automatically work.

**Comment by lawrencejohnston** [comment]
Was this fixed in RTM or not? I'm still seeing the issue I reported in #626 in RTM (see my comment and request to reopen there).

Unfortunately this issue makes 2015 unusable for us too.

**Comment by martinsuchan** [comment]
Just updated NuGet Package Manager to 3.0.60624.657 and the bug is still there. This makes VS2015 virtually unusable for me right now.

**Comment by zhili1208** [comment]
@martinsuchan the setting formart is not working in this version. please change your config like this:
```xml
 <config>
    <add key="repositoryPath" value="..\..\..\packages" />
  </config>
```
here is the document for this: http://docs.nuget.org/consume/nuget-config-settings

**Comment by martinsuchan** [comment]
Thanks, it works. This should be probably mentioned somewhere, or NuGet could automatically convert the previous format to the new one.

**Comment by tbolon** [comment]
Hi,

I can reproduce this bug in VS 2015 RTM / NuGet Package Manager for VS v3.1.60724.766

Here are the steps I used:
- Create an empty solution on `D:\MySolution\MySolution.sln`
- Create a class library (net45 in my case) on `D:\MySolution\MyProject1\src\MyProject1\MyProject1.csproj`
- Create a nuget.config in `D:\MySolution\MyProject1\nuget.config` with the following settings

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="packages" />
  </config>
</configuration>
```
- using VS, install a package on MyProject1 (`xunit.runner.visualstudio` in my case).

**Expected :** the `packages` folder is created under `D:\MySolution\MyProject1\packages`

**Actual result :** the `packages` folder is created under `D:\MySolution\packages`

**Comment by yishaigalatzer** [comment]
@tbolon that is not supposed to work, the path is always relative to the solution, not the project

**Comment by tbolon** [comment]
Hum, perhaps "relative" should be clarified as concerning only the solution and not the config file itself.

Because nuget.config are recursive, this could be misleading as the [doc](http://docs.nuget.org/Release-Notes/NuGet-2.1#Specify-%e2%80%98packages%e2%80%99-Folder-Location) give the project path `C:\myteam\solution1\project1` as examined for config files.

**Comment by yishaigalatzer** [comment]
The link you are pointing to actually says:

> In this example, the shared nuget.config file specifies a **shared packages folder for every project** that is created beneath

I'm updating it to become more verbose, I also updated [this](http://docs.nuget.org/consume/NuGet-Config-Settings) document to clarify both issues reported in this bug.

**Comment by tbolon** [comment]
Thank you

**Comment by yishaigalatzer** [comment]
One tiny last thing. You can always suggest modification to our docs by submitting a pull request to the nugetdocs repo, its super simple to do

Sent from my Windows Phone

**Comment by tbolon** [comment]
You are right, I was clicking on the edit link on the documentation when you replied this issue. Too slow :smile:

**Comment by yishaigalatzer** [comment]
nice! Thanks for the report, you can never put enough time into docs

**Comment by zhili1208** [comment]
it's fixed in 3.2, close this bug
