### ISSUE TITLE
NuGet Manager does not always persist packages

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7830]
When installing or updating NuGet's in Visual Studio 2019 preview 3, the changes are not always persisted. While packages show as being installed or updated several minutes/builds later the changes are lost and the csproj is reverted to what it was before the install/update. Saving or closing the project does not always work either. 

My gut tells me this is probably related to another issue in which the IDE sometimes starts to get confused about files. This surfaces in a couple of ways.

- Clicking on a file you want to open you start to get error messages that you cannot move that object to that directory
- Trying to edit a new format csproj simply does nothing, as you can click on Edit `myproject.csproj` until the cows come home and nothing happens

The only solution I've found thus far is to restart Visual Studio and make NuGet changes from VS Code and then reopen the solution in Visual Studio.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/463869/nuget-manager-does-not-always-persist-packages.html
VSTS ticketId: 796714_

_These are the original issue comments:_

Visual Studio Feedback System on 2/20/2019, 11:00 PM (4 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

Rob Relyea [MSFT] on 2/23/2019, 08:35 PM (38 hours ago): <p>These projects are sdk style projects ? (Dotnet core)

Dan Siegel on 2/23/2019, 08:46 PM (37 hours ago): <p><a rel="user" href="https://developercommunityapi.westus.cloudapp.azure.com/users/1707/fd314950-9f6e-4bf9-90a0-982362e25620.html" nodeid="1707">@Rob Relyea [MSFT]</a> they all use PackageReference, but they don't seem to be limited to SDK Style projects... I've had the same issue with the iOS and Android projects in the solution. </p>

Rob Relyea [MSFT] on 2/24/2019, 10:11 AM (24 hours ago): <p>I suspect our recent work to cache the dgspec in obj, so that we work if a project is unloaded, restore can still work.</p><p>We’ll investigate early this week.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by rrelyea** [comment]
Updating bits to latest internal build of Preview4 and attempting to repro.
Curious about exact repro steps. What project type? (console app (.net core)? asp.net core? other? what versions of SDK?)
What packages are you installing?
Does it repro 100% of time? How often?

**Comment by rrelyea** [comment]
No repro. We suspect this is a PackageREference scenario where you diddn't ask the project file to be saved when asked...
??

**Comment by tub5** [comment]
Can confirm still happening in 16.0.1. Occurs sporadically when developing in a solution of 5 or more projects. When clicking on a project affected, the csproj is no longer editable or displayed. When updating NuGet packages it will revert back to the previous values within a minute.
Modifying the csproj file externally does enable the NuGet packages to be downloaded and used most of the time. However, it has been seen that even changes modified remotely are reverted at times.
This is becoming a serious issue with our team and we're having to revert back to VS2017 due to the productivity hit we are experiencing with VS2019.

**Comment by tub5** [comment]
> Updating bits to latest internal build of Preview4 and attempting to repro.

This is occurring in the latest stable build (16.0.1) as well.
> Curious about exact repro steps. What project type? (console app (.net core)? asp.net core? other? what versions of SDK?)

.NET Core Console/ASP.NET Core. SDK 2.2.203
> What packages are you installing?

This scenario occurs with any package
> Does it repro 100% of time? How often?

Sporadically. Usually after an hour or two constantly developing with the IDE

This has also been recorded [in the developer community](https://developercommunity.visualstudio.com/content/problem/447942/nuget-packages-getting-auto-removed.html)

**Comment by rrelyea** [comment]
Dupe of https://github.com/NuGet/Home/issues/8017
Believe the project system team fixed in 16.0.4 and 16.1.0-preview4?

**Comment by IdeaHunter** [comment]
it not fixed, please reopen
vs version 16.0.4
![it removes new packages](https://user-images.githubusercontent.com/10799080/60121445-bede5180-978b-11e9-91ab-2253b7604d7e.gif)
also, it even returns back packages that was deleted
![it ressurrects removed packages as well](https://user-images.githubusercontent.com/10799080/60121622-301e0480-978c-11e9-8455-03199e90c722.gif)

**Comment by IdeaHunter** [comment]
Restart wasn't working as a fix, neither deletion of packages, also i wast able to double click on project to see which packages it has in .proj file. 
The workaround that made it work for me is to do 'Close All Documents'. After they closed im no longer have a problem.
