### ISSUE TITLE
[DOCS] Issues building NuGet from Home page instructions

### ISSUE THREAD

**Issue by stunney** [NuGet/Home#787]
Moved from:
https://github.com/NuGet/NuGetGallery/issues/2539

My first hurdle was that I needed to add C:\Users\Stephen\Documents\GitHub\NuGet.Home\nupkgs as a local nuget repo so that NuGet.CommandLine.Cmd (beta 3.1.0) et al would install after all tests were completed.

I have gotten MUCH further in the compilation however now I am running into the following error

C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft
.NuGet.targets(58,5): error MSB4062: The "Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets" task could not be load
ed from the assembly C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integr
ation\build\Microsoft.NuGet.Build.Tasks.dll. Could not load file or assembly 'Microsoft.NuGet.Build.Tasks, Version=14.0
.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exc
eption from HRESULT: 0x8013141A) Confirm that the declaration is correct, that the assembly and all its dep
endencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:
\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]
Build failed
At C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\pack.ps1:78 char:5

throw "Build failed"
~~~~~~~~~~~~~~~~~~~~
CategoryInfo : OperationStopped: (Build failed:String) [], RuntimeException
FullyQualifiedErrorId : Build failed
I opened "C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integr
ation\build\Microsoft.NuGet.Build.Tasks.dll" in depends.x64 2.2.6000 and it is showing that this DLL is x86 compiled and ALL of its dependencies on my machine are x64.

IESHIMS.DLL
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-0.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-0.DLL
API-MS-WIN-CORE-FILE-L2-1-0.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-1-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-1.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-0.DLL
API-MS-WIN-CORE-SYSTEMTOPOLOGY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
KERNEL32.DLL
KERNELBASE.DLL
MSCOREE.DLL
NTDLL.DLL
ACLUI.DLL
ACTIVEDS.DLL
ADSLDPC.DLL
ADVAPI32.DLL
ADVPACK.DLL
API-MS-WIN-APPMODEL-IDENTITY-L1-1-0.DLL
API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-APPMODEL-STATE-L1-1-0.DLL
API-MS-WIN-BASE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-BEM-L1-1-0.DLL
API-MS-WIN-CORE-BIPLMAPI-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-0.DLL
API-MS-WIN-CORE-COM-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-JOB-L2-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-PATH-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L2-1-0.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRYUSERSPECIFIC-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-SHLWAPI-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-TOOLHELP-L1-1-0.DLL
API-MS-WIN-CORE-URL-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-VERSIONANSI-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERRORPRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-PROPERTYSETPRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-REGISTRATION-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-0.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-ADVAPI32-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-NORMALIZ-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-OLE32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHELL32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L2-1-0.DLL
API-MS-WIN-DOWNLEVEL-USER32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-VERSION-L1-1-0.DLL
API-MS-WIN-DX-D3DKMT-L1-1-0.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
API-MS-WIN-EVENTING-LEGACY-L1-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTLOG-LEGACY-L1-1-0.DLL
API-MS-WIN-MM-JOYSTICK-L1-1-0.DLL
API-MS-WIN-MM-MISC-L1-1-0.DLL
API-MS-WIN-MM-MISC-L2-1-0.DLL
API-MS-WIN-MM-MME-L1-1-0.DLL
API-MS-WIN-MM-TIME-L1-1-0.DLL
API-MS-WIN-NTUSER-DC-ACCESS-L1-1-0.DLL
API-MS-WIN-NTUSER-RECTANGLE-L1-1-0.DLL
API-MS-WIN-NTUSER-SYSPARAMS-L1-1-0.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-SECURITY-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
API-MS-WIN-SECURITY-AUDIT-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L2-1-0.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDLPARSECOND-L1-1-0.DLL
API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-0.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
API-MS-WIN-SHCORE-COMHELPERS-L1-1-0.DLL
API-MS-WIN-SHCORE-OBSOLETE-L1-1-0.DLL
API-MS-WIN-SHCORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-0.DLL
API-MS-WIN-SHCORE-STREAM-L1-1-0.DLL
API-MS-WIN-SHCORE-STREAM-WINRT-L1-1-0.DLL
API-MS-WIN-SHCORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-SHCORE-THREAD-L1-1-0.DLL
API-MS-WIN-SHCORE-UNICODEANSI-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLCOM-L1-1-0.DLL
API-MS-WIN-SHELL-SHELLFOLDERS-L1-1-0.DLL
APPHELP.DLL
APPREPAPI.DLL
AUTHZ.DLL
AVRT.DLL
BCP47LANGS.DLL
BCRYPT.DLL
BCRYPTPRIMITIVES.DLL
BROWCLI.DLL
CABINET.DLL
CERTCA.DLL
CFGMGR32.DLL
CHARTV.DLL
COMBASE.DLL
COMCTL32.DLL
COMCTL32.DLL
COMDLG32.DLL
CREDUI.DLL
CRYPT32.DLL
CRYPTBASE.DLL
CRYPTSP.DLL
CRYPTUI.DLL
CSCAPI.DLL
D2D1.DLL
D3D11.DLL
DAVHLPR.DLL
DBGHELP.DLL
DCOMP.DLL
DEVMGR.DLL
DEVOBJ.DLL
DEVRTL.DLL
DFSCLI.DLL
DHCPCSVC.DLL
DHCPCSVC6.DLL
DNSAPI.DLL
DPAPI.DLL
DRVSTORE.DLL
DSPARSE.DLL
DSROLE.DLL
DUI70.DLL
DUSER.DLL
DWMAPI.DLL
DWRITE.DLL
DXGI.DLL
EAPPCFG.DLL
EAPPPRXY.DLL
EFSADU.DLL
EFSUTIL.DLL
ELSCORE.DLL
ESENT.DLL
EXT-MS-WIN-ADVAPI32-EVENTINGCONTROLLER-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-MSI-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-PSM-APP-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-REMOTE-L1-1-0.DLL
EXT-MS-WIN-COM-CLBCATQ-L1-1-0.DLL
EXT-MS-WIN-COM-OLE32-L1-1-0.DLL
EXT-MS-WIN-COM-PSMREGISTER-L1-1-0.DLL
EXT-MS-WIN-DOMAINJOIN-NETJOIN-L1-1-0.DLL
EXT-MS-WIN-FIREWALLAPI-WEBPROXY-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-CREATE-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-L1-1-0.DLL
EXT-MS-WIN-GDI-DEVCAPS-L1-1-0.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-0.DLL
EXT-MS-WIN-GDI-FONT-L1-1-0.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-0.DLL
EXT-MS-WIN-GDI-PATH-L1-1-0.DLL
EXT-MS-WIN-GDI-RENDER-L1-1-0.DLL
EXT-MS-WIN-GDI-RGN-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-CURRENT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-PACKAGE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MPR-MULTIPLEPROVIDERROUTER-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-DC-ACCESS-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-GUI-L1-1-0.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-0.DLL
EXT-MS-WIN-NTUSER-MISC-L1-1-0.DLL
EXT-MS-WIN-NTUSER-PRIVATE-L1-1-0.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYSPARAMS-EXT-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOWCLASS-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOWSTATION-L1-1-0.DLL
EXT-MS-WIN-OLE32-BINDCTX-L1-1-0.DLL
EXT-MS-WIN-OLE32-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-PROFILE-USERENV-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CREDUI-L1-1-0.DLL
EXT-MS-WIN-SESSION-WINSTA-L1-1-0.DLL
EXT-MS-WIN-SESSION-WTSAPI32-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-CFGMGR32LOCAL-L1-1-0.DLL
EXT-MS-WIN-SETUPAPI-CFGMGR32REMOTE-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
EXT-MS-WIN-SHELL32-SHELLFOLDERS-L1-1-0.DLL
EXT-MS-WIN-SXS-OLEAUTOMATION-L1-1-0.DLL
EXT-MS-WIN-WLAN-ONEXUI-L1-1-0.DLL
FIREWALLAPI.DLL
FLTLIB.DLL
FMS.DLL
GDI32.DLL
GDIPLUS.DLL
HLINK.DLL
IEADVPACK.DLL
IEFRAME.DLL
IERTUTIL.DLL
IEUI.DLL
IMAGEHLP.DLL
IMGUTIL.DLL
IMM32.DLL
INETCOMM.DLL
IPHLPAPI.DLL
LINKINFO.DLL
LOGONCLI.DLL
MFC42U.DLL
MFPLAT.DLL
MLANG.DLL
MMDEVAPI.DLL
MPR.DLL
MPRAPI.DLL
MPRMSG.DLL
MRMCORER.DLL
MSASN1.DLL
MSCTF.DLL
MSFEEDS.DLL
MSHTML.DLL
MSI.DLL
MSILTCFG.DLL
MSIMG32.DLL
MSLS31.DLL
MSOERT2.DLL
MSRATING.DLL
MSVCRT.DLL
NCRYPT.DLL
NDFAPI.DLL
NETAPI32.DLL
NETUTILS.DLL
NEWDEV.DLL
NINPUT.DLL
NSI.DLL
NTASN1.DLL
NTDSAPI.DLL
NTSHRUI.DLL
OCCACHE.DLL
ODBC32.DLL
OLE32.DLL
OLEACC.DLL
OLEAUT32.DLL
OLEDLG.DLL
ONEX.DLL
PCACLI.DLL
PCWUM.DLL
POWRPROF.DLL
PRINTUI.DLL
PRNTVPT.DLL
PROFAPI.DLL
PROPSYS.DLL
PUIAPI.DLL
RASAPI32.DLL
RASDLG.DLL
RASMAN.DLL
REGAPI.DLL
RPCRT4.DLL
RSTRTMGR.DLL
RTUTILS.DLL
SAMCLI.DLL
SAMLIB.DLL
SCECLI.DLL
SECUR32.DLL
SENSAPI.DLL
SETUPAPI.DLL
SHCORE.DLL
SHDOCVW.DLL
SHELL32.DLL
SHLWAPI.DLL
SLC.DLL
SPFILEQ.DLL
SPINF.DLL
SPPC.DLL
SRVCLI.DLL
SSPICLI.DLL
TAPI32.DLL
TWINAPI.DLL
UIAUTOMATIONCORE.DLL
URLMON.DLL
USER32.DLL
USERENV.DLL
USP10.DLL
UXTHEME.DLL
VERSION.DLL
VIRTDISK.DLL
VPNIKEAPI.DLL
W32TOPL.DLL
WDI.DLL
WEBIO.DLL
WEBSERVICES.DLL
WEBSOCKET.DLL
WER.DLL
WERUI.DLL
WEVTAPI.DLL
WINBRAND.DLL
WINDOWSCODECS.DLL
WINHTTP.DLL
WININET.DLL
WINMM.DLL
WINMMBASE.DLL
WINNSI.DLL
WINSCARD.DLL
WINSPOOL.DRV
WINSTA.DLL
WINTRUST.DLL
WKSCLI.DLL
WLANAPI.DLL
WLDAP32.DLL
WMICLNT.DLL
WS2_32.DLL
WTSAPI32.DLL
XMLLITE.DLL

**Comment by yishaigalatzer** [comment]
Here are some tips while we are fixing the instructions (from @danliu)

1.	Make sure the generated .nupkg file folder is added as one of the package sources, i.e. $BranchRoot\Home\nupkgs
2.	Make sure to switch to Dev branch of the Home repo, so that scripts from dev branch is used for building
3.	Start a new PowerShell window to run build-nuget.ps1 script, after that, switch to NuGet.VisualStudioExtension directory to call Build.cmd to finish building.

**Comment by stunney** [comment]
Ok, I seem to have gotten a little further now.  I'm getting an error during the TEST EXECUTION SUMMARY as shown below with a stack trace:

=== TEST EXECUTION SUMMARY ===
   NuGet.Commands.Test  Total: 11, Errors: 0, Failed: 0, Skipped: 0, Time: 10.940s
info: Exec
info:   program: cmd
info:   commandline: /C "C:\Users\Stephen\Documents\GitHub\NuGet3\packages\KoreBuild\build\dnvm" use default -runtime Co
reCLR && dnx . test
info:   workingdir: test\NuGet.Commands.Test
Adding C:\Users\Stephen\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta6-12032\bin to process PATH
xUnit.net ASP.NET test runner (32-bit DNXCore 5.0)
Copyright (C) 2015 Outercurve Foundation.

Discovering: NuGet.Commands.Test
Discovered:  NuGet.Commands.Test
Starting:    NuGet.Commands.Test
   NuGet.Commands.Test.RestoreCommandTests.RestoreCommand_UnmatchedRefAndLibAssemblies [FAIL]
      System.Threading.SemaphoreFullException : Adding the specified count to the semaphore would cause it to exceed its
 maximum count.
      Stack Trace:
            at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
            at System.Threading.SemaphoreSlim.Release()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Common\ConcurrencyUtilities.cs(37,0): at NuGet.Common.Concur
rencyUtilities.<ExecuteWithFileLocked>d__0`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Protocol.Core.v3\RemoteRepositories\RemoteV2FindPackageByIdR
esource.cs(272,0): at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResourcce.<OpenNupkgStreamAsync>d
__36.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Protocol.Core.v3\RemoteRepositories\PackageUtilities.cs(33,0
): at NuGet.Protocol.Core.v3.RemoteRepositories.PackageUtilities.<OpenNuspecStreamFromNupkgAsync>d__1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Protocol.Core.v3\RemoteRepositories\RemoteV2FindPackageByIdR
esource.cs(101,0): at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResourcce.<GetDependencyInfoAsync
>d__31.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.DependencyResolver\SourceRepositoryDependencyProvider.cs(68,
0): at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d__9.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.DependencyResolver.Core\Remote\RemoteDependencyWalker.cs(145
,0): at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryEntry>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.DependencyResolver.Core\Remote\RemoteDependencyWalker.cs(36,
0): at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.DependencyResolver.Core\Remote\RemoteDependencyWalker.cs(93,
0): at NuGet.DependencyResolver.RemoteDependencyWalker.<CreateGraphNode>d__3.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(503,0): at NuGet.Commands.Restore
Command.<WalkDependencies>d__13.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(148,0): at NuGet.Commands.Restore
Command.<ExecuteRestore>d__5.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(50,0): at NuGet.Commands.RestoreC
ommand.<ExecuteAsync>d__4.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         RestoreCommandTests.cs(376,0): at NuGet.Commands.Test.RestoreCommandTests.<RestoreCommand_UnmatchedRefAndLibAss
emblies>d__9.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    NuGet.Commands.Test

=== TEST EXECUTION SUMMARY ===
   NuGet.Commands.Test  Total: 11, Errors: 0, Failed: 1, Skipped: 0, Time: 4.965s
warn: Exit code 1 from cmd
verbose: Stack trace:
   at View0ec397bbce304381b8b1701f06f96cb8.K(String command, String workingdir, String dnvmUse) in c:\Users\Stephen\AppD
ata\Local\Temp\23d48bd6cf18416f9a50b099fad01a1b-1.cs:line 1370
   at View0ec397bbce304381b8b1701f06f96cb8.DnxTest(String projectFile, Boolean testParallel) in c:\Users\Stephen\AppData
\Local\Temp\23d48bd6cf18416f9a50b099fad01a1b-1.cs:line 437
   at View0ec397bbce304381b8b1701f06f96cb8.<RenderViewLevel0>b__73(String projectFile) in c:\Users\Stephen\AppData\Local
\Temp\23d48bd6cf18416f9a50b099fad01a1b-1.cs:line 7621
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at View0ec397bbce304381b8b1701f06f96cb8.<RenderViewLevel0>b__71() in c:\Users\Stephen\AppData\Local\Temp\23d48bd6cf18
416f9a50b099fad01a1b-1.cs:line 7621
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0ec397bbce304381b8b1701f06f96cb8.<RenderViewLevel0>b__53() in c:\Users\Stephen\AppData\Local\Temp\23d48bd6cf18
416f9a50b099fad01a1b-1.cs:line 1876
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View0ec397bbce304381b8b1701f06f96cb8.<RenderViewLevel0>b__4b() in c:\Users\Stephen\AppData\Local\Temp\23d48bd6cf18
416f9a50b099fad01a1b-1.cs:line 1732
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
last exit code 1
Build failed. Project directory is C:\Users\Stephen\Documents\GitHub\NuGet3
At C:\Users\Stephen\Documents\GitHub\Home\build-nuget.ps1:48 char:9
+         throw $errorMessage
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed. P...s\GitHub\NuGet3:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed. Project directory is C:\Users\Stephen\Documents\GitHub\NuGet3

**Comment by yishaigalatzer** [comment]
Can you pull the latest code? We have made some changes in this code in the last hour or so (and still making) we currently see a single broken unit test. We are working on fixing it, but the call stack we see has a null reference exception. 

Please let us know what it looks like after you try again.

**Comment by yishaigalatzer** [comment]
Actually, this is a reate catch. We are going to push in a change shortly to see if we can get this fixed

Thanks!

**Comment by stunney** [comment]
Re-ran clone-repo.ps1 sync at 8:42 Eastern Time.  The script already points to the dev branch.
No errors

Running build-nuget.ps1 afterwards produced the following unit test failure:
xUnit.net ASP.NET test runner (32-bit DNX 4.5.1)
Copyright (C) 2015 Outercurve Foundation.

Discovering: NuGet.Commands.Test
Discovered:  NuGet.Commands.Test
Starting:    NuGet.Commands.Test
   NuGet.Commands.Test.RestoreCommandTests.RestoreCommand_UnmatchedRefAndLibAssemblies [FAIL]
      System.Threading.SemaphoreFullException : Adding the specified count to the semaphore would cause it to exceed its
 maximum count.
      Stack Trace:
            at System.Threading.SemaphoreSlim.Release(Int32 releaseCount)
            at System.Threading.SemaphoreSlim.Release()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Common\ConcurrencyUtilities.cs(37,0): at NuGet.Common.Concur
rencyUtilities.<ExecuteWithFileLocked>d__0`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Protocol.Core.v3\RemoteRepositories\RemoteV2FindPackageByIdR
esource.cs(272,0): at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResourcce.<OpenNupkgStreamAsync>d
__36.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Protocol.Core.v3\RemoteRepositories\RemoteV2FindPackageByIdR
esource.cs(119,0): at NuGet.Protocol.Core.v3.RemoteRepositories.RemoteV2FindPackageByIdResourcce.<GetNupkgStreamAsync>d_
_32.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.DependencyResolver\SourceRepositoryDependencyProvider.cs(77,
0): at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<CopyToAsync>d__10.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Packaging\PackageExtraction\NuGetPackageUtils.cs(58,0): at N
uGet.Packaging.NuGetPackageUtils.<>c__DisplayClass1_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Common\ConcurrencyUtilities.cs(33,0): at NuGet.Common.Concur
rencyUtilities.<ExecuteWithFileLocked>d__0`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Packaging\PackageExtraction\NuGetPackageUtils.cs(39,0): at N
uGet.Packaging.NuGetPackageUtils.<InstallFromSourceAsync>d__1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(610,0): at NuGet.Commands.Restore
Command.<InstallPackage>d__18.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(586,0): at NuGet.Commands.Restore
Command.<InstallPackages>d__17.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(157,0): at NuGet.Commands.Restore
Command.<ExecuteRestore>d__5.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         C:\Users\Stephen\Documents\GitHub\NuGet3\src\NuGet.Commands\RestoreCommand.cs(50,0): at NuGet.Commands.RestoreC
ommand.<ExecuteAsync>d__4.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         RestoreCommandTests.cs(376,0): at NuGet.Commands.Test.RestoreCommandTests.<RestoreCommand_UnmatchedRefAndLibAss
emblies>d__9.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    NuGet.Commands.Test

=== TEST EXECUTION SUMMARY ===
   NuGet.Commands.Test  Total: 11, Errors: 0, Failed: 1, Skipped: 0, Time: 11.102s
warn: Exit code 1 from cmd
verbose: Stack trace:
   at Viewe4efc5008f1c4852b17328545e59c302.K(String command, String workingdir, String dnvmUse) in c:\Users\Stephen\AppD
ata\Local\Temp\9d83158d57c0497f9c00ac3eb736626c-1.cs:line 1277
   at Viewe4efc5008f1c4852b17328545e59c302.DnxTest(String projectFile, Boolean testParallel) in c:\Users\Stephen\AppData
\Local\Temp\9d83158d57c0497f9c00ac3eb736626c-1.cs:line 433
   at Viewe4efc5008f1c4852b17328545e59c302.<RenderViewLevel0>b__6f(String projectFile) in c:\Users\Stephen\AppData\Local
\Temp\9d83158d57c0497f9c00ac3eb736626c-1.cs:line 7638
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Viewe4efc5008f1c4852b17328545e59c302.<RenderViewLevel0>b__6d() in c:\Users\Stephen\AppData\Local\Temp\9d83158d57c0
497f9c00ac3eb736626c-1.cs:line 7638
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewe4efc5008f1c4852b17328545e59c302.<RenderViewLevel0>b__4f() in c:\Users\Stephen\AppData\Local\Temp\9d83158d57c0
497f9c00ac3eb736626c-1.cs:line 1893
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewe4efc5008f1c4852b17328545e59c302.<RenderViewLevel0>b__47() in c:\Users\Stephen\AppData\Local\Temp\9d83158d57c0
497f9c00ac3eb736626c-1.cs:line 1749
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
last exit code 1
Build failed. Project directory is C:\Users\Stephen\Documents\GitHub\NuGet3
At C:\Users\Stephen\Documents\GitHub\Home\build-nuget.ps1:47 char:9
+         throw $errorMessage
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed. P...s\GitHub\NuGet3:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed. Project directory is C:\Users\Stephen\Documents\GitHub\NuGet3

**Comment by stunney** [comment]
Running build.cmd in NuGet.VisualStudeionExtension produced the following error:
PS C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension> .\build.cmd
Microsoft (R) Build Engine version 14.0.22823.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/15/2015 8:49:38 PM.
Project "C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\Build\Build.proj" on node 1 (RestorePackages tar
get(s)).
RestorePackages:
  Restoring packages ...
  C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\.nuget\nuget.exe install NuGet.CommandLine.Cmd -Exclude
  Version -Out C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\packages -NoCache -pre
  Unable to find package 'NuGet.CommandLine.Cmd'.
C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\Build\Build.proj(146,9): error MSB3073: The command "C:\U
sers\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\.nuget\nuget.exe install NuGet.CommandLine.Cmd -ExcludeVersio
n -Out C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\packages -NoCache -pre " exited with code 1.
Done Building Project "C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\Build\Build.proj" (RestorePackages
 target(s)) -- FAILED.


Build FAILED.

"C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\Build\Build.proj" (RestorePackages target) (1) ->
(RestorePackages target) ->
  C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\Build\Build.proj(146,9): error MSB3073: The command "C:
\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\.nuget\nuget.exe install NuGet.CommandLine.Cmd -ExcludeVers
ion -Out C:\Users\Stephen\Documents\GitHub\NuGet.VisualStudioExtension\packages -NoCache -pre " exited with code 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.41

**Comment by stunney** [comment]
Ok, I completely cleaned my workspace and re-did the git clone command and \NuGet.Home\nupkgs doesn't get created automatically by the script.  That's an early error (I must have worked around that and forgotten).

**Comment by stunney** [comment]
Ok, now that I've completely cleaned my environment I'm back to to nupkgs folder issue.
The script originally complained that \NuGet.Home\nupkgs didn't exist.  Then the script creates \nupkgs  as a sibbling to NuGet.Home.  This folder is where all nupkg files are pushed to.
![image](https://cloud.githubusercontent.com/assets/609012/8173891/83c4ea76-13a2-11e5-9e56-0e7ec7a4301f.png).
Adding this directory to my list of packages sources in VS2015 has no effect.

I created a directory symlink using 
mklink /D ./NuGet.Home/nupkgs ./nupkgs
with elevated privileges to get this to work. (copying ALL the files also works, but I wanted to be sure that I wasn't missing a newer package that maybe a test had written out.

After that I get back to our notorious Test failure:
NuGet.Commands.Test.RestoreCommandTests.RestoreCommand_UnmatchedRefAndLibAssemblies

**Comment by yishaigalatzer** [comment]
Can you verify you have the following commit in your source tree? https://github.com/NuGet/NuGet3/commit/c8c4b85dfe130c0d58a00fc3dd41dbc72d6febb2

**Comment by stunney** [comment]
It appears as though I do *NOT* have this change.  Strange how I didn't get this when I deleted everything and re-cloned less than an hour ago.

**Comment by stunney** [comment]
Just wiped it all clean again, and doing the clone-repos.ps1 and I seem to now be getting this specific  commit in the sources on my disk.

**Comment by yishaigalatzer** [comment]
cool, this commit was a fix to the test failure. I'm hoping that you are going to get past this issue now.

**Comment by stunney** [comment]
Ok, I've moved to another issue :(

C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft.NuGet.targets(58,5): error MSB4062: The "Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets" task could not be loaded from the assembly C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft.NuGet.Build.Tasks.dll. Could not load file or assembly 'Microsoft.NuGet.Build.Tasks, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]

C:\Users\Stephen\Documents\GitHub\nupkgs\NuGet.Versioning.3.1.0-beta.symbols.nupkg".
Building! configuration: debug
Build failed
At C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\pack.ps1:78 char:5
+           throw "Build failed"
+           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed

**Comment by stunney** [comment]
I think this is the same error in that I listed earlier.

I opened "C:\Users\Stephen\Documents\GitHub\NuGet.Home\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft.NuGet.Build.Tasks.dll" in depends.x64 2.2.6000 and it is showing that this DLL is x86 compiled and ALL of its dependencies on my machine are x64.

**Comment by yishaigalatzer** [comment]
I think this dll is not fully signed, and you need a strong name hijack to make it work. My machine is also x64 and I'm seeing no issues, but I do have a hijack.

I'm going to look into getting a fully signed version available on the feed.

CC // @jasonmalinowski can we share a fully signed build? Can/Should the task be AnyCPU?

**Comment by stunney** [comment]
Ok, I've used sn.exe -Vr Microsoft.NuGet.Build.Tasks.dll to add an exception entry into my registry to attempt to get around this.  If this works a fully signed build should do as a long-term fix I think.

**Comment by stunney** [comment]
That didn't do it.  Attempting to do sn -Vr Newtonsoft.Json as well in the same build folder (NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build)

**Comment by stunney** [comment]
Just a heads up that those are the *only* two assemblies that are strong (delayed or otherwise) signed in the folder

    Directory: \NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         6/15/2015  10:38 PM      37848 Microsoft.NuGet.Build.Tasks.dll
-a---         6/15/2015  10:38 PM     502272 Newtonsoft.Json.dll
-a---         6/15/2015  10:38 PM      28640 NuGet.ContentModel.dll
-a---         6/15/2015  10:38 PM      35296 NuGet.DependencyResolver.Core.dll
-a---         6/15/2015  10:38 PM      16352 NuGet.DependencyResolver.dll
-a---         6/15/2015  10:38 PM      64480 NuGet.Frameworks.dll
-a---         6/15/2015  10:38 PM      21472 NuGet.LibraryModel.dll
-a---         6/15/2015  10:38 PM      22496 NuGet.Packaging.Core.dll
-a---         6/15/2015  10:38 PM      21472 NuGet.Packaging.Core.Types.dll
-a---         6/15/2015  10:38 PM      55776 NuGet.Packaging.dll
-a---         6/15/2015  10:38 PM      40928 NuGet.ProjectModel.dll
-a---         6/15/2015  10:38 PM      15328 NuGet.Repositories.dll
-a---         6/15/2015  10:38 PM      36320 NuGet.Versioning.dll
-a---         6/15/2015  10:38 PM     233688 System.Collections.Immutable.dll

**Comment by stunney** [comment]
No dice.  Any suggestions for the SN Hijacking?

**Comment by stunney** [comment]
Ah, I ran the x64 version of sn.exe.  Had to run the x86 version.  Getting a little further but have this error now:

Utility\BuildIntegratedProjectUtility.cs(38,78): error CS0117: 'SettingsUtility' does not contain a definition for 'GetGlobalPackagesFolder' [C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]
Utility\BuildIntegratedProjectUtility.cs(47,78): error CS0117: 'SettingsUtility' does not contain a definition for 'GetGlobalPackagesFolder' [C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]
Projects\PackagesConfigNuGetProject.cs(225,84): error CS1061: 'PackageReaderBase' does not contain a definition for 'GetDevelopmentDependency' and no extension method 'GetDevelopmentDependency' accepting a first argument of type 'PackageReaderBase' could be found (are you missing a using directive or an assembly reference?) [C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]
Projects\PackagesConfigNuGetProject.cs(232,60): error CS1061: 'NuspecReader' does not contain a definition for 'GetDevelopmentDependency' and no extension method 'GetDevelopmentDependency' accepting a first argument of type 'NuspecReader' could be found (are you missing a using directive or an assembly reference?) [C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]

**Comment by yishaigalatzer** [comment]
Looks like you still have some synching issues - https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Configuration/Utility/SettingsUtility.cs does have the right overloads.

I'm checking out for the day, I'll pick it up tomorrow again.

**Comment by stunney** [comment]
We can pick up again tomorrow.  I'm looking at the source and see the right overloads.  Could it be a stale reference perhaps?

Have a good night!

**Comment by stunney** [comment]
I have also hit the issue that @hubuk has hit in #783 here:

& : The term 'C:\Users\Stephen\Documents\GitHub\NuGet.PackageManagement\pack.ps1' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\Stephen\Documents\GitHub\Home\build-nuget.ps1:78 char:7
+     & "$GitRoot\NuGet.PackageManagement\pack.ps1" @args
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Stephe...gement\pack.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Build failed
At C:\Users\Stephen\Documents\GitHub\Home\build-nuget.ps1:84 char:9
+         throw "Build failed"
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed

**Comment by stunney** [comment]
Has this been resolved yet?  I'd like to get on with building and generating pull requests please :)

**Comment by yishaigalatzer** [comment]
You should be able to build now. But please before submitting pull requests please file an issue an discuss the idea with the team.

Deepak is going to verify and resolve this week, which is why this is open.

Also note that we are not going to be taking prs into dev for a few more weeks until visual studio releases

**Comment by yishaigalatzer** [comment]
Note - NuGet command line is building from https://github.com/nuget/nuget.packagemanagement

**Comment by MeniZalzman** [comment]
We fixed this issues please make sure you are using the Dev branch in the Home repo and make sure to pull to get the update build script

**Comment by stunney** [comment]
Has the documentation been updated on the Home web page?  I still cannot build from a fresh command line sync right now.

**Comment by MeniZalzman** [comment]
Thanks for the feedback, can you sync again and run the build script with the following:
.\Home\build-nuget.ps1 -CleanCache
The clean cache will make sure all the cache packages get deleted

**Comment by sliekens** [comment]
@yishaigalatzer @MeniZalzman  I just joined the party and it looks like this is still not fixed.

> Build failed
> At D:\src\NuGet.PackageManagement\pack.ps1:80 char:5
> -           throw "Build failed"
> -           ~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
>   - FullyQualifiedErrorId : Build failed

Last info log before the build crashes

> Generating MSBuild file D:\src\NuGet.PackageManagement\test\NuGet.CommandLine.Test\**NuGet.CommandLine.Test.csproj.nuget.targets**.
> Generating MSBuild file D:\src\NuGet.PackageManagement\test\NuGet.CommandLine.Test\**NuGet.CommandLine.Test.csproj.nuget.props**.

This is the error

> D:\src\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft.NuGet.targets(58,5): error MSB4062: The "Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets" task could not be loaded from the assembly D:\src\NuGet.PackageManagement\packages\NuGet.MsBuild.Integration\build\Microsoft.NuGet.Build.Tasks.dll. Could not load file or assembly '**Microsoft.NuGet.Build.Tasks**, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. **Strong name validation failed**. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\src\NuGet.PackageManagement\src\ProjectManagement\ProjectManagement.csproj]

**Comment by yishaigalatzer** [comment]
Hey Steven we are in another change mode. The home build was failing in various cases and we are moving to a simpler model.

We will document in details but here is the jist:

Pre requisites:
Vs 2015 with window 10 tools, visual studio SDK and ASP.net 5 beta7

Clone nuget.client, use the dev branch
Run Build.ps1

You will see two solutions
Core and clients

The first builds xproj projects and generates nuget packages, the second generates the vsix and nuget.exe

To debug the vsix you will need to uninstall nuget from your visual studio.

You also want to uncheck the jit option in debugging, otherwise it gets optimized too much for useful debugging.

Last keep in mind that we are still making changes and haven't announced it publicly. So you might find rough edges. It should be better than what we have in the home at the moment.
