### ISSUE TITLE
“Browse” tab can’t show the embedded icon of the package from DevOps private feeds

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9250]
## Details about Problem
NuGet version: NuGet Client Dev\5.6.0.6479
VS Version: Master\29902.138
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a Console App (.NET Core 3.1) in VS and open the PM UI of the solution.
2.	Add the [DevOps feed](https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json ) into the Settings->NuGet Package Manager->Package Sources.
3.  Select the new added DevOps feed in the Package source dropdown box in the PM UI and install the package [**classlib.net48 -version 1.0.5** (don’t have the backlash problem in bug 9225), **dotnet.icon -version 1.0.0** (embedded icon)]
4.  Check all the tabs in PM UI. 
## Expected
The embedded icon should show correctly in all the tabs of PM UI.
## Actual
Only “Browse” tab can’t show the embedded icon of the package from DevOps feed as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/75776381-df38c400-5d8e-11ea-93ce-c4cda3a6d87e.png)

## Note
It doesn't repro for the nuget.org feed.

**Comment by dominoFire** [comment]
@karann-msft @jmyersmsft

**Comment by jmyersmsft** [comment]
Azure Artifacts does not yet support extracting embedded icons to re-host them, so it has no icon to provide to VS. For already-installed packages, NuGet is pulling the icon from the .nupkg that it already has on disk.

This is near the top of our (Azure Artifacts's) backlog, but I can't give any more concrete information about timeline.

To be clear, this is an Azure Artifacts problem, not a NuGet problem.
Also, this doesn't affect the content of the packages in any way, just what we return in search results.

**Comment by zivkan** [comment]
Closing as per the comment above. NuGet added a new feature and Azure Artifacts hasn't yet implemented it.

**Comment by dominoFire** [comment]
I will use this issue as an Epic to track all efforts to enable this scenario in NuGet PM UI and Azure DevOps

**Comment by donnie-msft** [comment]
Closed as Duplicate a VS Feedback ticket around this issue (1114782)

**Comment by AroglDarthu** [comment]
Just want to mention that this issue also happens on the "Updates" and "Consolidate" tabs.

**Comment by rrelyea** [comment]
putting on my plate right now...as I am doing work in this area.

**Comment by donnie-msft** [comment]
New upvotes on https://developercommunity2.visualstudio.com/t/nuget-package-projecticon-azure-devops-artifacts-i/1014111?from=email&viewtype=all#T-ND1307513

**Comment by rrelyea** [comment]
fixed in dev build 7084, which isn't inserted into P4 yet...but we hope to this week.

**Comment by v-luzh** [comment]
Reactivate this bug since it still repro on Main\31101.164 + NuGet Client Dev\5.10.0.7152. Please help to check if the fix is merged to dev branch? Thanks.

**Comment by rrelyea** [comment]
yes, was mistakenly closed. i fixed embedded icons...but doesn't yet work with authenticated feeds. More work to do that..

**Comment by woeterman94** [comment]
Any updates on this?
It still doesn't work even with a valid .nuspec file

![image](https://user-images.githubusercontent.com/5755057/138058934-2a09c206-52a6-4e09-bde7-38a664663495.png)

![image](https://user-images.githubusercontent.com/5755057/138058995-78e876bc-5612-4332-a68c-b0d653007558.png)

![image](https://user-images.githubusercontent.com/5755057/138059057-ba58d52c-2fae-4bcd-8497-12f025bcf3d4.png)

**Comment by Nexusmeister** [comment]
Are there any updates on this problem?

**Comment by Xyotic** [comment]
Also looking forward to this!

**Comment by StefanOverHaevgRZ** [comment]
Probably no update?

**Comment by TheRealAyCe** [comment]
It works when your package only has an `iconUrl`.
The main problem here is that it forces you to use `iconUrl` **only**. It would be fine if it would default to using the `iconUrl` when both it and `icon` are available. But as soon as you use both (which is the recommended thing to do it seems?), it ignores  `iconUrl` and no longer shows an actual icon.
```xml
    <icon>nugeticon.png</icon>
    <iconUrl>some icon url address</iconUrl>
```
doesn't work in the feed search (but does, once installed).

```xml
    <iconUrl>some icon url address</iconUrl>
```
does work in the feed search and once installed, but is no longer recommended.

Please just make it use `iconUrl` if available, until you've implemented re-hosting of package internal icons. You're **already** doing that if `icon` is not set!

**Comment by michael-hawker** [comment]
Think we've been hitting this as well, really hard to know. Also makes it impossible to validate packages have the proper icon setup on our private feed before we publish...

**Comment by jimSampica** [comment]
Intra-organization packages would be much more identifiable with this fixed.

**Comment by donnie-msft** [comment]
Going to take a look this Sprint to see if I can articulate the problem with this icon binding.

**Comment by DaleyKD** [comment]
@donnie-msft : Any update?

I know this seems like a silly thing we're requesting, but it sure would be nice for Azure Artifacts to support standard nuspec stuff.

Thanks!

**Comment by Nexusmeister** [comment]
> Intra-organization packages would be much more identifiable with this fixed.

This is a problem that we are facing like every day. It is a little "bug" but it annoys while validating the correct package

**Comment by donnie-msft** [comment]
> @donnie-msft : Any update?
> 
> I know this seems like a silly thing we're requesting, but it sure would be nice for Azure Artifacts to support standard nuspec stuff.
> 
> Thanks!

Not yet, I ended up having to move it to November Sprint, and Quality Week will be next week which is when I'll look into this task.
Thanks for your patience!

**Comment by DaleyKD** [comment]
I appreciate that. I'm glad to hear that ADO isn't forgotten. There are many times it feels like it is, especially with buggy Build Tasks.

**Comment by donnie-msft** [comment]
I've found that there's a few ways to encounter this problem. Out of curiosity, how many of you are seeing this with an Azure DevOps feed with [upstream package sources](https://learn.microsoft.com/en-us/azure/devops/artifacts/how-to/public-feeds-upstream-sources?view=azure-devops&tabs=nuget)?

**Comment by DaleyKD** [comment]
We do, but I don't know why:
![image](https://github.com/NuGet/Home/assets/7206282/6dea6d0e-f1d5-4ef4-9370-4bc3ab2f5d2b)

**Comment by donnie-msft** [comment]
Providing an update on what I've found and a rough draft of my notes:

- Package icon HTTP calls are made without any auth consideration here: https://github.com/NuGet/NuGet.Client/blob/29f292950dfa50aea030bd74c3277e983eff711e/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetPackageFileService.cs#L195
- Once a failed HTTP call is made, the default package icon is cached and used thereafter
- The GPF/fallback folders may have the package and its icon, but reading local repositories are not attempted

My rough draft proposal would be:
- Plumb in an `HttpSource` / `SourceRepository` that has a resource which can make authenticated HTTP calls.
- Look in GPF/fallback folders for icons first (reduce need for HTTP calls when the machine already has the icon)

Questions/concerns:

AzDo package sources with Upstreaming: I'm not yet clear if the authenticated HTTP call would cause AzDo to save packages to the feed when Browse tab makes authenticated requests for icons. My guess is that it would save those packages (as it does that when installing a package that exists on an upstream). Questions to be understood are 1. is that a problematic side effect for those feeds and 2. does it have performance implications on Client that need more design work.

**Comment by jmyersmsft** [comment]
Current implementation in Azure Artifacts is to return a 404 when asked to extract an icon from a package from upstream that hasn't been saved to the feed.

That could possibly be changed in the future to do something like forward the request on to the upstream, but that's nontrivial for us. We pull nuspecs from PackageBaseAddress to get metadata rather than the registrations API, so we don't have the upstream's IconUrl at hand.

**Comment by smkanadl** [comment]
I never use upstream sources. Since a nuget.config file with package source mapping makes it quite easy to setup multiple packages sources, I will not need package icons from upstream sources at all.

**Comment by felipementel** [comment]
I'm preparing material to create a video on my YouTube channel, and I came across exactly this problem.

I am unable to place an icon for my package, published in Azure DevOps Artifacts.

I've tried using different tags in csproj, different file formats, but nothing works.

I will leave my example of how I am publishing the package, using YAML Pipelines
```
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
   branches:
     include:
     -main
     - feature/*

pool:
   vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
   inputs:
     packageType: 'sdk'
     version: '8.0.x'

- task: DotNetCoreCLI@2
   displayName: Restore
   inputs:
     command: 'custom'
     projects: '**/*.csproj'
     custom: 'restore'

- task: DotNetCoreCLI@2
   displayName: Build
   inputs:
     command: 'custom'
     projects: '**/*.csproj'
     custom: 'build'
     arguments: '--no-restore'

- task: DotNetCoreCLI@2
   displayName: Pack
   inputs:
     command: 'pack'
     packagesToPack: '**/*.csproj'
     versioningScheme: 'off'

- task: NuGetCommand@2
   displayName: 'NuGet push'
   inputs:
     command: push
     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
     publishVstsFeed: 'felipementel-packages'
     nuGetFeedType: 'internal'
     noCache: true
     allowPackageConflicts: true
```

and this is my csproj (without any icon references, as no tag worked)
```
<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
<TargetFramework>net8.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
<Version>1.0.8</Version>
<VersionSuffix>-alpha-1.0</VersionSuffix>
<Authors>Felipe P Augusto</Authors>
<Company>DEPLOY</Company>
<PackageTags>Microsoft .NET;Channel DEPLOY</PackageTags>
<Description>Example API and documentation too
It may contain a link, such as this example https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/README.md and https://github. com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md</Description>
<RepositoryType>git</RepositoryType>
</PropertyGroup>


<ItemGroup>
<Content Include="FileAttachment.txt">
<CopyToOutputDirectory>Always</CopyToOutputDirectory>
<PackageCopyToOutput>true</PackageCopyToOutput>
<pack>true</pack>
</Content>
</ItemGroup>

<ItemGroup>
<EmbeddedResource Include="AttachmentFile.txt" />
</ItemGroup>

</Project>
```

![image](https://github.com/NuGet/Home/assets/14238257/2b39ffd9-fefe-48bf-a8b5-576be4939fc0)


if anyone can help.

**Comment by TheRealAyCe** [comment]
@felipementel I always use this in my NuGet projects:

```
		<!-- TODO: Uncomment this once the Azure Feed/NuGet team fixes icon display when searching: https://github.com/NuGet/Home/issues/9250 -->
		<!--<PackageIcon>nugeticon.png</PackageIcon>-->

		<PackageIconUrl>url path to png file like uploaded @ imgur</PackageIconUrl>



	<ItemGroup>
		<None Include="../nugeticon.png" Pack="true" PackagePath="" />
	</ItemGroup>
```

**Comment by TheRealAyCe** [comment]
@felipementel I don't think it's possible to display a custom icon in that menu at all.

**Comment by LockTar** [comment]
Hammer seems I'm not the only one with this problem. Hopefully this will be fixed ASAP

**Comment by v-luzh** [comment]
It still reproes on VS Main\35222.175 with implicit NuGet Client Dev\6.12.0.82.

**Comment by donnie-msft** [comment]
Providing a status update & plan outline:

1. ➡️[PR in review (see screenshot)] Read icon from GPF when the icon is on the machine locally already (partial improvement):  [Attempt Loading package Icon from local folders to avoid accessing remote feeds for metadata by donnie-msft · Pull Request #6009 · NuGet/NuGet.Client (github.com)](https://github.com/NuGet/NuGet.Client/pull/6009)
2. 🚧[On plate for September 2024] Show broken icon status indicator when the icon still isn't available [PM UI Icon Status could be indicated with an Overlay on Default Icon · Issue #10122 · NuGet/Home (github.com)](https://github.com/NuGet/Home/issues/10122)
3. 💡[Needs design discussion] Hypothesis/trial needed: see if authenticating icon requests helps in any scenario to actually retrieve an icon remotely.
4. Work with AzDo to determine if any changes can be made to improve how clients access icon from upstream sources.

_Sample of improvement for PR in point # 1:_
![image](https://github.com/user-attachments/assets/b555d096-3dc1-4764-af19-f4108f51599d)

**Comment by zivkan** [comment]
related:

* https://github.com/NuGet/Home/issues/14273

Now that PM UI can show readmes, it can't get the readmes from private feeds.

**Comment by zivkan** [comment]
I've been thinking recently about NuGet's HTTP auth, and it reminded me of this issue. I'm fairly confident we need to change the protocol to make this feature secure.

The problem is that package authors can provide any random URL in the package's `iconUrl` metadata. It was convenient for nuget.org to re-use the same `iconUrl` metadata for embedded icons, and Visual Studio worked without changes for nuget.org. But for private package sources, now Visual Studio can't tell if the URL is just some CDN of the package source, or the package author supplied URL. If the package author controls the HTTP server, they could configure it to send HTTP 401 responses to unauthenticated requests. NuGet must not send customer credentials to the server in this scenario.

Therefore, there must be a change to the HTTP protocol, so NuGet knows whether the server is hosting an embedded icon, or if the icon URL is 3rd party and therefore cannot be trusted with secure credentials.

**Comment by donnie-msft** [comment]
Closed a duplicate from Developer Community: https://developercommunity.visualstudio.com/t/Azure-Artifacts-feed-shows-generic-icon-/11126154
